/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

class Accumulator {
    // Index by Mesg# and DestField#
    private var accumulatedFields: ArrayList<AccumulatedField> = ArrayList()

    fun set(mesgNum: Int, destFieldNum: Int, value: Long) {
        findOrCreateField(mesgNum, destFieldNum).set(value)
    }

    fun accumulate(mesgNum: Int, destFieldNum: Int, value: Long, bits: Int) =
        findOrCreateField(mesgNum, destFieldNum).accumulate(value, bits)

    private fun findOrCreateField(mesgNum: Int, destFieldNum: Int) =
        accumulatedFields.find { it.mesgNum == mesgNum && it.destFieldNum == destFieldNum }
            ?: AccumulatedField(mesgNum, destFieldNum).also { accumulatedFields.add(it) }

    private class AccumulatedField(
        val mesgNum: Int, //Field# to accumulate into
        val destFieldNum: Int
    ) {
        private var lastValue: Long = 0
        private var accumulatedValue: Long = 0

        fun accumulate(value: Long, bits: Int): Long {
            val mask = (1L shl bits) - 1

            accumulatedValue += (value - lastValue) and mask
            lastValue = value

            return accumulatedValue
        }

        fun set(value: Long): Long {
            accumulatedValue = value
            lastValue = value
            return accumulatedValue
        }
    }
}