/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


enum class ActivitySubtype(var value: Short) {
    GENERIC(0.toShort()),
    TREADMILL(1.toShort()),
    STREET(2.toShort()),
    TRAIL(3.toShort()),
    TRACK(4.toShort()),
    SPIN(5.toShort()),
    INDOOR_CYCLING(6.toShort()),
    ROAD(7.toShort()),
    MOUNTAIN(8.toShort()),
    DOWNHILL(9.toShort()),
    RECUMBENT(10.toShort()),
    CYCLOCROSS(11.toShort()),
    HAND_CYCLING(12.toShort()),
    TRACK_CYCLING(13.toShort()),
    INDOOR_ROWING(14.toShort()),
    ELLIPTICAL(15.toShort()),
    STAIR_CLIMBING(16.toShort()),
    LAP_SWIMMING(17.toShort()),
    OPEN_WATER(18.toShort()),
    ALL(254.toShort()),
    INVALID(255.toShort());


    companion object {
        fun getByValue(value: Short): ActivitySubtype {
            for (type in entries) {
                if (value == type.value) return type
            }

            return INVALID
        }

        /**
         * Retrieves the String Representation of the Value
         * @param value The enum constant
         * @return The name of this enum constant
         */
        fun getStringFromValue(value: ActivitySubtype): String {
            return value.name
        }
    }
}
