/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

object BandedExercisesExerciseName {
    const val AB_TWIST: Int = 1
    const val BACK_EXTENSION: Int = 2
    const val BICYCLE_CRUNCH: Int = 3
    const val CALF_RAISES: Int = 4
    const val CHEST_PRESS: Int = 5
    const val CLAM_SHELLS: Int = 6
    const val CURL: Int = 7
    const val DEADBUG: Int = 8
    const val DEADLIFT: Int = 9
    const val DONKEY_KICK: Int = 10
    const val EXTERNAL_ROTATION: Int = 11
    const val EXTERNAL_ROTATION_AT_90_DEGREE_ABDUCTION: Int = 12
    const val FACE_PULL: Int = 13
    const val FIRE_HYDRANT: Int = 14
    const val FLY: Int = 15
    const val FRONT_RAISE: Int = 16
    const val GLUTE_BRIDGE: Int = 17
    const val HAMSTRING_CURLS: Int = 18
    const val HIGH_PLANK_LEG_LIFTS: Int = 19
    const val HIP_EXTENSION: Int = 20
    const val INTERNAL_ROTATION: Int = 21
    const val JUMPING_JACK: Int = 22
    const val KNEELING_CRUNCH: Int = 23
    const val LATERAL_BAND_WALKS: Int = 24
    const val LATERAL_RAISE: Int = 25
    const val LATPULL: Int = 26
    const val LEG_ABDUCTION: Int = 27
    const val LEG_ADDUCTION: Int = 28
    const val LEG_EXTENSION: Int = 29
    const val LUNGE: Int = 30
    const val PLANK: Int = 31
    const val PULL_APART: Int = 32
    const val PUSH_UPS: Int = 33
    const val REVERSE_CRUNCH: Int = 34
    const val ROW: Int = 35
    const val SHOULDER_ABDUCTION: Int = 36
    const val SHOULDER_EXTENSION: Int = 37
    const val SHOULDER_EXTERNAL_ROTATION: Int = 38
    const val SHOULDER_FLEXION_TO_90_DEGREES: Int = 39
    const val SIDE_PLANK_LEG_LIFTS: Int = 40
    const val SIDE_RAISE: Int = 41
    const val SQUAT: Int = 42
    const val SQUAT_TO_PRESS: Int = 43
    const val TRICEP_EXTENSION: Int = 44
    const val TRICEP_KICKBACK: Int = 45
    const val UPRIGHT_ROW: Int = 46
    const val WALL_CRAWL_WITH_EXTERNAL_ROTATION: Int = 47
    const val LATERAL_RAISE_WHEELCHAIR: Int = 49
    const val TRICEPS_EXTENSION_WHEELCHAIR: Int = 50
    const val CHEST_FLY_INCLINE_WHEELCHAIR: Int = 51
    const val CHEST_FLY_DECLINE_WHEELCHAIR: Int = 52
    const val PULL_DOWN_WHEELCHAIR: Int = 53
    const val STRAIGHT_ARM_PULL_DOWN_WHEELCHAIR: Int = 54
    const val CURL_WHEELCHAIR: Int = 55
    const val OVERHEAD_CURL_WHEELCHAIR: Int = 56
    const val FACE_PULL_WHEELCHAIR: Int = 57
    const val AROUND_THE_WORLD_WHEELCHAIR: Int = 58
    const val PULL_APART_WHEELCHAIR: Int = 59
    const val SIDE_CURL_WHEELCHAIR: Int = 60
    const val OVERHEAD_PRESS_WHEELCHAIR: Int = 61
    const val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap = mutableMapOf<Int, String>()

    init {
        stringMap[AB_TWIST] = "AB_TWIST"
        stringMap[BACK_EXTENSION] = "BACK_EXTENSION"
        stringMap[BICYCLE_CRUNCH] = "BICYCLE_CRUNCH"
        stringMap[CALF_RAISES] = "CALF_RAISES"
        stringMap[CHEST_PRESS] = "CHEST_PRESS"
        stringMap[CLAM_SHELLS] = "CLAM_SHELLS"
        stringMap[CURL] = "CURL"
        stringMap[DEADBUG] = "DEADBUG"
        stringMap[DEADLIFT] = "DEADLIFT"
        stringMap[DONKEY_KICK] = "DONKEY_KICK"
        stringMap[EXTERNAL_ROTATION] = "EXTERNAL_ROTATION"
        stringMap[EXTERNAL_ROTATION_AT_90_DEGREE_ABDUCTION] =
            "EXTERNAL_ROTATION_AT_90_DEGREE_ABDUCTION"
        stringMap[FACE_PULL] = "FACE_PULL"
        stringMap[FIRE_HYDRANT] = "FIRE_HYDRANT"
        stringMap[FLY] = "FLY"
        stringMap[FRONT_RAISE] = "FRONT_RAISE"
        stringMap[GLUTE_BRIDGE] = "GLUTE_BRIDGE"
        stringMap[HAMSTRING_CURLS] = "HAMSTRING_CURLS"
        stringMap[HIGH_PLANK_LEG_LIFTS] = "HIGH_PLANK_LEG_LIFTS"
        stringMap[HIP_EXTENSION] = "HIP_EXTENSION"
        stringMap[INTERNAL_ROTATION] = "INTERNAL_ROTATION"
        stringMap[JUMPING_JACK] = "JUMPING_JACK"
        stringMap[KNEELING_CRUNCH] = "KNEELING_CRUNCH"
        stringMap[LATERAL_BAND_WALKS] = "LATERAL_BAND_WALKS"
        stringMap[LATERAL_RAISE] = "LATERAL_RAISE"
        stringMap[LATPULL] = "LATPULL"
        stringMap[LEG_ABDUCTION] = "LEG_ABDUCTION"
        stringMap[LEG_ADDUCTION] = "LEG_ADDUCTION"
        stringMap[LEG_EXTENSION] = "LEG_EXTENSION"
        stringMap[LUNGE] = "LUNGE"
        stringMap[PLANK] = "PLANK"
        stringMap[PULL_APART] = "PULL_APART"
        stringMap[PUSH_UPS] = "PUSH_UPS"
        stringMap[REVERSE_CRUNCH] = "REVERSE_CRUNCH"
        stringMap[ROW] = "ROW"
        stringMap[SHOULDER_ABDUCTION] = "SHOULDER_ABDUCTION"
        stringMap[SHOULDER_EXTENSION] = "SHOULDER_EXTENSION"
        stringMap[SHOULDER_EXTERNAL_ROTATION] = "SHOULDER_EXTERNAL_ROTATION"
        stringMap[SHOULDER_FLEXION_TO_90_DEGREES] = "SHOULDER_FLEXION_TO_90_DEGREES"
        stringMap[SIDE_PLANK_LEG_LIFTS] = "SIDE_PLANK_LEG_LIFTS"
        stringMap[SIDE_RAISE] = "SIDE_RAISE"
        stringMap[SQUAT] = "SQUAT"
        stringMap[SQUAT_TO_PRESS] = "SQUAT_TO_PRESS"
        stringMap[TRICEP_EXTENSION] = "TRICEP_EXTENSION"
        stringMap[TRICEP_KICKBACK] = "TRICEP_KICKBACK"
        stringMap[UPRIGHT_ROW] = "UPRIGHT_ROW"
        stringMap[WALL_CRAWL_WITH_EXTERNAL_ROTATION] = "WALL_CRAWL_WITH_EXTERNAL_ROTATION"
        stringMap[LATERAL_RAISE_WHEELCHAIR] = "LATERAL_RAISE_WHEELCHAIR"
        stringMap[TRICEPS_EXTENSION_WHEELCHAIR] = "TRICEPS_EXTENSION_WHEELCHAIR"
        stringMap[CHEST_FLY_INCLINE_WHEELCHAIR] = "CHEST_FLY_INCLINE_WHEELCHAIR"
        stringMap[CHEST_FLY_DECLINE_WHEELCHAIR] = "CHEST_FLY_DECLINE_WHEELCHAIR"
        stringMap[PULL_DOWN_WHEELCHAIR] = "PULL_DOWN_WHEELCHAIR"
        stringMap[STRAIGHT_ARM_PULL_DOWN_WHEELCHAIR] = "STRAIGHT_ARM_PULL_DOWN_WHEELCHAIR"
        stringMap[CURL_WHEELCHAIR] = "CURL_WHEELCHAIR"
        stringMap[OVERHEAD_CURL_WHEELCHAIR] = "OVERHEAD_CURL_WHEELCHAIR"
        stringMap[FACE_PULL_WHEELCHAIR] = "FACE_PULL_WHEELCHAIR"
        stringMap[AROUND_THE_WORLD_WHEELCHAIR] = "AROUND_THE_WORLD_WHEELCHAIR"
        stringMap[PULL_APART_WHEELCHAIR] = "PULL_APART_WHEELCHAIR"
        stringMap[SIDE_CURL_WHEELCHAIR] = "SIDE_CURL_WHEELCHAIR"
        stringMap[OVERHEAD_PRESS_WHEELCHAIR] = "OVERHEAD_PRESS_WHEELCHAIR"
    }


    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum contsant
     */
    fun getStringFromValue(value: Int): String {
        if (stringMap.containsKey(value)) {
            return stringMap[value] ?: ""
        }

        return ""
    }

    /**
     * Returns the enum constant with the specified name.
     * @param value The enum string value
     * @return The enum constant or INVALID if unknown
     */
    fun getValueFromString(value: String): Int {
        for (entry in stringMap.entries) {
            if (entry.value == value) {
                return entry.key
            }
        }

        return INVALID
    }
}
