/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


enum class CameraEventType(val value: Short) {
    VIDEO_START(0),
    VIDEO_SPLIT(1),
    VIDEO_END(2),
    PHOTO_TAKEN(3),
    VIDEO_SECOND_STREAM_START(4),
    VIDEO_SECOND_STREAM_SPLIT(5),
    VIDEO_SECOND_STREAM_END(6),
    VIDEO_SPLIT_START(7),
    VIDEO_SECOND_STREAM_SPLIT_START(8),
    VIDEO_PAUSE(11),
    VIDEO_SECOND_STREAM_PAUSE(12),
    VIDEO_RESUME(13),
    VIDEO_SECOND_STREAM_RESUME(14),
    INVALID(255);


    companion object {
        fun getByValue(value: Short): CameraEventType {
            for (type in entries) {
                if (value == type.value) return type
            }

            return INVALID
        }

        /**
         * Retrieves the String Representation of the Value
         * @param value The enum constant
         * @return The name of this enum constant
         */
        fun getStringFromValue(value: CameraEventType): String {
            return value.name
        }
    }
}
