/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


enum class ExdLayout(val value: Short) {
    FULL_SCREEN(0),
    HALF_VERTICAL(1),
    HALF_HORIZONTAL(2),
    HALF_VERTICAL_RIGHT_SPLIT(3),
    HALF_HORIZONTAL_BOTTOM_SPLIT(4),
    FULL_QUARTER_SPLIT(5),
    HALF_VERTICAL_LEFT_SPLIT(6),
    HALF_HORIZONTAL_TOP_SPLIT(7),
    DYNAMIC(8),
    INVALID(255);


    companion object {
        fun getByValue(value: Short): ExdLayout {
            for (type in entries) {
                if (value == type.value) return type
            }

            return INVALID
        }

        /**
         * Retrieves the String Representation of the Value
         * @param value The enum constant
         * @return The name of this enum constant
         */
        fun getStringFromValue(value: ExdLayout): String {
            return value.name
        }
    }
}
