/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


enum class Language(val value: Short) {
    ENGLISH(0),
    FRENCH(1),
    ITALIAN(2),
    GERMAN(3),
    SPANISH(4),
    CROATIAN(5),
    CZECH(6),
    DANISH(7),
    DUTCH(8),
    FINNISH(9),
    GREEK(10),
    HUNGARIAN(11),
    NORWEGIAN(12),
    POLISH(13),
    PORTUGUESE(14),
    SLOVAKIAN(15),
    SLOVENIAN(16),
    SWEDISH(17),
    RUSSIAN(18),
    TURKISH(19),
    LATVIAN(20),
    UKRAINIAN(21),
    ARABIC(22),
    FARSI(23),
    BULGARIAN(24),
    ROMANIAN(25),
    CHINESE(26),
    JAPANESE(27),
    KOREAN(28),
    TAIWANESE(29),
    THAI(30),
    HEBREW(31),
    BRAZILIAN_PORTUGUESE(32),
    INDONESIAN(33),
    MALAYSIAN(34),
    VIETNAMESE(35),
    BURMESE(36),
    MONGOLIAN(37),
    CUSTOM(254),
    INVALID(255);


    companion object {
        fun getByValue(value: Short): Language {
            for (type in entries) {
                if (value == type.value) return type
            }

            return INVALID
        }

        /**
         * Retrieves the String Representation of the Value
         * @param value The enum constant
         * @return The name of this enum constant
         */
        fun getStringFromValue(value: Language): String {
            return value.name
        }
    }
}
