/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


enum class WktStepTarget(val value: Short) {
    SPEED(0),
    HEART_RATE(1),
    OPEN(2),
    CADENCE(3),
    POWER(4),
    GRADE(5),
    RESISTANCE(6),
    POWER_3S(7),
    POWER_10S(8),
    POWER_30S(9),
    POWER_LAP(10),
    SWIM_STROKE(11),
    SPEED_LAP(12),
    HEART_RATE_LAP(13),
    INVALID(255);


    companion object {
        fun getByValue(value: Short): WktStepTarget {
            for (type in entries) {
                if (value == type.value) return type
            }

            return INVALID
        }

        /**
         * Retrieves the String Representation of the Value
         * @param value The enum constant
         * @return The name of this enum constant
         */
        fun getStringFromValue(value: WktStepTarget): String {
            return value.name
        }
    }
}
