/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


class AntRxMesg : Mesg {
    constructor() : super(Factory.createMesg(MesgNum.ANT_RX))

    constructor(mesg: Mesg) : super(mesg)


    var timestamp: DateTime?
        /**
         * Get timestamp field
         * Units: s
         *
         * @return timestamp
         */
        get() = timestampToDateTime(getFieldLongValue(253, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD))
        /**
         * Set timestamp field
         * Units: s
         *
         * @param timestamp The new timestamp value to be set
         */
        set(timestamp) {
            setFieldValue(253, 0, timestamp?.timestamp, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var fractionalTimestamp: Float?
        /**
         * Get fractional_timestamp field
         * Units: s
         *
         * @return fractional_timestamp
         */
        get() = getFieldFloatValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set fractional_timestamp field
         * Units: s
         *
         * @param fractionalTimestamp The new fractionalTimestamp value to be set
         */
        set(fractionalTimestamp) {
            setFieldValue(0, 0, fractionalTimestamp, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var mesgId: Byte?
        /**
         * Get mesg_id field
         *
         * @return mesg_id
         */
        get() = getFieldByteValue(1, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set mesg_id field
         *
         * @param mesgId The new mesgId value to be set
         */
        set(mesgId) {
            setFieldValue(1, 0, mesgId, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    val mesgData: Array<Byte>?
        get() = getFieldByteValues(2, Fit.SUBFIELD_INDEX_MAIN_FIELD)

    val numMesgData: Int
        /**
         * @return number of mesg_data
         */
        get() = getNumFieldValues(2, Fit.SUBFIELD_INDEX_MAIN_FIELD)

    /**
     * Get mesg_data field
     *
     * @param index of mesg_data
     * @return mesg_data
     */
    fun getMesgData(index: Int): Byte? {
        return getFieldByteValue(2, index, Fit.SUBFIELD_INDEX_MAIN_FIELD)
    }

    /**
     * Set mesg_data field
     *
     * @param index of mesg_data
     * @param mesgData The new mesgData value to be set
     */
    fun setMesgData(index: Int, mesgData: Byte?) {
        setFieldValue(2, index, mesgData, Fit.SUBFIELD_INDEX_MAIN_FIELD)
    }

    var channelNumber: Short?
        /**
         * Get channel_number field
         *
         * @return channel_number
         */
        get() = getFieldShortValue(3, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set channel_number field
         *
         * @param channelNumber The new channelNumber value to be set
         */
        set(channelNumber) {
            setFieldValue(3, 0, channelNumber, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    val data: Array<Byte>?
        get() = getFieldByteValues(4, Fit.SUBFIELD_INDEX_MAIN_FIELD)

    val numData: Int
        /**
         * @return number of data
         */
        get() = getNumFieldValues(4, Fit.SUBFIELD_INDEX_MAIN_FIELD)

    /**
     * Get data field
     *
     * @param index of data
     * @return data
     */
    fun getData(index: Int): Byte? {
        return getFieldByteValue(4, index, Fit.SUBFIELD_INDEX_MAIN_FIELD)
    }

    /**
     * Set data field
     *
     * @param index of data
     * @param data The new data value to be set
     */
    fun setData(index: Int, data: Byte?) {
        setFieldValue(4, index, data, Fit.SUBFIELD_INDEX_MAIN_FIELD)
    }

    companion object {
        const val TimestampFieldNum: Int = 253

        const val FractionalTimestampFieldNum: Int = 0

        const val MesgIdFieldNum: Int = 1

        const val MesgDataFieldNum: Int = 2

        const val ChannelNumberFieldNum: Int = 3

        const val DataFieldNum: Int = 4


        val antRxMesg: Mesg

        init {
            var field_index = 0
            // ant_rx
            antRxMesg = Mesg("ant_rx", MesgNum.ANT_RX)
            antRxMesg.addField(
                Field(
                    "timestamp",
                    TimestampFieldNum,
                    134,
                    1.0,
                    0.0,
                    "s",
                    false,
                    Profile.Type.DATE_TIME
                )
            )
            field_index++
            antRxMesg.addField(
                Field(
                    "fractional_timestamp",
                    FractionalTimestampFieldNum,
                    132,
                    32768.0,
                    0.0,
                    "s",
                    false,
                    Profile.Type.UINT16
                )
            )
            field_index++
            antRxMesg.addField(
                Field(
                    "mesg_id",
                    MesgIdFieldNum,
                    13,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.BYTE
                )
            )
            field_index++
            antRxMesg.addField(
                Field(
                    "mesg_data",
                    MesgDataFieldNum,
                    13,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.BYTE
                )
            )
            antRxMesg.fields[field_index].components.add(
                FieldComponent(
                    3,
                    false,
                    8,
                    1.0,
                    0.0
                )
            ) // channel_number
            antRxMesg.fields[field_index].components.add(
                FieldComponent(
                    4,
                    false,
                    8,
                    1.0,
                    0.0
                )
            ) // data
            antRxMesg.fields[field_index].components.add(
                FieldComponent(
                    4,
                    false,
                    8,
                    1.0,
                    0.0
                )
            ) // data
            antRxMesg.fields[field_index].components.add(
                FieldComponent(
                    4,
                    false,
                    8,
                    1.0,
                    0.0
                )
            ) // data
            antRxMesg.fields[field_index].components.add(
                FieldComponent(
                    4,
                    false,
                    8,
                    1.0,
                    0.0
                )
            ) // data
            antRxMesg.fields[field_index].components.add(
                FieldComponent(
                    4,
                    false,
                    8,
                    1.0,
                    0.0
                )
            ) // data
            antRxMesg.fields[field_index].components.add(
                FieldComponent(
                    4,
                    false,
                    8,
                    1.0,
                    0.0
                )
            ) // data
            antRxMesg.fields[field_index].components.add(
                FieldComponent(
                    4,
                    false,
                    8,
                    1.0,
                    0.0
                )
            ) // data
            antRxMesg.fields[field_index].components.add(
                FieldComponent(
                    4,
                    false,
                    8,
                    1.0,
                    0.0
                )
            ) // data
            field_index++
            antRxMesg.addField(
                Field(
                    "channel_number",
                    ChannelNumberFieldNum,
                    2,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT8
                )
            )
            field_index++
            antRxMesg.addField(
                Field(
                    "data",
                    DataFieldNum,
                    13,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.BYTE
                )
            )
            field_index++
        }
    }
}
