/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

object AttitudeValidity {
    const val TRACK_ANGLE_HEADING_VALID: Int = 0x0001
    const val PITCH_VALID: Int = 0x0002
    const val ROLL_VALID: Int = 0x0004
    const val LATERAL_BODY_ACCEL_VALID: Int = 0x0008
    const val NORMAL_BODY_ACCEL_VALID: Int = 0x0010
    const val TURN_RATE_VALID: Int = 0x0020
    const val HW_FAIL: Int = 0x0040
    const val MAG_INVALID: Int = 0x0080
    const val NO_GPS: Int = 0x0100
    const val GPS_INVALID: Int = 0x0200
    const val SOLUTION_COASTING: Int = 0x0400
    const val TRUE_TRACK_ANGLE: Int = 0x0800
    const val MAGNETIC_HEADING: Int = 0x1000
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: MutableMap<Int?, String?>

    init {
        stringMap = HashMap<Int?, String?>()
        stringMap.put(TRACK_ANGLE_HEADING_VALID, "TRACK_ANGLE_HEADING_VALID")
        stringMap.put(PITCH_VALID, "PITCH_VALID")
        stringMap.put(ROLL_VALID, "ROLL_VALID")
        stringMap.put(LATERAL_BODY_ACCEL_VALID, "LATERAL_BODY_ACCEL_VALID")
        stringMap.put(NORMAL_BODY_ACCEL_VALID, "NORMAL_BODY_ACCEL_VALID")
        stringMap.put(TURN_RATE_VALID, "TURN_RATE_VALID")
        stringMap.put(HW_FAIL, "HW_FAIL")
        stringMap.put(MAG_INVALID, "MAG_INVALID")
        stringMap.put(NO_GPS, "NO_GPS")
        stringMap.put(GPS_INVALID, "GPS_INVALID")
        stringMap.put(SOLUTION_COASTING, "SOLUTION_COASTING")
        stringMap.put(TRUE_TRACK_ANGLE, "TRUE_TRACK_ANGLE")
        stringMap.put(MAGNETIC_HEADING, "MAGNETIC_HEADING")
    }


    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum contsant
     */
    fun getStringFromValue(value: Int?): String? {
        if (stringMap.containsKey(value)) {
            return stringMap.get(value)
        }

        return ""
    }

    /**
     * Returns the enum constant with the specified name.
     * @param value The enum string value
     * @return The enum constant or INVALID if unknown
     */
    fun getValueFromString(value: String?): Int? {
        for (entry in stringMap.entries) {
            if (entry.value == value) {
                return entry.key
            }
        }

        return INVALID
    }
}
