/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


enum class AutoSyncFrequency(var value: Short) {
    NEVER(0.toShort()),
    OCCASIONALLY(1.toShort()),
    FREQUENT(2.toShort()),
    ONCE_A_DAY(3.toShort()),
    REMOTE(4.toShort()),
    INVALID(255.toShort());


    companion object {
        fun getByValue(value: Short): AutoSyncFrequency {
            for (type in entries) {
                if (value == type.value) return type
            }

            return INVALID
        }

        /**
         * Retrieves the String Representation of the Value
         * @param value The enum constant
         * @return The name of this enum constant
         */
        fun getStringFromValue(value: AutoSyncFrequency): String {
            return value.name
        }
    }
}
