/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


class BarometerDataMesg : Mesg, AllFitMesg {
    constructor() : super(Factory.createMesg(MesgNum.BAROMETER_DATA))

    constructor(mesg: Mesg) : super(mesg)


    var timestamp: DateTime?
        /**
         * Get timestamp field
         * Units: s
         * Comment: Whole second part of the timestamp
         *
         * @return timestamp
         */
        get() = timestampToDateTime(getFieldLongValue(253, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD))
        /**
         * Set timestamp field
         * Units: s
         * Comment: Whole second part of the timestamp
         *
         * @param timestamp The new timestamp value to be set
         */
        set(timestamp) {
            setFieldValue(253, 0, timestamp?.timestamp, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var timestampMs: Int?
        /**
         * Get timestamp_ms field
         * Units: ms
         * Comment: Millisecond part of the timestamp.
         *
         * @return timestamp_ms
         */
        get() = getFieldIntegerValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set timestamp_ms field
         * Units: ms
         * Comment: Millisecond part of the timestamp.
         *
         * @param timestampMs The new timestampMs value to be set
         */
        set(timestampMs) {
            setFieldValue(0, 0, timestampMs, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    val sampleTimeOffset: Array<Int>?
        get() = getFieldIntegerValues(1, Fit.SUBFIELD_INDEX_MAIN_FIELD)

    val numSampleTimeOffset: Int
        /**
         * @return number of sample_time_offset
         */
        get() = getNumFieldValues(1, Fit.SUBFIELD_INDEX_MAIN_FIELD)

    /**
     * Get sample_time_offset field
     * Units: ms
     * Comment: Each time in the array describes the time at which the barometer sample with the corrosponding index was taken. The samples may span across seconds. Array size must match the number of samples in baro_cal
     *
     * @param index of sample_time_offset
     * @return sample_time_offset
     */
    fun getSampleTimeOffset(index: Int): Int? {
        return getFieldIntegerValue(1, index, Fit.SUBFIELD_INDEX_MAIN_FIELD)
    }

    /**
     * Set sample_time_offset field
     * Units: ms
     * Comment: Each time in the array describes the time at which the barometer sample with the corrosponding index was taken. The samples may span across seconds. Array size must match the number of samples in baro_cal
     *
     * @param index of sample_time_offset
     * @param sampleTimeOffset The new sampleTimeOffset value to be set
     */
    fun setSampleTimeOffset(index: Int, sampleTimeOffset: Int?) {
        setFieldValue(1, index, sampleTimeOffset, Fit.SUBFIELD_INDEX_MAIN_FIELD)
    }

    val baroPres: Array<Long>?
        get() = getFieldLongValues(2, Fit.SUBFIELD_INDEX_MAIN_FIELD)

    val numBaroPres: Int
        /**
         * @return number of baro_pres
         */
        get() = getNumFieldValues(2, Fit.SUBFIELD_INDEX_MAIN_FIELD)

    /**
     * Get baro_pres field
     * Units: Pa
     * Comment: These are the raw ADC reading. The samples may span across seconds. A conversion will need to be done on this data once read.
     *
     * @param index of baro_pres
     * @return baro_pres
     */
    fun getBaroPres(index: Int): Long? {
        return getFieldLongValue(2, index, Fit.SUBFIELD_INDEX_MAIN_FIELD)
    }

    /**
     * Set baro_pres field
     * Units: Pa
     * Comment: These are the raw ADC reading. The samples may span across seconds. A conversion will need to be done on this data once read.
     *
     * @param index of baro_pres
     * @param baroPres The new baroPres value to be set
     */
    fun setBaroPres(index: Int, baroPres: Long?) {
        setFieldValue(2, index, baroPres, Fit.SUBFIELD_INDEX_MAIN_FIELD)
    }

    companion object {
        const val TimestampFieldNum: Int = 253

        const val TimestampMsFieldNum: Int = 0

        const val SampleTimeOffsetFieldNum: Int = 1

        const val BaroPresFieldNum: Int = 2


        // barometer_data
        val barometerDataMesg: Mesg = Mesg("barometer_data", MesgNum.BAROMETER_DATA)

        init {
            barometerDataMesg.addField(
                Field(
                    "timestamp",
                    TimestampFieldNum,
                    134,
                    1.0,
                    0.0,
                    "s",
                    false,
                    Profile.Type.DATE_TIME
                )
            )

            barometerDataMesg.addField(
                Field(
                    "timestamp_ms",
                    TimestampMsFieldNum,
                    132,
                    1.0,
                    0.0,
                    "ms",
                    false,
                    Profile.Type.UINT16
                )
            )

            barometerDataMesg.addField(
                Field(
                    "sample_time_offset",
                    SampleTimeOffsetFieldNum,
                    132,
                    1.0,
                    0.0,
                    "ms",
                    false,
                    Profile.Type.UINT16
                )
            )

            barometerDataMesg.addField(
                Field(
                    "baro_pres",
                    BaroPresFieldNum,
                    134,
                    1.0,
                    0.0,
                    "Pa",
                    false,
                    Profile.Type.UINT32
                )
            )
        }
    }
}
