/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


class CourseMesg : Mesg {
    constructor() : super(Factory.createMesg(MesgNum.COURSE))

    constructor(mesg: Mesg?) : super(mesg)


    var sport: Sport?
        /**
         * Get sport field
         * 
         * @return sport
         */
        get() {
            val value = getFieldShortValue(4, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
            if (value == null) {
                return null
            }
            return Sport.Companion.getByValue(value)
        }
        /**
         * Set sport field
         * 
         * @param sport The new sport value to be set
         */
        set(sport) {
            setFieldValue(4, 0, sport!!.value, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    /**
     * Get name field
     * 
     * @return name
     */
    override fun getName(): String? {
        return getFieldStringValue(5, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
    }

    /**
     * Set name field
     * 
     * @param name The new name value to be set
     */
    fun setName(name: String?) {
        setFieldValue(5, 0, name, Fit.SUBFIELD_INDEX_MAIN_FIELD)
    }

    var capabilities: Long?
        /**
         * Get capabilities field
         * 
         * @return capabilities
         */
        get() = getFieldLongValue(6, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set capabilities field
         * 
         * @param capabilities The new capabilities value to be set
         */
        set(capabilities) {
            setFieldValue(6, 0, capabilities, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var subSport: SubSport?
        /**
         * Get sub_sport field
         * 
         * @return sub_sport
         */
        get() {
            val value = getFieldShortValue(7, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
            if (value == null) {
                return null
            }
            return SubSport.Companion.getByValue(value)
        }
        /**
         * Set sub_sport field
         * 
         * @param subSport The new subSport value to be set
         */
        set(subSport) {
            setFieldValue(7, 0, subSport!!.value, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    companion object {
        const val SportFieldNum: Int = 4

        const val NameFieldNum: Int = 5

        const val CapabilitiesFieldNum: Int = 6

        const val SubSportFieldNum: Int = 7


        val courseMesg: Mesg

        init {
            // course
            courseMesg = Mesg("course", MesgNum.COURSE)
            courseMesg.addField(
                Field(
                    "sport",
                    SportFieldNum,
                    0,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.SPORT
                )
            )

            courseMesg.addField(
                Field(
                    "name",
                    NameFieldNum,
                    7,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.STRING
                )
            )

            courseMesg.addField(
                Field(
                    "capabilities",
                    CapabilitiesFieldNum,
                    140,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.COURSE_CAPABILITIES
                )
            )

            courseMesg.addField(
                Field(
                    "sub_sport",
                    SubSportFieldNum,
                    0,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.SUB_SPORT
                )
            )
        }
    }
}
