/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

object CurlExerciseName {
    const val ALTERNATING_DUMBBELL_BICEPS_CURL: Int = 0
    const val ALTERNATING_DUMBBELL_BICEPS_CURL_ON_SWISS_BALL: Int = 1
    const val ALTERNATING_INCLINE_DUMBBELL_BICEPS_CURL: Int = 2
    const val BARBELL_BICEPS_CURL: Int = 3
    const val BARBELL_REVERSE_WRIST_CURL: Int = 4
    const val BARBELL_WRIST_CURL: Int = 5
    const val BEHIND_THE_BACK_BARBELL_REVERSE_WRIST_CURL: Int = 6
    const val BEHIND_THE_BACK_ONE_ARM_CABLE_CURL: Int = 7
    const val CABLE_BICEPS_CURL: Int = 8
    const val CABLE_HAMMER_CURL: Int = 9
    const val CHEATING_BARBELL_BICEPS_CURL: Int = 10
    const val CLOSE_GRIP_EZ_BAR_BICEPS_CURL: Int = 11
    const val CROSS_BODY_DUMBBELL_HAMMER_CURL: Int = 12
    const val DEAD_HANG_BICEPS_CURL: Int = 13
    const val DECLINE_HAMMER_CURL: Int = 14
    const val DUMBBELL_BICEPS_CURL_WITH_STATIC_HOLD: Int = 15
    const val DUMBBELL_HAMMER_CURL: Int = 16
    const val DUMBBELL_REVERSE_WRIST_CURL: Int = 17
    const val DUMBBELL_WRIST_CURL: Int = 18
    const val EZ_BAR_PREACHER_CURL: Int = 19
    const val FORWARD_BEND_BICEPS_CURL: Int = 20
    const val HAMMER_CURL_TO_PRESS: Int = 21
    const val INCLINE_DUMBBELL_BICEPS_CURL: Int = 22
    const val INCLINE_OFFSET_THUMB_DUMBBELL_CURL: Int = 23
    const val KETTLEBELL_BICEPS_CURL: Int = 24
    const val LYING_CONCENTRATION_CABLE_CURL: Int = 25
    const val ONE_ARM_PREACHER_CURL: Int = 26
    const val PLATE_PINCH_CURL: Int = 27
    const val PREACHER_CURL_WITH_CABLE: Int = 28
    const val REVERSE_EZ_BAR_CURL: Int = 29
    const val REVERSE_GRIP_WRIST_CURL: Int = 30
    const val REVERSE_GRIP_BARBELL_BICEPS_CURL: Int = 31
    const val SEATED_ALTERNATING_DUMBBELL_BICEPS_CURL: Int = 32
    const val SEATED_DUMBBELL_BICEPS_CURL: Int = 33
    const val SEATED_REVERSE_DUMBBELL_CURL: Int = 34
    const val SPLIT_STANCE_OFFSET_PINKY_DUMBBELL_CURL: Int = 35
    const val STANDING_ALTERNATING_DUMBBELL_CURLS: Int = 36
    const val STANDING_DUMBBELL_BICEPS_CURL: Int = 37
    const val STANDING_EZ_BAR_BICEPS_CURL: Int = 38
    const val STATIC_CURL: Int = 39
    const val SWISS_BALL_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION: Int = 40
    const val SWISS_BALL_EZ_BAR_PREACHER_CURL: Int = 41
    const val TWISTING_STANDING_DUMBBELL_BICEPS_CURL: Int = 42
    const val WIDE_GRIP_EZ_BAR_BICEPS_CURL: Int = 43
    const val ONE_ARM_CONCENTRATION_CURL: Int = 44
    const val STANDING_ZOTTMAN_BICEPS_CURL: Int = 45
    const val DUMBBELL_BICEPS_CURL: Int = 46
    const val DRAG_CURL_WHEELCHAIR: Int = 47
    const val DUMBBELL_BICEPS_CURL_WHEELCHAIR: Int = 48
    const val BOTTLE_CURL: Int = 49
    const val SEATED_BOTTLE_CURL: Int = 50
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: MutableMap<Int?, String?>

    init {
        stringMap = HashMap<Int?, String?>()
        stringMap.put(ALTERNATING_DUMBBELL_BICEPS_CURL, "ALTERNATING_DUMBBELL_BICEPS_CURL")
        stringMap.put(
            ALTERNATING_DUMBBELL_BICEPS_CURL_ON_SWISS_BALL,
            "ALTERNATING_DUMBBELL_BICEPS_CURL_ON_SWISS_BALL"
        )
        stringMap.put(
            ALTERNATING_INCLINE_DUMBBELL_BICEPS_CURL,
            "ALTERNATING_INCLINE_DUMBBELL_BICEPS_CURL"
        )
        stringMap.put(BARBELL_BICEPS_CURL, "BARBELL_BICEPS_CURL")
        stringMap.put(BARBELL_REVERSE_WRIST_CURL, "BARBELL_REVERSE_WRIST_CURL")
        stringMap.put(BARBELL_WRIST_CURL, "BARBELL_WRIST_CURL")
        stringMap.put(
            BEHIND_THE_BACK_BARBELL_REVERSE_WRIST_CURL,
            "BEHIND_THE_BACK_BARBELL_REVERSE_WRIST_CURL"
        )
        stringMap.put(BEHIND_THE_BACK_ONE_ARM_CABLE_CURL, "BEHIND_THE_BACK_ONE_ARM_CABLE_CURL")
        stringMap.put(CABLE_BICEPS_CURL, "CABLE_BICEPS_CURL")
        stringMap.put(CABLE_HAMMER_CURL, "CABLE_HAMMER_CURL")
        stringMap.put(CHEATING_BARBELL_BICEPS_CURL, "CHEATING_BARBELL_BICEPS_CURL")
        stringMap.put(CLOSE_GRIP_EZ_BAR_BICEPS_CURL, "CLOSE_GRIP_EZ_BAR_BICEPS_CURL")
        stringMap.put(CROSS_BODY_DUMBBELL_HAMMER_CURL, "CROSS_BODY_DUMBBELL_HAMMER_CURL")
        stringMap.put(DEAD_HANG_BICEPS_CURL, "DEAD_HANG_BICEPS_CURL")
        stringMap.put(DECLINE_HAMMER_CURL, "DECLINE_HAMMER_CURL")
        stringMap.put(
            DUMBBELL_BICEPS_CURL_WITH_STATIC_HOLD,
            "DUMBBELL_BICEPS_CURL_WITH_STATIC_HOLD"
        )
        stringMap.put(DUMBBELL_HAMMER_CURL, "DUMBBELL_HAMMER_CURL")
        stringMap.put(DUMBBELL_REVERSE_WRIST_CURL, "DUMBBELL_REVERSE_WRIST_CURL")
        stringMap.put(DUMBBELL_WRIST_CURL, "DUMBBELL_WRIST_CURL")
        stringMap.put(EZ_BAR_PREACHER_CURL, "EZ_BAR_PREACHER_CURL")
        stringMap.put(FORWARD_BEND_BICEPS_CURL, "FORWARD_BEND_BICEPS_CURL")
        stringMap.put(HAMMER_CURL_TO_PRESS, "HAMMER_CURL_TO_PRESS")
        stringMap.put(INCLINE_DUMBBELL_BICEPS_CURL, "INCLINE_DUMBBELL_BICEPS_CURL")
        stringMap.put(INCLINE_OFFSET_THUMB_DUMBBELL_CURL, "INCLINE_OFFSET_THUMB_DUMBBELL_CURL")
        stringMap.put(KETTLEBELL_BICEPS_CURL, "KETTLEBELL_BICEPS_CURL")
        stringMap.put(LYING_CONCENTRATION_CABLE_CURL, "LYING_CONCENTRATION_CABLE_CURL")
        stringMap.put(ONE_ARM_PREACHER_CURL, "ONE_ARM_PREACHER_CURL")
        stringMap.put(PLATE_PINCH_CURL, "PLATE_PINCH_CURL")
        stringMap.put(PREACHER_CURL_WITH_CABLE, "PREACHER_CURL_WITH_CABLE")
        stringMap.put(REVERSE_EZ_BAR_CURL, "REVERSE_EZ_BAR_CURL")
        stringMap.put(REVERSE_GRIP_WRIST_CURL, "REVERSE_GRIP_WRIST_CURL")
        stringMap.put(REVERSE_GRIP_BARBELL_BICEPS_CURL, "REVERSE_GRIP_BARBELL_BICEPS_CURL")
        stringMap.put(
            SEATED_ALTERNATING_DUMBBELL_BICEPS_CURL,
            "SEATED_ALTERNATING_DUMBBELL_BICEPS_CURL"
        )
        stringMap.put(SEATED_DUMBBELL_BICEPS_CURL, "SEATED_DUMBBELL_BICEPS_CURL")
        stringMap.put(SEATED_REVERSE_DUMBBELL_CURL, "SEATED_REVERSE_DUMBBELL_CURL")
        stringMap.put(
            SPLIT_STANCE_OFFSET_PINKY_DUMBBELL_CURL,
            "SPLIT_STANCE_OFFSET_PINKY_DUMBBELL_CURL"
        )
        stringMap.put(STANDING_ALTERNATING_DUMBBELL_CURLS, "STANDING_ALTERNATING_DUMBBELL_CURLS")
        stringMap.put(STANDING_DUMBBELL_BICEPS_CURL, "STANDING_DUMBBELL_BICEPS_CURL")
        stringMap.put(STANDING_EZ_BAR_BICEPS_CURL, "STANDING_EZ_BAR_BICEPS_CURL")
        stringMap.put(STATIC_CURL, "STATIC_CURL")
        stringMap.put(
            SWISS_BALL_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION,
            "SWISS_BALL_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION"
        )
        stringMap.put(SWISS_BALL_EZ_BAR_PREACHER_CURL, "SWISS_BALL_EZ_BAR_PREACHER_CURL")
        stringMap.put(
            TWISTING_STANDING_DUMBBELL_BICEPS_CURL,
            "TWISTING_STANDING_DUMBBELL_BICEPS_CURL"
        )
        stringMap.put(WIDE_GRIP_EZ_BAR_BICEPS_CURL, "WIDE_GRIP_EZ_BAR_BICEPS_CURL")
        stringMap.put(ONE_ARM_CONCENTRATION_CURL, "ONE_ARM_CONCENTRATION_CURL")
        stringMap.put(STANDING_ZOTTMAN_BICEPS_CURL, "STANDING_ZOTTMAN_BICEPS_CURL")
        stringMap.put(DUMBBELL_BICEPS_CURL, "DUMBBELL_BICEPS_CURL")
        stringMap.put(DRAG_CURL_WHEELCHAIR, "DRAG_CURL_WHEELCHAIR")
        stringMap.put(DUMBBELL_BICEPS_CURL_WHEELCHAIR, "DUMBBELL_BICEPS_CURL_WHEELCHAIR")
        stringMap.put(BOTTLE_CURL, "BOTTLE_CURL")
        stringMap.put(SEATED_BOTTLE_CURL, "SEATED_BOTTLE_CURL")
    }


    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum contsant
     */
    fun getStringFromValue(value: Int?): String? {
        if (stringMap.containsKey(value)) {
            return stringMap.get(value)
        }

        return ""
    }

    /**
     * Returns the enum constant with the specified name.
     * @param value The enum string value
     * @return The enum constant or INVALID if unknown
     */
    fun getValueFromString(value: String?): Int? {
        for (entry in stringMap.entries) {
            if (entry.value == value) {
                return entry.key
            }
        }

        return INVALID
    }
}
