/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

import java.io.IOException
import java.io.OutputStream

class DeveloperFieldDefinition : FieldDefinitionBase {
    private var fieldDescriptionMesg: FieldDescriptionMesg? = null
    private var developerDataIdMesg: DeveloperDataIdMesg? = null
    private var size = 0
    var type: Int = 0
        private set
    var num: Short = 0

    constructor() {
        fieldDescriptionMesg = null
        type = FitBaseType.UINT8.toInt()
    }

    constructor(mesg: FieldDescriptionMesg?, developerDataIdMesg: DeveloperDataIdMesg?) {
        setFieldDescription(mesg)
        this.developerDataIdMesg = developerDataIdMesg
    }

    constructor(field: DeveloperField) : this(field.getFieldDefinition()) {
        this.size = field.getSize()
    }

    constructor(other: DeveloperFieldDefinition) {
        setFieldDescription(other.fieldDescriptionMesg)
        this.developerDataIdMesg = other.developerDataIdMesg
        size = other.getSize()
    }

    val appVersion: Long
        get() {
            var `val`: Long? = null

            if (this.isDefined) {
                `val` = developerDataIdMesg!!.getApplicationVersion()
            }

            if (null == `val`) {
                return Fit.UINT32_INVALID
            }

            return `val`
        }

    val appId: Array<Byte?>?
        get() {
            if (this.isDefined) {
                return developerDataIdMesg!!.getApplicationId()
            }

            return null
        }

    val developerDataIndex: Short
        get() {
            var `val`: Short? = null
            if (this.isDefined) {
                `val` = fieldDescriptionMesg!!.getDeveloperDataIndex()
            }

            if (null == `val`) {
                return Fit.UINT8_INVALID
            }

            return `val`
        }

    val isDefined: Boolean
        get() = (fieldDescriptionMesg != null) && (developerDataIdMesg != null)

    val fieldName: String?
        get() {
            if (this.isDefined) {
                return fieldDescriptionMesg!!.getFieldName(0)
            }

            return null
        }

    val scale: Short
        get() {
            if (this.isDefined &&
                (fieldDescriptionMesg!!.getScale() != null) &&
                (fieldDescriptionMesg!!.getScale() != Fit.UINT8_INVALID)
            ) {
                return fieldDescriptionMesg!!.getScale()
            }

            return Fit.FIELD_DEFAULT_SCALE.toShort()
        }

    val offset: Short
        get() {
            if (this.isDefined &&
                (fieldDescriptionMesg!!.getOffset() != null) &&
                (fieldDescriptionMesg!!.getOffset() != Fit.SINT8_INVALID)
            ) {
                return fieldDescriptionMesg!!.getOffset().toShort()
            }

            return Fit.FIELD_DEFAULT_OFFSET.toShort()
        }

    val units: String?
        get() {
            if (this.isDefined) {
                return fieldDescriptionMesg!!.getUnits(0)
            }

            return null
        }

    val defaultField: DeveloperField
        get() = DeveloperField(this)

    fun write(out: OutputStream) {
        try {
            out.write(fieldDescriptionMesg!!.getFieldDefinitionNumber().toInt())
            out.write(size)
            out.write(fieldDescriptionMesg!!.getDeveloperDataIndex().toInt())
        } catch (e: IOException) {
            throw FitRuntimeException(e)
        }
    }

    override fun getSize(): Int {
        return size
    }

    override fun setSize(size: Int) {
        this.size = size
    }

    val nativeOverride: Short
        /**
         * Retrieve the Overridden Native Field Number
         * 
         * @return Overridden field number if field overrides a value, [Fit.UINT8_INVALID] otherwise.
         */
        get() {
            if (this.isDefined) {
                val nativeNum = fieldDescriptionMesg!!.getNativeFieldNum()
                if (null != nativeNum) {
                    return nativeNum
                }
            }

            return Fit.UINT8_INVALID
        }

    fun setFieldDescription(description: FieldDescriptionMesg?) {
        this.fieldDescriptionMesg = description
        this.num = fieldDescriptionMesg!!.getFieldDefinitionNumber()
        this.type = fieldDescriptionMesg!!.getFitBaseTypeId().toInt()
    }

    fun setDeveloperDataIdMesg(developerDataIdMesg: DeveloperDataIdMesg?) {
        this.developerDataIdMesg = developerDataIdMesg
    }
}
