/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

import java.io.IOException
import java.io.OutputStream

class DeveloperFieldDefinition : FieldDefinitionBase {
    private var fieldDescriptionMesg: FieldDescriptionMesg? = null
    private var developerDataIdMesg: DeveloperDataIdMesg? = null
    override var size = 0
    var type: Int = 0
        private set
    var num: Short = 0

    constructor() {
        fieldDescriptionMesg = null
        type = FitBaseType.UINT8.toInt()
    }

    constructor(mesg: FieldDescriptionMesg, developerDataIdMesg: DeveloperDataIdMesg) {
        setFieldDescription(mesg)
        this.developerDataIdMesg = developerDataIdMesg
    }

    constructor(field: DeveloperField) : this(field.fieldDefinition) {
        this.size = field.size
    }

    constructor(other: DeveloperFieldDefinition) {
        other.fieldDescriptionMesg?.let {
            setFieldDescription(it)
            this.developerDataIdMesg = other.developerDataIdMesg
            size = other.size
        }
    }

    val appVersion: Long
        get() {
            var `val`: Long? = null

            if (this.isDefined) {
                `val` = developerDataIdMesg!!.applicationVersion
            }

            if (null == `val`) {
                return Fit.UINT32_INVALID
            }

            return `val`
        }

    val appId: Array<Byte>?
        get() {
            if (this.isDefined) {
                return developerDataIdMesg!!.applicationId
            }

            return null
        }

    val developerDataIndex: Short
        get() {
            var `val`: Short? = null
            if (this.isDefined) {
                `val` = fieldDescriptionMesg!!.developerDataIndex
            }

            if (null == `val`) {
                return Fit.UINT8_INVALID
            }

            return `val`
        }

    val isDefined: Boolean
        get() = (fieldDescriptionMesg != null) && (developerDataIdMesg != null)

    val fieldName: String?
        get() {
            if (this.isDefined) {
                return fieldDescriptionMesg!!.getFieldName(0)
            }

            return null
        }

    val scale: Short
        get() {
            val fieldScale = fieldDescriptionMesg!!.scale
            if (this.isDefined && (fieldScale != null) && (fieldScale != Fit.UINT8_INVALID)) {
                return fieldScale
            }

            return Fit.FIELD_DEFAULT_SCALE.toShort()
        }

    val offset: Short
        get() {
            val fieldOffset = fieldDescriptionMesg!!.offset
            if (this.isDefined &&
                (fieldOffset != null) &&
                (fieldOffset != Fit.SINT8_INVALID)
            ) {
                return fieldOffset.toShort()
            }

            return Fit.FIELD_DEFAULT_OFFSET.toShort()
        }

    val units: String?
        get() {
            if (this.isDefined) {
                return fieldDescriptionMesg!!.getUnits(0)
            }

            return null
        }

    val defaultField: DeveloperField
        get() = DeveloperField(this)

    fun write(out: OutputStream) {
        try {
            out.write(fieldDescriptionMesg!!.fieldDefinitionNumber!!.toInt())
            out.write(size)
            out.write(fieldDescriptionMesg!!.developerDataIndex!!.toInt())
        } catch (e: IOException) {
            throw FitRuntimeException(e)
        }
    }

    val nativeOverride: Short
        /**
         * Retrieve the Overridden Native Field Number
         * 
         * @return Overridden field number if field overrides a value, [Fit.UINT8_INVALID] otherwise.
         */
        get() {
            if (this.isDefined) {
                val nativeNum = fieldDescriptionMesg!!.nativeFieldNum
                if (null != nativeNum) {
                    return nativeNum
                }
            }

            return Fit.UINT8_INVALID
        }

    fun setFieldDescription(description: FieldDescriptionMesg) {
        this.fieldDescriptionMesg = description
        fieldDescriptionMesg!!.fieldDefinitionNumber?.let { this.num = it }
        fieldDescriptionMesg!!.fitBaseTypeId?.toInt()?.let { this.type = it }
    }

    fun setDeveloperDataIdMesg(developerDataIdMesg: DeveloperDataIdMesg?) {
        this.developerDataIdMesg = developerDataIdMesg
    }

    override fun toString() = "DeveloperFieldDefinition(" +
            "num=$num, " +
            "size=$size, " +
            "type=$type, " +
            "appVersion=$appVersion, " +
            "appId=${appId?.toByteArray()?.toHexString()}, " +
            "developerDataIndex=$developerDataIndex, " +
            "isDefined=$isDefined, " +
            "fieldName=$fieldName, " +
            "scale=$scale, " +
            "offset=$offset, " +
            "units=$units" +
            ")"

}
