/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


enum class DiveAlert(var value: Short) {
    NDL_REACHED(0.toShort()),
    GAS_SWITCH_PROMPTED(1.toShort()),
    NEAR_SURFACE(2.toShort()),
    APPROACHING_NDL(3.toShort()),
    PO2_WARN(4.toShort()),
    PO2_CRIT_HIGH(5.toShort()),
    PO2_CRIT_LOW(6.toShort()),
    TIME_ALERT(7.toShort()),
    DEPTH_ALERT(8.toShort()),
    DECO_CEILING_BROKEN(9.toShort()),
    DECO_COMPLETE(10.toShort()),
    SAFETY_STOP_BROKEN(11.toShort()),
    SAFETY_STOP_COMPLETE(12.toShort()),
    CNS_WARNING(13.toShort()),
    CNS_CRITICAL(14.toShort()),
    OTU_WARNING(15.toShort()),
    OTU_CRITICAL(16.toShort()),
    ASCENT_CRITICAL(17.toShort()),
    ALERT_DISMISSED_BY_KEY(18.toShort()),
    ALERT_DISMISSED_BY_TIMEOUT(19.toShort()),
    BATTERY_LOW(20.toShort()),
    BATTERY_CRITICAL(21.toShort()),
    SAFETY_STOP_STARTED(22.toShort()),
    APPROACHING_FIRST_DECO_STOP(23.toShort()),
    SETPOINT_SWITCH_AUTO_LOW(24.toShort()),
    SETPOINT_SWITCH_AUTO_HIGH(25.toShort()),
    SETPOINT_SWITCH_MANUAL_LOW(26.toShort()),
    SETPOINT_SWITCH_MANUAL_HIGH(27.toShort()),
    AUTO_SETPOINT_SWITCH_IGNORED(28.toShort()),
    SWITCHED_TO_OPEN_CIRCUIT(29.toShort()),
    SWITCHED_TO_CLOSED_CIRCUIT(30.toShort()),
    TANK_BATTERY_LOW(32.toShort()),
    PO2_CCR_DIL_LOW(33.toShort()),
    DECO_STOP_CLEARED(34.toShort()),
    APNEA_NEUTRAL_BUOYANCY(35.toShort()),
    APNEA_TARGET_DEPTH(36.toShort()),
    APNEA_SURFACE(37.toShort()),
    APNEA_HIGH_SPEED(38.toShort()),
    APNEA_LOW_SPEED(39.toShort()),
    INVALID(255.toShort());


    companion object {
        fun getByValue(value: Short): DiveAlert {
            for (type in entries) {
                if (value == type.value) return type
            }

            return DiveAlert.INVALID
        }

        /**
         * Retrieves the String Representation of the Value
         * @param value The enum constant
         * @return The name of this enum constant
         */
        fun getStringFromValue(value: DiveAlert): String {
            return value.name
        }
    }
}
