/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


enum class ExdDisplayType(var value: Short) {
    NUMERICAL(0.toShort()),
    SIMPLE(1.toShort()),
    GRAPH(2.toShort()),
    BAR(3.toShort()),
    CIRCLE_GRAPH(4.toShort()),
    VIRTUAL_PARTNER(5.toShort()),
    BALANCE(6.toShort()),
    STRING_LIST(7.toShort()),
    STRING(8.toShort()),
    SIMPLE_DYNAMIC_ICON(9.toShort()),
    GAUGE(10.toShort()),
    INVALID(255.toShort());


    companion object {
        fun getByValue(value: Short): ExdDisplayType {
            for (type in entries) {
                if (value == type.value) return type
            }

            return INVALID
        }

        /**
         * Retrieves the String Representation of the Value
         * @param value The enum constant
         * @return The name of this enum constant
         */
        fun getStringFromValue(value: ExdDisplayType): String {
            return value.name
        }
    }
}
