/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


class ExdDataConceptConfigurationMesg : Mesg {
    constructor() : super(Factory.createMesg(MesgNum.EXD_DATA_CONCEPT_CONFIGURATION))

    constructor(mesg: Mesg?) : super(mesg)


    var screenIndex: Short?
        /**
         * Get screen_index field
         * 
         * @return screen_index
         */
        get() = getFieldShortValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set screen_index field
         * 
         * @param screenIndex The new screenIndex value to be set
         */
        set(screenIndex) {
            setFieldValue(0, 0, screenIndex, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var conceptField: Byte?
        /**
         * Get concept_field field
         * 
         * @return concept_field
         */
        get() = getFieldByteValue(1, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set concept_field field
         * 
         * @param conceptField The new conceptField value to be set
         */
        set(conceptField) {
            setFieldValue(1, 0, conceptField, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var fieldId: Short?
        /**
         * Get field_id field
         * 
         * @return field_id
         */
        get() = getFieldShortValue(2, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set field_id field
         * 
         * @param fieldId The new fieldId value to be set
         */
        set(fieldId) {
            setFieldValue(2, 0, fieldId, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var conceptIndex: Short?
        /**
         * Get concept_index field
         * 
         * @return concept_index
         */
        get() = getFieldShortValue(3, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set concept_index field
         * 
         * @param conceptIndex The new conceptIndex value to be set
         */
        set(conceptIndex) {
            setFieldValue(3, 0, conceptIndex, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var dataPage: Short?
        /**
         * Get data_page field
         * 
         * @return data_page
         */
        get() = getFieldShortValue(4, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set data_page field
         * 
         * @param dataPage The new dataPage value to be set
         */
        set(dataPage) {
            setFieldValue(4, 0, dataPage, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var conceptKey: Short?
        /**
         * Get concept_key field
         * 
         * @return concept_key
         */
        get() = getFieldShortValue(5, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set concept_key field
         * 
         * @param conceptKey The new conceptKey value to be set
         */
        set(conceptKey) {
            setFieldValue(5, 0, conceptKey, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var scaling: Short?
        /**
         * Get scaling field
         * 
         * @return scaling
         */
        get() = getFieldShortValue(6, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set scaling field
         * 
         * @param scaling The new scaling value to be set
         */
        set(scaling) {
            setFieldValue(6, 0, scaling, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var dataUnits: ExdDataUnits?
        /**
         * Get data_units field
         * 
         * @return data_units
         */
        get() {
            val value = getFieldShortValue(8, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
            if (value == null) {
                return null
            }
            return ExdDataUnits.Companion.getByValue(value)
        }
        /**
         * Set data_units field
         * 
         * @param dataUnits The new dataUnits value to be set
         */
        set(dataUnits) {
            setFieldValue(8, 0, dataUnits!!.value, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var qualifier: ExdQualifiers?
        /**
         * Get qualifier field
         * 
         * @return qualifier
         */
        get() {
            val value = getFieldShortValue(9, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
            if (value == null) {
                return null
            }
            return ExdQualifiers.Companion.getByValue(value)
        }
        /**
         * Set qualifier field
         * 
         * @param qualifier The new qualifier value to be set
         */
        set(qualifier) {
            setFieldValue(9, 0, qualifier!!.value, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var descriptor: ExdDescriptors?
        /**
         * Get descriptor field
         * 
         * @return descriptor
         */
        get() {
            val value = getFieldShortValue(10, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
            if (value == null) {
                return null
            }
            return ExdDescriptors.Companion.getByValue(value)
        }
        /**
         * Set descriptor field
         * 
         * @param descriptor The new descriptor value to be set
         */
        set(descriptor) {
            setFieldValue(10, 0, descriptor!!.value, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var isSigned: Bool?
        /**
         * Get is_signed field
         * 
         * @return is_signed
         */
        get() {
            val value = getFieldShortValue(11, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
            if (value == null) {
                return null
            }
            return Bool.Companion.getByValue(value)
        }
        /**
         * Set is_signed field
         * 
         * @param isSigned The new isSigned value to be set
         */
        set(isSigned) {
            setFieldValue(11, 0, isSigned!!.value, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    companion object {
        const val ScreenIndexFieldNum: Int = 0

        const val ConceptFieldFieldNum: Int = 1

        const val FieldIdFieldNum: Int = 2

        const val ConceptIndexFieldNum: Int = 3

        const val DataPageFieldNum: Int = 4

        const val ConceptKeyFieldNum: Int = 5

        const val ScalingFieldNum: Int = 6

        const val DataUnitsFieldNum: Int = 8

        const val QualifierFieldNum: Int = 9

        const val DescriptorFieldNum: Int = 10

        const val IsSignedFieldNum: Int = 11


        val exdDataConceptConfigurationMesg: Mesg

        init {
            var field_index = 0
            // exd_data_concept_configuration
            exdDataConceptConfigurationMesg =
                Mesg("exd_data_concept_configuration", MesgNum.EXD_DATA_CONCEPT_CONFIGURATION)
            exdDataConceptConfigurationMesg.addField(
                Field(
                    "screen_index",
                    ScreenIndexFieldNum,
                    2,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT8
                )
            )
            field_index++
            exdDataConceptConfigurationMesg.addField(
                Field(
                    "concept_field",
                    ConceptFieldFieldNum,
                    13,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.BYTE
                )
            )
            exdDataConceptConfigurationMesg.fields.get(field_index).components.add(
                FieldComponent(
                    2,
                    false,
                    4,
                    1.0,
                    0.0
                )
            ) // field_id
            exdDataConceptConfigurationMesg.fields.get(field_index).components.add(
                FieldComponent(
                    3,
                    false,
                    4,
                    1.0,
                    0.0
                )
            ) // concept_index
            field_index++
            exdDataConceptConfigurationMesg.addField(
                Field(
                    "field_id",
                    FieldIdFieldNum,
                    2,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT8
                )
            )
            field_index++
            exdDataConceptConfigurationMesg.addField(
                Field(
                    "concept_index",
                    ConceptIndexFieldNum,
                    2,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT8
                )
            )
            field_index++
            exdDataConceptConfigurationMesg.addField(
                Field(
                    "data_page",
                    DataPageFieldNum,
                    2,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT8
                )
            )
            field_index++
            exdDataConceptConfigurationMesg.addField(
                Field(
                    "concept_key",
                    ConceptKeyFieldNum,
                    2,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT8
                )
            )
            field_index++
            exdDataConceptConfigurationMesg.addField(
                Field(
                    "scaling",
                    ScalingFieldNum,
                    2,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT8
                )
            )
            field_index++
            exdDataConceptConfigurationMesg.addField(
                Field(
                    "data_units",
                    DataUnitsFieldNum,
                    0,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.EXD_DATA_UNITS
                )
            )
            field_index++
            exdDataConceptConfigurationMesg.addField(
                Field(
                    "qualifier",
                    QualifierFieldNum,
                    0,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.EXD_QUALIFIERS
                )
            )
            field_index++
            exdDataConceptConfigurationMesg.addField(
                Field(
                    "descriptor",
                    DescriptorFieldNum,
                    0,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.EXD_DESCRIPTORS
                )
            )
            field_index++
            exdDataConceptConfigurationMesg.addField(
                Field(
                    "is_signed",
                    IsSignedFieldNum,
                    0,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.BOOL
                )
            )
            field_index++
        }
    }
}
