/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

object Factory {
    fun createMesg(mesg: Mesg): Mesg {
        when (mesg.num) {
            MesgNum.FILE_ID -> return FileIdMesg(mesg)
            MesgNum.FILE_CREATOR -> return FileCreatorMesg(mesg)
            MesgNum.TIMESTAMP_CORRELATION -> return TimestampCorrelationMesg(mesg)
            MesgNum.SOFTWARE -> return SoftwareMesg(mesg)
            MesgNum.SLAVE_DEVICE -> return SlaveDeviceMesg(mesg)
            MesgNum.CAPABILITIES -> return CapabilitiesMesg(mesg)
            MesgNum.FILE_CAPABILITIES -> return FileCapabilitiesMesg(mesg)
            MesgNum.MESG_CAPABILITIES -> return MesgCapabilitiesMesg(mesg)
            MesgNum.FIELD_CAPABILITIES -> return FieldCapabilitiesMesg(mesg)
            MesgNum.DEVICE_SETTINGS -> return DeviceSettingsMesg(mesg)
            MesgNum.USER_PROFILE -> return UserProfileMesg(mesg)
            MesgNum.HRM_PROFILE -> return HrmProfileMesg(mesg)
            MesgNum.SDM_PROFILE -> return SdmProfileMesg(mesg)
            MesgNum.BIKE_PROFILE -> return BikeProfileMesg(mesg)
            MesgNum.CONNECTIVITY -> return ConnectivityMesg(mesg)
            MesgNum.WATCHFACE_SETTINGS -> return WatchfaceSettingsMesg(mesg)
            MesgNum.OHR_SETTINGS -> return OhrSettingsMesg(mesg)
            MesgNum.TIME_IN_ZONE -> return TimeInZoneMesg(mesg)
            MesgNum.ZONES_TARGET -> return ZonesTargetMesg(mesg)
            MesgNum.SPORT -> return SportMesg(mesg)
            MesgNum.HR_ZONE -> return HrZoneMesg(mesg)
            MesgNum.SPEED_ZONE -> return SpeedZoneMesg(mesg)
            MesgNum.CADENCE_ZONE -> return CadenceZoneMesg(mesg)
            MesgNum.POWER_ZONE -> return PowerZoneMesg(mesg)
            MesgNum.MET_ZONE -> return MetZoneMesg(mesg)
            MesgNum.TRAINING_SETTINGS -> return TrainingSettingsMesg(mesg)
            MesgNum.DIVE_SETTINGS -> return DiveSettingsMesg(mesg)
            MesgNum.DIVE_ALARM -> return DiveAlarmMesg(mesg)
            MesgNum.DIVE_APNEA_ALARM -> return DiveApneaAlarmMesg(mesg)
            MesgNum.DIVE_GAS -> return DiveGasMesg(mesg)
            MesgNum.GOAL -> return GoalMesg(mesg)
            MesgNum.ACTIVITY -> return ActivityMesg(mesg)
            MesgNum.SESSION -> return SessionMesg(mesg)
            MesgNum.LAP -> return LapMesg(mesg)
            MesgNum.LENGTH -> return LengthMesg(mesg)
            MesgNum.RECORD -> return RecordMesg(mesg)
            MesgNum.EVENT -> return EventMesg(mesg)
            MesgNum.DEVICE_INFO -> return DeviceInfoMesg(mesg)
            MesgNum.DEVICE_AUX_BATTERY_INFO -> return DeviceAuxBatteryInfoMesg(mesg)
            MesgNum.TRAINING_FILE -> return TrainingFileMesg(mesg)
            MesgNum.WEATHER_CONDITIONS -> return WeatherConditionsMesg(mesg)
            MesgNum.WEATHER_ALERT -> return WeatherAlertMesg(mesg)
            MesgNum.GPS_METADATA -> return GpsMetadataMesg(mesg)
            MesgNum.CAMERA_EVENT -> return CameraEventMesg(mesg)
            MesgNum.GYROSCOPE_DATA -> return GyroscopeDataMesg(mesg)
            MesgNum.ACCELEROMETER_DATA -> return AccelerometerDataMesg(mesg)
            MesgNum.MAGNETOMETER_DATA -> return MagnetometerDataMesg(mesg)
            MesgNum.BAROMETER_DATA -> return BarometerDataMesg(mesg)
            MesgNum.THREE_D_SENSOR_CALIBRATION -> return ThreeDSensorCalibrationMesg(mesg)
            MesgNum.ONE_D_SENSOR_CALIBRATION -> return OneDSensorCalibrationMesg(mesg)
            MesgNum.VIDEO_FRAME -> return VideoFrameMesg(mesg)
            MesgNum.OBDII_DATA -> return ObdiiDataMesg(mesg)
            MesgNum.NMEA_SENTENCE -> return NmeaSentenceMesg(mesg)
            MesgNum.AVIATION_ATTITUDE -> return AviationAttitudeMesg(mesg)
            MesgNum.VIDEO -> return VideoMesg(mesg)
            MesgNum.VIDEO_TITLE -> return VideoTitleMesg(mesg)
            MesgNum.VIDEO_DESCRIPTION -> return VideoDescriptionMesg(mesg)
            MesgNum.VIDEO_CLIP -> return VideoClipMesg(mesg)
            MesgNum.SET -> return SetMesg(mesg)
            MesgNum.JUMP -> return JumpMesg(mesg)
            MesgNum.SPLIT -> return SplitMesg(mesg)
            MesgNum.SPLIT_SUMMARY -> return SplitSummaryMesg(mesg)
            MesgNum.CLIMB_PRO -> return ClimbProMesg(mesg)
            MesgNum.FIELD_DESCRIPTION -> return FieldDescriptionMesg(mesg)
            MesgNum.DEVELOPER_DATA_ID -> return DeveloperDataIdMesg(mesg)
            MesgNum.COURSE -> return CourseMesg(mesg)
            MesgNum.COURSE_POINT -> return CoursePointMesg(mesg)
            MesgNum.SEGMENT_ID -> return SegmentIdMesg(mesg)
            MesgNum.SEGMENT_LEADERBOARD_ENTRY -> return SegmentLeaderboardEntryMesg(mesg)
            MesgNum.SEGMENT_POINT -> return SegmentPointMesg(mesg)
            MesgNum.SEGMENT_LAP -> return SegmentLapMesg(mesg)
            MesgNum.SEGMENT_FILE -> return SegmentFileMesg(mesg)
            MesgNum.WORKOUT -> return WorkoutMesg(mesg)
            MesgNum.WORKOUT_SESSION -> return WorkoutSessionMesg(mesg)
            MesgNum.WORKOUT_STEP -> return WorkoutStepMesg(mesg)
            MesgNum.EXERCISE_TITLE -> return ExerciseTitleMesg(mesg)
            MesgNum.SCHEDULE -> return ScheduleMesg(mesg)
            MesgNum.TOTALS -> return TotalsMesg(mesg)
            MesgNum.WEIGHT_SCALE -> return WeightScaleMesg(mesg)
            MesgNum.BLOOD_PRESSURE -> return BloodPressureMesg(mesg)
            MesgNum.MONITORING_INFO -> return MonitoringInfoMesg(mesg)
            MesgNum.MONITORING -> return MonitoringMesg(mesg)
            MesgNum.MONITORING_HR_DATA -> return MonitoringHrDataMesg(mesg)
            MesgNum.SPO2_DATA -> return Spo2DataMesg(mesg)
            MesgNum.HR -> return HrMesg(mesg)
            MesgNum.STRESS_LEVEL -> return StressLevelMesg(mesg)
            MesgNum.MAX_MET_DATA -> return MaxMetDataMesg(mesg)
            MesgNum.HSA_BODY_BATTERY_DATA -> return HsaBodyBatteryDataMesg(mesg)
            MesgNum.HSA_EVENT -> return HsaEventMesg(mesg)
            MesgNum.HSA_ACCELEROMETER_DATA -> return HsaAccelerometerDataMesg(mesg)
            MesgNum.HSA_GYROSCOPE_DATA -> return HsaGyroscopeDataMesg(mesg)
            MesgNum.HSA_STEP_DATA -> return HsaStepDataMesg(mesg)
            MesgNum.HSA_SPO2_DATA -> return HsaSpo2DataMesg(mesg)
            MesgNum.HSA_STRESS_DATA -> return HsaStressDataMesg(mesg)
            MesgNum.HSA_RESPIRATION_DATA -> return HsaRespirationDataMesg(mesg)
            MesgNum.HSA_HEART_RATE_DATA -> return HsaHeartRateDataMesg(mesg)
            MesgNum.HSA_CONFIGURATION_DATA -> return HsaConfigurationDataMesg(mesg)
            MesgNum.HSA_WRIST_TEMPERATURE_DATA -> return HsaWristTemperatureDataMesg(mesg)
            MesgNum.MEMO_GLOB -> return MemoGlobMesg(mesg)
            MesgNum.SLEEP_LEVEL -> return SleepLevelMesg(mesg)
            MesgNum.ANT_CHANNEL_ID -> return AntChannelIdMesg(mesg)
            MesgNum.ANT_RX -> return AntRxMesg(mesg)
            MesgNum.ANT_TX -> return AntTxMesg(mesg)
            MesgNum.EXD_SCREEN_CONFIGURATION -> return ExdScreenConfigurationMesg(mesg)
            MesgNum.EXD_DATA_FIELD_CONFIGURATION -> return ExdDataFieldConfigurationMesg(mesg)
            MesgNum.EXD_DATA_CONCEPT_CONFIGURATION -> return ExdDataConceptConfigurationMesg(mesg)
            MesgNum.DIVE_SUMMARY -> return DiveSummaryMesg(mesg)
            MesgNum.AAD_ACCEL_FEATURES -> return AadAccelFeaturesMesg(mesg)
            MesgNum.HRV -> return HrvMesg(mesg)
            MesgNum.BEAT_INTERVALS -> return BeatIntervalsMesg(mesg)
            MesgNum.HRV_STATUS_SUMMARY -> return HrvStatusSummaryMesg(mesg)
            MesgNum.HRV_VALUE -> return HrvValueMesg(mesg)
            MesgNum.RAW_BBI -> return RawBbiMesg(mesg)
            MesgNum.RESPIRATION_RATE -> return RespirationRateMesg(mesg)
            MesgNum.CHRONO_SHOT_SESSION -> return ChronoShotSessionMesg(mesg)
            MesgNum.CHRONO_SHOT_DATA -> return ChronoShotDataMesg(mesg)
            MesgNum.TANK_UPDATE -> return TankUpdateMesg(mesg)
            MesgNum.TANK_SUMMARY -> return TankSummaryMesg(mesg)
            MesgNum.SLEEP_ASSESSMENT -> return SleepAssessmentMesg(mesg)
            MesgNum.SLEEP_DISRUPTION_SEVERITY_PERIOD -> return SleepDisruptionSeverityPeriodMesg(
                mesg
            )

            MesgNum.SLEEP_DISRUPTION_OVERNIGHT_SEVERITY -> return SleepDisruptionOvernightSeverityMesg(
                mesg
            )

            MesgNum.NAP_EVENT -> return NapEventMesg(mesg)
            MesgNum.SKIN_TEMP_OVERNIGHT -> return SkinTempOvernightMesg(mesg)
            MesgNum.PAD -> return PadMesg(mesg)
            else -> {}
        }
        return Mesg("unknown", MesgNum.INVALID)
    }

    @JvmStatic
    fun createMesg(mesgNum: Int): Mesg {
        for (i in mesgs.indices) {
            if (mesgs[i].num == mesgNum) {
                return Mesg(mesgs[i])
            }
        }
        return Mesg("unknown", mesgNum)
    }

    @JvmStatic
    fun createMesg(mesgName: String?): Mesg {
        for (i in mesgs.indices) {
            if (mesgs[i].name == mesgName) {
                return Mesg(mesgs[i])
            }
        }
        return Mesg(mesgName, MesgNum.INVALID)
    }

    @JvmStatic
    fun createField(mesgName: String?, fieldName: String?): Field {
        for (i in mesgs.indices) {
            if (mesgs[i].name == mesgName) {
                return Field(mesgs[i].getField(fieldName, false))
            }
        }
        return Field(fieldName, Fit.FIELD_NUM_INVALID, 0, 1.0, 0.0, "", false, Profile.Type.ENUM)
    }

    fun createField(mesgName: String?, fieldNum: Int): Field {
        for (i in mesgs.indices) {
            if (mesgs[i].name == mesgName) {
                return Field(mesgs[i].getField(fieldNum))
            }
        }
        return Field("unknown", fieldNum, 0, 1.0, 0.0, "", false, Profile.Type.ENUM)
    }

    fun createField(mesgNum: Int, fieldNum: Int): Field {
        for (i in mesgs.indices) {
            if (mesgs[i].num == mesgNum) {
                return Field(mesgs[i].getField(fieldNum))
            }
        }
        return Field("unknown", fieldNum, 0, 1.0, 0.0, "", false, Profile.Type.ENUM)
    }

    fun createField(mesgNum: Int, fieldName: String?): Field {
        for (i in mesgs.indices) {
            if (mesgs[i].num == mesgNum) {
                return Field(mesgs[i].getField(fieldName, false))
            }
        }
        return Field(fieldName, Fit.FIELD_NUM_INVALID, 0, 1.0, 0.0, "", false, Profile.Type.ENUM)
    }

    fun createField(mesgName: String?, fieldName: String?, values: ArrayList<Any?>): Field {
        val field = createField(mesgName, fieldName)
        field.values = values
        return field
    }

    private val mesgs = listOf(
        FileIdMesg.fileIdMesg,
        FileCreatorMesg.fileCreatorMesg,
        TimestampCorrelationMesg.timestampCorrelationMesg,
        SoftwareMesg.softwareMesg,
        SlaveDeviceMesg.slaveDeviceMesg,
        CapabilitiesMesg.capabilitiesMesg,
        FileCapabilitiesMesg.fileCapabilitiesMesg,
        MesgCapabilitiesMesg.mesgCapabilitiesMesg,
        FieldCapabilitiesMesg.fieldCapabilitiesMesg,
        DeviceSettingsMesg.deviceSettingsMesg,
        UserProfileMesg.userProfileMesg,
        HrmProfileMesg.hrmProfileMesg,
        SdmProfileMesg.sdmProfileMesg,
        BikeProfileMesg.bikeProfileMesg,
        ConnectivityMesg.connectivityMesg,
        WatchfaceSettingsMesg.watchfaceSettingsMesg,
        OhrSettingsMesg.ohrSettingsMesg,
        TimeInZoneMesg.timeInZoneMesg,
        ZonesTargetMesg.zonesTargetMesg,
        SportMesg.sportMesg,
        HrZoneMesg.hrZoneMesg,
        SpeedZoneMesg.speedZoneMesg,
        CadenceZoneMesg.cadenceZoneMesg,
        PowerZoneMesg.powerZoneMesg,
        MetZoneMesg.metZoneMesg,
        TrainingSettingsMesg.trainingSettingsMesg,
        DiveSettingsMesg.diveSettingsMesg,
        DiveAlarmMesg.diveAlarmMesg,
        DiveApneaAlarmMesg.diveApneaAlarmMesg,
        DiveGasMesg.diveGasMesg,
        GoalMesg.goalMesg,
        ActivityMesg.activityMesg,
        SessionMesg.sessionMesg,
        LapMesg.lapMesg,
        LengthMesg.lengthMesg,
        RecordMesg.recordMesg,
        EventMesg.eventMesg,
        DeviceInfoMesg.deviceInfoMesg,
        DeviceAuxBatteryInfoMesg.deviceAuxBatteryInfoMesg,
        TrainingFileMesg.trainingFileMesg,
        WeatherConditionsMesg.weatherConditionsMesg,
        WeatherAlertMesg.weatherAlertMesg,
        GpsMetadataMesg.gpsMetadataMesg,
        CameraEventMesg.cameraEventMesg,
        GyroscopeDataMesg.gyroscopeDataMesg,
        AccelerometerDataMesg.accelerometerDataMesg,
        MagnetometerDataMesg.magnetometerDataMesg,
        BarometerDataMesg.barometerDataMesg,
        ThreeDSensorCalibrationMesg.threeDSensorCalibrationMesg,
        OneDSensorCalibrationMesg.oneDSensorCalibrationMesg,
        VideoFrameMesg.videoFrameMesg,
        ObdiiDataMesg.obdiiDataMesg,
        NmeaSentenceMesg.nmeaSentenceMesg,
        AviationAttitudeMesg.aviationAttitudeMesg,
        VideoMesg.videoMesg,
        VideoTitleMesg.videoTitleMesg,
        VideoDescriptionMesg.videoDescriptionMesg,
        VideoClipMesg.videoClipMesg,
        SetMesg.setMesg,
        JumpMesg.jumpMesg,
        SplitMesg.splitMesg,
        SplitSummaryMesg.splitSummaryMesg,
        ClimbProMesg.climbProMesg,
        FieldDescriptionMesg.fieldDescriptionMesg,
        DeveloperDataIdMesg.developerDataIdMesg,
        CourseMesg.courseMesg,
        CoursePointMesg.coursePointMesg,
        SegmentIdMesg.segmentIdMesg,
        SegmentLeaderboardEntryMesg.segmentLeaderboardEntryMesg,
        SegmentPointMesg.segmentPointMesg,
        SegmentLapMesg.segmentLapMesg,
        SegmentFileMesg.segmentFileMesg,
        WorkoutMesg.workoutMesg,
        WorkoutSessionMesg.workoutSessionMesg,
        WorkoutStepMesg.workoutStepMesg,
        ExerciseTitleMesg.exerciseTitleMesg,
        ScheduleMesg.scheduleMesg,
        TotalsMesg.totalsMesg,
        WeightScaleMesg.weightScaleMesg,
        BloodPressureMesg.bloodPressureMesg,
        MonitoringInfoMesg.monitoringInfoMesg,
        MonitoringMesg.monitoringMesg,
        MonitoringHrDataMesg.monitoringHrDataMesg,
        Spo2DataMesg.spo2DataMesg,
        HrMesg.hrMesg,
        StressLevelMesg.stressLevelMesg,
        MaxMetDataMesg.maxMetDataMesg,
        HsaBodyBatteryDataMesg.hsaBodyBatteryDataMesg,
        HsaEventMesg.hsaEventMesg,
        HsaAccelerometerDataMesg.hsaAccelerometerDataMesg,
        HsaGyroscopeDataMesg.hsaGyroscopeDataMesg,
        HsaStepDataMesg.hsaStepDataMesg,
        HsaSpo2DataMesg.hsaSpo2DataMesg,
        HsaStressDataMesg.hsaStressDataMesg,
        HsaRespirationDataMesg.hsaRespirationDataMesg,
        HsaHeartRateDataMesg.hsaHeartRateDataMesg,
        HsaConfigurationDataMesg.hsaConfigurationDataMesg,
        HsaWristTemperatureDataMesg.hsaWristTemperatureDataMesg,
        MemoGlobMesg.memoGlobMesg,
        SleepLevelMesg.sleepLevelMesg,
        AntChannelIdMesg.antChannelIdMesg,
        AntRxMesg.antRxMesg,
        AntTxMesg.antTxMesg,
        ExdScreenConfigurationMesg.exdScreenConfigurationMesg,
        ExdDataFieldConfigurationMesg.exdDataFieldConfigurationMesg,
        ExdDataConceptConfigurationMesg.exdDataConceptConfigurationMesg,
        DiveSummaryMesg.diveSummaryMesg,
        AadAccelFeaturesMesg.aadAccelFeaturesMesg,
        HrvMesg.hrvMesg,
        BeatIntervalsMesg.beatIntervalsMesg,
        HrvStatusSummaryMesg.hrvStatusSummaryMesg,
        HrvValueMesg.hrvValueMesg,
        RawBbiMesg.rawBbiMesg,
        RespirationRateMesg.respirationRateMesg,
        ChronoShotSessionMesg.chronoShotSessionMesg,
        ChronoShotDataMesg.chronoShotDataMesg,
        TankUpdateMesg.tankUpdateMesg,
        TankSummaryMesg.tankSummaryMesg,
        SleepAssessmentMesg.sleepAssessmentMesg,
        SleepDisruptionSeverityPeriodMesg.sleepDisruptionSeverityPeriodMesg,
        SleepDisruptionOvernightSeverityMesg.sleepDisruptionOvernightSeverityMesg,
        NapEventMesg.napEventMesg,
        SkinTempOvernightMesg.skinTempOvernightMesg,
        PadMesg.padMesg
    )
}
