/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


class FileCapabilitiesMesg : Mesg {
    constructor() : super(Factory.createMesg(MesgNum.FILE_CAPABILITIES))

    constructor(mesg: Mesg) : super(mesg)


    var messageIndex: Int?
        /**
         * Get message_index field
         *
         * @return message_index
         */
        get() = getFieldIntegerValue(254, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set message_index field
         *
         * @param messageIndex The new messageIndex value to be set
         */
        set(messageIndex) {
            setFieldValue(254, 0, messageIndex, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var type: File?
        /**
         * Get type field
         *
         * @return type
         */
        get() {
            val value = getFieldShortValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD) ?: return null
            return File.getByValue(value)
        }
        /**
         * Set type field
         *
         * @param type The new type value to be set
         */
        set(type) {
            setFieldValue(0, 0, type!!.value, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var flags: Short?
        /**
         * Get flags field
         *
         * @return flags
         */
        get() = getFieldShortValue(1, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set flags field
         *
         * @param flags The new flags value to be set
         */
        set(flags) {
            setFieldValue(1, 0, flags, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var directory: String?
        /**
         * Get directory field
         *
         * @return directory
         */
        get() = getFieldStringValue(2, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set directory field
         *
         * @param directory The new directory value to be set
         */
        set(directory) {
            setFieldValue(2, 0, directory, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var maxCount: Int?
        /**
         * Get max_count field
         *
         * @return max_count
         */
        get() = getFieldIntegerValue(3, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set max_count field
         *
         * @param maxCount The new maxCount value to be set
         */
        set(maxCount) {
            setFieldValue(3, 0, maxCount, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var maxSize: Long?
        /**
         * Get max_size field
         * Units: bytes
         *
         * @return max_size
         */
        get() = getFieldLongValue(4, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set max_size field
         * Units: bytes
         *
         * @param maxSize The new maxSize value to be set
         */
        set(maxSize) {
            setFieldValue(4, 0, maxSize, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    companion object {
        const val MessageIndexFieldNum: Int = 254

        const val TypeFieldNum: Int = 0

        const val FlagsFieldNum: Int = 1

        const val DirectoryFieldNum: Int = 2

        const val MaxCountFieldNum: Int = 3

        const val MaxSizeFieldNum: Int = 4


        // file_capabilities
        val fileCapabilitiesMesg: Mesg = Mesg("file_capabilities", MesgNum.FILE_CAPABILITIES)

        init {
            fileCapabilitiesMesg.addField(
                Field(
                    "message_index",
                    MessageIndexFieldNum,
                    132,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.MESSAGE_INDEX
                )
            )

            fileCapabilitiesMesg.addField(
                Field(
                    "type",
                    TypeFieldNum,
                    0,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.FILE
                )
            )

            fileCapabilitiesMesg.addField(
                Field(
                    "flags",
                    FlagsFieldNum,
                    10,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.FILE_FLAGS
                )
            )

            fileCapabilitiesMesg.addField(
                Field(
                    "directory",
                    DirectoryFieldNum,
                    7,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.STRING
                )
            )

            fileCapabilitiesMesg.addField(
                Field(
                    "max_count",
                    MaxCountFieldNum,
                    132,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT16
                )
            )

            fileCapabilitiesMesg.addField(
                Field(
                    "max_size",
                    MaxSizeFieldNum,
                    134,
                    1.0,
                    0.0,
                    "bytes",
                    false,
                    Profile.Type.UINT32
                )
            )
        }
    }
}
