/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

import com.garmin.fit.Profile.SubFields


class FileIdMesg : Mesg {
    constructor() : super(Factory.createMesg(MesgNum.FILE_ID))

    constructor(mesg: Mesg?) : super(mesg)


    var type: File?
        /**
         * Get type field
         * 
         * @return type
         */
        get() {
            val value = getFieldShortValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
            if (value == null) {
                return null
            }
            return File.Companion.getByValue(value)
        }
        /**
         * Set type field
         * 
         * @param type The new type value to be set
         */
        set(type) {
            setFieldValue(0, 0, type!!.value, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var manufacturer: Int?
        /**
         * Get manufacturer field
         * 
         * @return manufacturer
         */
        get() = getFieldIntegerValue(1, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set manufacturer field
         * 
         * @param manufacturer The new manufacturer value to be set
         */
        set(manufacturer) {
            setFieldValue(1, 0, manufacturer, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var product: Int?
        /**
         * Get product field
         * 
         * @return product
         */
        get() = getFieldIntegerValue(2, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set product field
         * 
         * @param product The new product value to be set
         */
        set(product) {
            setFieldValue(2, 0, product, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var faveroProduct: Int?
        /**
         * Get favero_product field
         * 
         * @return favero_product
         */
        get() = getFieldIntegerValue(2, 0, SubFields.FILE_ID_MESG_PRODUCT_FIELD_FAVERO_PRODUCT)
        /**
         * Set favero_product field
         * 
         * @param faveroProduct The new faveroProduct value to be set
         */
        set(faveroProduct) {
            setFieldValue(2, 0, faveroProduct, SubFields.FILE_ID_MESG_PRODUCT_FIELD_FAVERO_PRODUCT)
        }

    var garminProduct: Int?
        /**
         * Get garmin_product field
         * 
         * @return garmin_product
         */
        get() = getFieldIntegerValue(2, 0, SubFields.FILE_ID_MESG_PRODUCT_FIELD_GARMIN_PRODUCT)
        /**
         * Set garmin_product field
         * 
         * @param garminProduct The new garminProduct value to be set
         */
        set(garminProduct) {
            setFieldValue(2, 0, garminProduct, SubFields.FILE_ID_MESG_PRODUCT_FIELD_GARMIN_PRODUCT)
        }

    var serialNumber: Long?
        /**
         * Get serial_number field
         * 
         * @return serial_number
         */
        get() = getFieldLongValue(3, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set serial_number field
         * 
         * @param serialNumber The new serialNumber value to be set
         */
        set(serialNumber) {
            setFieldValue(3, 0, serialNumber, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var timeCreated: DateTime?
        /**
         * Get time_created field
         * Comment: Only set for files that are can be created/erased.
         * 
         * @return time_created
         */
        get() = timestampToDateTime(getFieldLongValue(4, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD))
        /**
         * Set time_created field
         * Comment: Only set for files that are can be created/erased.
         * 
         * @param timeCreated The new timeCreated value to be set
         */
        set(timeCreated) {
            setFieldValue(4, 0, timeCreated!!.getTimestamp(), Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var number: Int?
        /**
         * Get number field
         * Comment: Only set for files that are not created/erased.
         * 
         * @return number
         */
        get() = getFieldIntegerValue(5, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set number field
         * Comment: Only set for files that are not created/erased.
         * 
         * @param number The new number value to be set
         */
        set(number) {
            setFieldValue(5, 0, number, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var productName: String?
        /**
         * Get product_name field
         * Comment: Optional free form string to indicate the devices name or model
         * 
         * @return product_name
         */
        get() = getFieldStringValue(8, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set product_name field
         * Comment: Optional free form string to indicate the devices name or model
         * 
         * @param productName The new productName value to be set
         */
        set(productName) {
            setFieldValue(8, 0, productName, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    companion object {
        const val TypeFieldNum: Int = 0

        const val ManufacturerFieldNum: Int = 1

        const val ProductFieldNum: Int = 2

        const val SerialNumberFieldNum: Int = 3

        const val TimeCreatedFieldNum: Int = 4

        const val NumberFieldNum: Int = 5

        const val ProductNameFieldNum: Int = 8


        val fileIdMesg: Mesg

        init {
            var field_index = 0
            var subfield_index = 0
            // file_id
            fileIdMesg = Mesg("file_id", MesgNum.FILE_ID)
            fileIdMesg.addField(
                Field(
                    "type",
                    TypeFieldNum,
                    0,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.FILE
                )
            )
            field_index++
            fileIdMesg.addField(
                Field(
                    "manufacturer",
                    ManufacturerFieldNum,
                    132,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.MANUFACTURER
                )
            )
            field_index++
            fileIdMesg.addField(
                Field(
                    "product",
                    ProductFieldNum,
                    132,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT16
                )
            )
            subfield_index = 0
            fileIdMesg.fields.get(field_index).subFields.add(
                SubField(
                    "favero_product",
                    132,
                    1.0,
                    0.0,
                    ""
                )
            )
            fileIdMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 263)
            subfield_index++
            fileIdMesg.fields.get(field_index).subFields.add(
                SubField(
                    "garmin_product",
                    132,
                    1.0,
                    0.0,
                    ""
                )
            )
            fileIdMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 1)
            fileIdMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 15)
            fileIdMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 13)
            fileIdMesg.fields.get(field_index).subFields.get(subfield_index).addMap(1, 89)
            subfield_index++
            field_index++
            fileIdMesg.addField(
                Field(
                    "serial_number",
                    SerialNumberFieldNum,
                    140,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT32Z
                )
            )
            field_index++
            fileIdMesg.addField(
                Field(
                    "time_created",
                    TimeCreatedFieldNum,
                    134,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.DATE_TIME
                )
            )
            field_index++
            fileIdMesg.addField(
                Field(
                    "number",
                    NumberFieldNum,
                    132,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT16
                )
            )
            field_index++
            fileIdMesg.addField(
                Field(
                    "product_name",
                    ProductNameFieldNum,
                    7,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.STRING
                )
            )
            field_index++
        }
    }
}
