/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

object FitBaseType {
    const val ENUM: Short = 0
    const val SINT8: Short = 1
    const val UINT8: Short = 2
    const val SINT16: Short = 131
    const val UINT16: Short = 132
    const val SINT32: Short = 133
    const val UINT32: Short = 134
    const val STRING: Short = 7
    const val FLOAT32: Short = 136
    const val FLOAT64: Short = 137
    const val UINT8Z: Short = 10
    const val UINT16Z: Short = 139
    const val UINT32Z: Short = 140
    const val BYTE: Short = 13
    const val SINT64: Short = 142
    const val UINT64: Short = 143
    const val UINT64Z: Short = 144
    val INVALID: Short = Fit.UINT8_INVALID

    private val stringMap: MutableMap<Short?, String?>

    init {
        stringMap = HashMap<Short?, String?>()
        stringMap.put(ENUM, "ENUM")
        stringMap.put(SINT8, "SINT8")
        stringMap.put(UINT8, "UINT8")
        stringMap.put(SINT16, "SINT16")
        stringMap.put(UINT16, "UINT16")
        stringMap.put(SINT32, "SINT32")
        stringMap.put(UINT32, "UINT32")
        stringMap.put(STRING, "STRING")
        stringMap.put(FLOAT32, "FLOAT32")
        stringMap.put(FLOAT64, "FLOAT64")
        stringMap.put(UINT8Z, "UINT8Z")
        stringMap.put(UINT16Z, "UINT16Z")
        stringMap.put(UINT32Z, "UINT32Z")
        stringMap.put(BYTE, "BYTE")
        stringMap.put(SINT64, "SINT64")
        stringMap.put(UINT64, "UINT64")
        stringMap.put(UINT64Z, "UINT64Z")
    }


    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum contsant
     */
    fun getStringFromValue(value: Short?): String? {
        if (stringMap.containsKey(value)) {
            return stringMap.get(value)
        }

        return ""
    }

    /**
     * Returns the enum constant with the specified name.
     * @param value The enum string value
     * @return The enum constant or INVALID if unknown
     */
    fun getValueFromString(value: String?): Short? {
        for (entry in stringMap.entries) {
            if (entry.value == value) {
                return entry.key
            }
        }

        return INVALID
    }
}
