/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

import java.io.InputStream

class FitDecoder {
    fun decode(inputStream: InputStream?): FitMessages {
        val decode = Decode()
        val fitListener = FitListener()

        try {
            decode.read(inputStream, fitListener, null)
        } catch (fre: FitRuntimeException) {
            // If a FIT file with 0 data size is encountered, attempt to
            // process the next chained FIT file in the input stream.
            if (decode.getInvalidFileDataSize()) {
                decode.nextFile()
                decode.read(inputStream, fitListener, null)
            } else {
                throw fre
            }
        }

        return fitListener.getFitMessages()
    }

    fun decode(inputStream: InputStream?, plugin: MesgBroadcastPlugin?): FitMessages {
        val decode = Decode()
        val fitListener = FitListener()
        val mesgBroadcaster = BufferedMesgBroadcaster(decode)

        mesgBroadcaster.registerMesgBroadcastPlugin(plugin)
        mesgBroadcaster.addListener(fitListener)

        try {
            mesgBroadcaster.run(inputStream)
            mesgBroadcaster.broadcast()
        } catch (fre: FitRuntimeException) {
            // If a FIT file with 0 data size is encountered, attempt to
            // process the next chained FIT file in the input stream.
            if (decode.getInvalidFileDataSize()) {
                decode.nextFile()
                mesgBroadcaster.run(inputStream)
                mesgBroadcaster.broadcast()
            } else {
                throw fre
            }
        }

        return fitListener.getFitMessages()
    }
}
