/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

import java.util.Collections

class FitMessages {
    val fileIdMesgs: MutableList<FileIdMesg?> = ArrayList<FileIdMesg?>()
    val fileCreatorMesgs: MutableList<FileCreatorMesg?> = ArrayList<FileCreatorMesg?>()
    val timestampCorrelationMesgs: MutableList<TimestampCorrelationMesg?> =
        ArrayList<TimestampCorrelationMesg?>()
    val softwareMesgs: MutableList<SoftwareMesg?> = ArrayList<SoftwareMesg?>()
    val slaveDeviceMesgs: MutableList<SlaveDeviceMesg?> = ArrayList<SlaveDeviceMesg?>()
    val capabilitiesMesgs: MutableList<CapabilitiesMesg?> = ArrayList<CapabilitiesMesg?>()
    val fileCapabilitiesMesgs: MutableList<FileCapabilitiesMesg?> =
        ArrayList<FileCapabilitiesMesg?>()
    val mesgCapabilitiesMesgs: MutableList<MesgCapabilitiesMesg?> =
        ArrayList<MesgCapabilitiesMesg?>()
    val fieldCapabilitiesMesgs: MutableList<FieldCapabilitiesMesg?> =
        ArrayList<FieldCapabilitiesMesg?>()
    val deviceSettingsMesgs: MutableList<DeviceSettingsMesg?> = ArrayList<DeviceSettingsMesg?>()
    val userProfileMesgs: MutableList<UserProfileMesg?> = ArrayList<UserProfileMesg?>()
    val hrmProfileMesgs: MutableList<HrmProfileMesg?> = ArrayList<HrmProfileMesg?>()
    val sdmProfileMesgs: MutableList<SdmProfileMesg?> = ArrayList<SdmProfileMesg?>()
    val bikeProfileMesgs: MutableList<BikeProfileMesg?> = ArrayList<BikeProfileMesg?>()
    val connectivityMesgs: MutableList<ConnectivityMesg?> = ArrayList<ConnectivityMesg?>()
    val watchfaceSettingsMesgs: MutableList<WatchfaceSettingsMesg?> =
        ArrayList<WatchfaceSettingsMesg?>()
    val ohrSettingsMesgs: MutableList<OhrSettingsMesg?> = ArrayList<OhrSettingsMesg?>()
    val timeInZoneMesgs: MutableList<TimeInZoneMesg?> = ArrayList<TimeInZoneMesg?>()
    val zonesTargetMesgs: MutableList<ZonesTargetMesg?> = ArrayList<ZonesTargetMesg?>()
    val sportMesgs: MutableList<SportMesg?> = ArrayList<SportMesg?>()
    val hrZoneMesgs: MutableList<HrZoneMesg?> = ArrayList<HrZoneMesg?>()
    val speedZoneMesgs: MutableList<SpeedZoneMesg?> = ArrayList<SpeedZoneMesg?>()
    val cadenceZoneMesgs: MutableList<CadenceZoneMesg?> = ArrayList<CadenceZoneMesg?>()
    val powerZoneMesgs: MutableList<PowerZoneMesg?> = ArrayList<PowerZoneMesg?>()
    val metZoneMesgs: MutableList<MetZoneMesg?> = ArrayList<MetZoneMesg?>()
    val trainingSettingsMesgs: MutableList<TrainingSettingsMesg?> =
        ArrayList<TrainingSettingsMesg?>()
    val diveSettingsMesgs: MutableList<DiveSettingsMesg?> = ArrayList<DiveSettingsMesg?>()
    val diveAlarmMesgs: MutableList<DiveAlarmMesg?> = ArrayList<DiveAlarmMesg?>()
    val diveApneaAlarmMesgs: MutableList<DiveApneaAlarmMesg?> = ArrayList<DiveApneaAlarmMesg?>()
    val diveGasMesgs: MutableList<DiveGasMesg?> = ArrayList<DiveGasMesg?>()
    val goalMesgs: MutableList<GoalMesg?> = ArrayList<GoalMesg?>()
    val activityMesgs: MutableList<ActivityMesg?> = ArrayList<ActivityMesg?>()
    val sessionMesgs: MutableList<SessionMesg?> = ArrayList<SessionMesg?>()
    val lapMesgs: MutableList<LapMesg?> = ArrayList<LapMesg?>()
    val lengthMesgs: MutableList<LengthMesg?> = ArrayList<LengthMesg?>()
    val recordMesgs: MutableList<RecordMesg?> = ArrayList<RecordMesg?>()
    val eventMesgs: MutableList<EventMesg?> = ArrayList<EventMesg?>()
    val deviceInfoMesgs: MutableList<DeviceInfoMesg?> = ArrayList<DeviceInfoMesg?>()
    val deviceAuxBatteryInfoMesgs: MutableList<DeviceAuxBatteryInfoMesg?> =
        ArrayList<DeviceAuxBatteryInfoMesg?>()
    val trainingFileMesgs: MutableList<TrainingFileMesg?> = ArrayList<TrainingFileMesg?>()
    val weatherConditionsMesgs: MutableList<WeatherConditionsMesg?> =
        ArrayList<WeatherConditionsMesg?>()
    val weatherAlertMesgs: MutableList<WeatherAlertMesg?> = ArrayList<WeatherAlertMesg?>()
    val gpsMetadataMesgs: MutableList<GpsMetadataMesg?> = ArrayList<GpsMetadataMesg?>()
    val cameraEventMesgs: MutableList<CameraEventMesg?> = ArrayList<CameraEventMesg?>()
    val gyroscopeDataMesgs: MutableList<GyroscopeDataMesg?> = ArrayList<GyroscopeDataMesg?>()
    val accelerometerDataMesgs: MutableList<AccelerometerDataMesg?> =
        ArrayList<AccelerometerDataMesg?>()
    val magnetometerDataMesgs: MutableList<MagnetometerDataMesg?> =
        ArrayList<MagnetometerDataMesg?>()
    val barometerDataMesgs: MutableList<BarometerDataMesg?> = ArrayList<BarometerDataMesg?>()
    val threeDSensorCalibrationMesgs: MutableList<ThreeDSensorCalibrationMesg?> =
        ArrayList<ThreeDSensorCalibrationMesg?>()
    val oneDSensorCalibrationMesgs: MutableList<OneDSensorCalibrationMesg?> =
        ArrayList<OneDSensorCalibrationMesg?>()
    val videoFrameMesgs: MutableList<VideoFrameMesg?> = ArrayList<VideoFrameMesg?>()
    val obdiiDataMesgs: MutableList<ObdiiDataMesg?> = ArrayList<ObdiiDataMesg?>()
    val nmeaSentenceMesgs: MutableList<NmeaSentenceMesg?> = ArrayList<NmeaSentenceMesg?>()
    val aviationAttitudeMesgs: MutableList<AviationAttitudeMesg?> =
        ArrayList<AviationAttitudeMesg?>()
    val videoMesgs: MutableList<VideoMesg?> = ArrayList<VideoMesg?>()
    val videoTitleMesgs: MutableList<VideoTitleMesg?> = ArrayList<VideoTitleMesg?>()
    val videoDescriptionMesgs: MutableList<VideoDescriptionMesg?> =
        ArrayList<VideoDescriptionMesg?>()
    val videoClipMesgs: MutableList<VideoClipMesg?> = ArrayList<VideoClipMesg?>()
    val setMesgs: MutableList<SetMesg?> = ArrayList<SetMesg?>()
    val jumpMesgs: MutableList<JumpMesg?> = ArrayList<JumpMesg?>()
    val splitMesgs: MutableList<SplitMesg?> = ArrayList<SplitMesg?>()
    val splitSummaryMesgs: MutableList<SplitSummaryMesg?> = ArrayList<SplitSummaryMesg?>()
    val climbProMesgs: MutableList<ClimbProMesg?> = ArrayList<ClimbProMesg?>()
    val fieldDescriptionMesgs: MutableList<FieldDescriptionMesg?> =
        ArrayList<FieldDescriptionMesg?>()
    val developerDataIdMesgs: MutableList<DeveloperDataIdMesg?> = ArrayList<DeveloperDataIdMesg?>()
    val courseMesgs: MutableList<CourseMesg?> = ArrayList<CourseMesg?>()
    val coursePointMesgs: MutableList<CoursePointMesg?> = ArrayList<CoursePointMesg?>()
    val segmentIdMesgs: MutableList<SegmentIdMesg?> = ArrayList<SegmentIdMesg?>()
    val segmentLeaderboardEntryMesgs: MutableList<SegmentLeaderboardEntryMesg?> =
        ArrayList<SegmentLeaderboardEntryMesg?>()
    val segmentPointMesgs: MutableList<SegmentPointMesg?> = ArrayList<SegmentPointMesg?>()
    val segmentLapMesgs: MutableList<SegmentLapMesg?> = ArrayList<SegmentLapMesg?>()
    val segmentFileMesgs: MutableList<SegmentFileMesg?> = ArrayList<SegmentFileMesg?>()
    val workoutMesgs: MutableList<WorkoutMesg?> = ArrayList<WorkoutMesg?>()
    val workoutSessionMesgs: MutableList<WorkoutSessionMesg?> = ArrayList<WorkoutSessionMesg?>()
    val workoutStepMesgs: MutableList<WorkoutStepMesg?> = ArrayList<WorkoutStepMesg?>()
    val exerciseTitleMesgs: MutableList<ExerciseTitleMesg?> = ArrayList<ExerciseTitleMesg?>()
    val scheduleMesgs: MutableList<ScheduleMesg?> = ArrayList<ScheduleMesg?>()
    val totalsMesgs: MutableList<TotalsMesg?> = ArrayList<TotalsMesg?>()
    val weightScaleMesgs: MutableList<WeightScaleMesg?> = ArrayList<WeightScaleMesg?>()
    val bloodPressureMesgs: MutableList<BloodPressureMesg?> = ArrayList<BloodPressureMesg?>()
    val monitoringInfoMesgs: MutableList<MonitoringInfoMesg?> = ArrayList<MonitoringInfoMesg?>()
    val monitoringMesgs: MutableList<MonitoringMesg?> = ArrayList<MonitoringMesg?>()
    val monitoringHrDataMesgs: MutableList<MonitoringHrDataMesg?> =
        ArrayList<MonitoringHrDataMesg?>()
    val spo2DataMesgs: MutableList<Spo2DataMesg?> = ArrayList<Spo2DataMesg?>()
    val hrMesgs: MutableList<HrMesg?> = ArrayList<HrMesg?>()
    val stressLevelMesgs: MutableList<StressLevelMesg?> = ArrayList<StressLevelMesg?>()
    val maxMetDataMesgs: MutableList<MaxMetDataMesg?> = ArrayList<MaxMetDataMesg?>()
    val hsaBodyBatteryDataMesgs: MutableList<HsaBodyBatteryDataMesg?> =
        ArrayList<HsaBodyBatteryDataMesg?>()
    val hsaEventMesgs: MutableList<HsaEventMesg?> = ArrayList<HsaEventMesg?>()
    val hsaAccelerometerDataMesgs: MutableList<HsaAccelerometerDataMesg?> =
        ArrayList<HsaAccelerometerDataMesg?>()
    val hsaGyroscopeDataMesgs: MutableList<HsaGyroscopeDataMesg?> =
        ArrayList<HsaGyroscopeDataMesg?>()
    val hsaStepDataMesgs: MutableList<HsaStepDataMesg?> = ArrayList<HsaStepDataMesg?>()
    val hsaSpo2DataMesgs: MutableList<HsaSpo2DataMesg?> = ArrayList<HsaSpo2DataMesg?>()
    val hsaStressDataMesgs: MutableList<HsaStressDataMesg?> = ArrayList<HsaStressDataMesg?>()
    val hsaRespirationDataMesgs: MutableList<HsaRespirationDataMesg?> =
        ArrayList<HsaRespirationDataMesg?>()
    val hsaHeartRateDataMesgs: MutableList<HsaHeartRateDataMesg?> =
        ArrayList<HsaHeartRateDataMesg?>()
    val hsaConfigurationDataMesgs: MutableList<HsaConfigurationDataMesg?> =
        ArrayList<HsaConfigurationDataMesg?>()
    val hsaWristTemperatureDataMesgs: MutableList<HsaWristTemperatureDataMesg?> =
        ArrayList<HsaWristTemperatureDataMesg?>()
    val memoGlobMesgs: MutableList<MemoGlobMesg?> = ArrayList<MemoGlobMesg?>()
    val sleepLevelMesgs: MutableList<SleepLevelMesg?> = ArrayList<SleepLevelMesg?>()
    val antChannelIdMesgs: MutableList<AntChannelIdMesg?> = ArrayList<AntChannelIdMesg?>()
    val antRxMesgs: MutableList<AntRxMesg?> = ArrayList<AntRxMesg?>()
    val antTxMesgs: MutableList<AntTxMesg?> = ArrayList<AntTxMesg?>()
    val exdScreenConfigurationMesgs: MutableList<ExdScreenConfigurationMesg?> =
        ArrayList<ExdScreenConfigurationMesg?>()
    val exdDataFieldConfigurationMesgs: MutableList<ExdDataFieldConfigurationMesg?> =
        ArrayList<ExdDataFieldConfigurationMesg?>()
    val exdDataConceptConfigurationMesgs: MutableList<ExdDataConceptConfigurationMesg?> =
        ArrayList<ExdDataConceptConfigurationMesg?>()
    val diveSummaryMesgs: MutableList<DiveSummaryMesg?> = ArrayList<DiveSummaryMesg?>()
    val aadAccelFeaturesMesgs: MutableList<AadAccelFeaturesMesg?> =
        ArrayList<AadAccelFeaturesMesg?>()
    val hrvMesgs: MutableList<HrvMesg?> = ArrayList<HrvMesg?>()
    val beatIntervalsMesgs: MutableList<BeatIntervalsMesg?> = ArrayList<BeatIntervalsMesg?>()
    val hrvStatusSummaryMesgs: MutableList<HrvStatusSummaryMesg?> =
        ArrayList<HrvStatusSummaryMesg?>()
    val hrvValueMesgs: MutableList<HrvValueMesg?> = ArrayList<HrvValueMesg?>()
    val rawBbiMesgs: MutableList<RawBbiMesg?> = ArrayList<RawBbiMesg?>()
    val respirationRateMesgs: MutableList<RespirationRateMesg?> = ArrayList<RespirationRateMesg?>()
    val chronoShotSessionMesgs: MutableList<ChronoShotSessionMesg?> =
        ArrayList<ChronoShotSessionMesg?>()
    val chronoShotDataMesgs: MutableList<ChronoShotDataMesg?> = ArrayList<ChronoShotDataMesg?>()
    val tankUpdateMesgs: MutableList<TankUpdateMesg?> = ArrayList<TankUpdateMesg?>()
    val tankSummaryMesgs: MutableList<TankSummaryMesg?> = ArrayList<TankSummaryMesg?>()
    val sleepAssessmentMesgs: MutableList<SleepAssessmentMesg?> = ArrayList<SleepAssessmentMesg?>()
    val sleepDisruptionSeverityPeriodMesgs: MutableList<SleepDisruptionSeverityPeriodMesg?> =
        ArrayList<SleepDisruptionSeverityPeriodMesg?>()
    val sleepDisruptionOvernightSeverityMesgs: MutableList<SleepDisruptionOvernightSeverityMesg?> =
        ArrayList<SleepDisruptionOvernightSeverityMesg?>()
    val napEventMesgs: MutableList<NapEventMesg?> = ArrayList<NapEventMesg?>()
    val skinTempOvernightMesgs: MutableList<SkinTempOvernightMesg?> =
        ArrayList<SkinTempOvernightMesg?>()
    val padMesgs: MutableList<PadMesg?> = ArrayList<PadMesg?>()

    val developerFieldDescriptionMesgs: MutableList<DeveloperFieldDescription?> =
        ArrayList<DeveloperFieldDescription?>()

    fun getFileIdMesgs(): MutableList<FileIdMesg?> {
        return Collections.unmodifiableList<FileIdMesg?>(fileIdMesgs)
    }

    fun getFileCreatorMesgs(): MutableList<FileCreatorMesg?> {
        return Collections.unmodifiableList<FileCreatorMesg?>(fileCreatorMesgs)
    }

    fun getTimestampCorrelationMesgs(): MutableList<TimestampCorrelationMesg?> {
        return Collections.unmodifiableList<TimestampCorrelationMesg?>(timestampCorrelationMesgs)
    }

    fun getSoftwareMesgs(): MutableList<SoftwareMesg?> {
        return Collections.unmodifiableList<SoftwareMesg?>(softwareMesgs)
    }

    fun getSlaveDeviceMesgs(): MutableList<SlaveDeviceMesg?> {
        return Collections.unmodifiableList<SlaveDeviceMesg?>(slaveDeviceMesgs)
    }

    fun getCapabilitiesMesgs(): MutableList<CapabilitiesMesg?> {
        return Collections.unmodifiableList<CapabilitiesMesg?>(capabilitiesMesgs)
    }

    fun getFileCapabilitiesMesgs(): MutableList<FileCapabilitiesMesg?> {
        return Collections.unmodifiableList<FileCapabilitiesMesg?>(fileCapabilitiesMesgs)
    }

    fun getMesgCapabilitiesMesgs(): MutableList<MesgCapabilitiesMesg?> {
        return Collections.unmodifiableList<MesgCapabilitiesMesg?>(mesgCapabilitiesMesgs)
    }

    fun getFieldCapabilitiesMesgs(): MutableList<FieldCapabilitiesMesg?> {
        return Collections.unmodifiableList<FieldCapabilitiesMesg?>(fieldCapabilitiesMesgs)
    }

    fun getDeviceSettingsMesgs(): MutableList<DeviceSettingsMesg?> {
        return Collections.unmodifiableList<DeviceSettingsMesg?>(deviceSettingsMesgs)
    }

    fun getUserProfileMesgs(): MutableList<UserProfileMesg?> {
        return Collections.unmodifiableList<UserProfileMesg?>(userProfileMesgs)
    }

    fun getHrmProfileMesgs(): MutableList<HrmProfileMesg?> {
        return Collections.unmodifiableList<HrmProfileMesg?>(hrmProfileMesgs)
    }

    fun getSdmProfileMesgs(): MutableList<SdmProfileMesg?> {
        return Collections.unmodifiableList<SdmProfileMesg?>(sdmProfileMesgs)
    }

    fun getBikeProfileMesgs(): MutableList<BikeProfileMesg?> {
        return Collections.unmodifiableList<BikeProfileMesg?>(bikeProfileMesgs)
    }

    fun getConnectivityMesgs(): MutableList<ConnectivityMesg?> {
        return Collections.unmodifiableList<ConnectivityMesg?>(connectivityMesgs)
    }

    fun getWatchfaceSettingsMesgs(): MutableList<WatchfaceSettingsMesg?> {
        return Collections.unmodifiableList<WatchfaceSettingsMesg?>(watchfaceSettingsMesgs)
    }

    fun getOhrSettingsMesgs(): MutableList<OhrSettingsMesg?> {
        return Collections.unmodifiableList<OhrSettingsMesg?>(ohrSettingsMesgs)
    }

    fun getTimeInZoneMesgs(): MutableList<TimeInZoneMesg?> {
        return Collections.unmodifiableList<TimeInZoneMesg?>(timeInZoneMesgs)
    }

    fun getZonesTargetMesgs(): MutableList<ZonesTargetMesg?> {
        return Collections.unmodifiableList<ZonesTargetMesg?>(zonesTargetMesgs)
    }

    fun getSportMesgs(): MutableList<SportMesg?> {
        return Collections.unmodifiableList<SportMesg?>(sportMesgs)
    }

    fun getHrZoneMesgs(): MutableList<HrZoneMesg?> {
        return Collections.unmodifiableList<HrZoneMesg?>(hrZoneMesgs)
    }

    fun getSpeedZoneMesgs(): MutableList<SpeedZoneMesg?> {
        return Collections.unmodifiableList<SpeedZoneMesg?>(speedZoneMesgs)
    }

    fun getCadenceZoneMesgs(): MutableList<CadenceZoneMesg?> {
        return Collections.unmodifiableList<CadenceZoneMesg?>(cadenceZoneMesgs)
    }

    fun getPowerZoneMesgs(): MutableList<PowerZoneMesg?> {
        return Collections.unmodifiableList<PowerZoneMesg?>(powerZoneMesgs)
    }

    fun getMetZoneMesgs(): MutableList<MetZoneMesg?> {
        return Collections.unmodifiableList<MetZoneMesg?>(metZoneMesgs)
    }

    fun getTrainingSettingsMesgs(): MutableList<TrainingSettingsMesg?> {
        return Collections.unmodifiableList<TrainingSettingsMesg?>(trainingSettingsMesgs)
    }

    fun getDiveSettingsMesgs(): MutableList<DiveSettingsMesg?> {
        return Collections.unmodifiableList<DiveSettingsMesg?>(diveSettingsMesgs)
    }

    fun getDiveAlarmMesgs(): MutableList<DiveAlarmMesg?> {
        return Collections.unmodifiableList<DiveAlarmMesg?>(diveAlarmMesgs)
    }

    fun getDiveApneaAlarmMesgs(): MutableList<DiveApneaAlarmMesg?> {
        return Collections.unmodifiableList<DiveApneaAlarmMesg?>(diveApneaAlarmMesgs)
    }

    fun getDiveGasMesgs(): MutableList<DiveGasMesg?> {
        return Collections.unmodifiableList<DiveGasMesg?>(diveGasMesgs)
    }

    fun getGoalMesgs(): MutableList<GoalMesg?> {
        return Collections.unmodifiableList<GoalMesg?>(goalMesgs)
    }

    fun getActivityMesgs(): MutableList<ActivityMesg?> {
        return Collections.unmodifiableList<ActivityMesg?>(activityMesgs)
    }

    fun getSessionMesgs(): MutableList<SessionMesg?> {
        return Collections.unmodifiableList<SessionMesg?>(sessionMesgs)
    }

    fun getLapMesgs(): MutableList<LapMesg?> {
        return Collections.unmodifiableList<LapMesg?>(lapMesgs)
    }

    fun getLengthMesgs(): MutableList<LengthMesg?> {
        return Collections.unmodifiableList<LengthMesg?>(lengthMesgs)
    }

    fun getRecordMesgs(): MutableList<RecordMesg?> {
        return Collections.unmodifiableList<RecordMesg?>(recordMesgs)
    }

    fun getEventMesgs(): MutableList<EventMesg?> {
        return Collections.unmodifiableList<EventMesg?>(eventMesgs)
    }

    fun getDeviceInfoMesgs(): MutableList<DeviceInfoMesg?> {
        return Collections.unmodifiableList<DeviceInfoMesg?>(deviceInfoMesgs)
    }

    fun getDeviceAuxBatteryInfoMesgs(): MutableList<DeviceAuxBatteryInfoMesg?> {
        return Collections.unmodifiableList<DeviceAuxBatteryInfoMesg?>(deviceAuxBatteryInfoMesgs)
    }

    fun getTrainingFileMesgs(): MutableList<TrainingFileMesg?> {
        return Collections.unmodifiableList<TrainingFileMesg?>(trainingFileMesgs)
    }

    fun getWeatherConditionsMesgs(): MutableList<WeatherConditionsMesg?> {
        return Collections.unmodifiableList<WeatherConditionsMesg?>(weatherConditionsMesgs)
    }

    fun getWeatherAlertMesgs(): MutableList<WeatherAlertMesg?> {
        return Collections.unmodifiableList<WeatherAlertMesg?>(weatherAlertMesgs)
    }

    fun getGpsMetadataMesgs(): MutableList<GpsMetadataMesg?> {
        return Collections.unmodifiableList<GpsMetadataMesg?>(gpsMetadataMesgs)
    }

    fun getCameraEventMesgs(): MutableList<CameraEventMesg?> {
        return Collections.unmodifiableList<CameraEventMesg?>(cameraEventMesgs)
    }

    fun getGyroscopeDataMesgs(): MutableList<GyroscopeDataMesg?> {
        return Collections.unmodifiableList<GyroscopeDataMesg?>(gyroscopeDataMesgs)
    }

    fun getAccelerometerDataMesgs(): MutableList<AccelerometerDataMesg?> {
        return Collections.unmodifiableList<AccelerometerDataMesg?>(accelerometerDataMesgs)
    }

    fun getMagnetometerDataMesgs(): MutableList<MagnetometerDataMesg?> {
        return Collections.unmodifiableList<MagnetometerDataMesg?>(magnetometerDataMesgs)
    }

    fun getBarometerDataMesgs(): MutableList<BarometerDataMesg?> {
        return Collections.unmodifiableList<BarometerDataMesg?>(barometerDataMesgs)
    }

    fun getThreeDSensorCalibrationMesgs(): MutableList<ThreeDSensorCalibrationMesg?> {
        return Collections.unmodifiableList<ThreeDSensorCalibrationMesg?>(
            threeDSensorCalibrationMesgs
        )
    }

    fun getOneDSensorCalibrationMesgs(): MutableList<OneDSensorCalibrationMesg?> {
        return Collections.unmodifiableList<OneDSensorCalibrationMesg?>(oneDSensorCalibrationMesgs)
    }

    fun getVideoFrameMesgs(): MutableList<VideoFrameMesg?> {
        return Collections.unmodifiableList<VideoFrameMesg?>(videoFrameMesgs)
    }

    fun getObdiiDataMesgs(): MutableList<ObdiiDataMesg?> {
        return Collections.unmodifiableList<ObdiiDataMesg?>(obdiiDataMesgs)
    }

    fun getNmeaSentenceMesgs(): MutableList<NmeaSentenceMesg?> {
        return Collections.unmodifiableList<NmeaSentenceMesg?>(nmeaSentenceMesgs)
    }

    fun getAviationAttitudeMesgs(): MutableList<AviationAttitudeMesg?> {
        return Collections.unmodifiableList<AviationAttitudeMesg?>(aviationAttitudeMesgs)
    }

    fun getVideoMesgs(): MutableList<VideoMesg?> {
        return Collections.unmodifiableList<VideoMesg?>(videoMesgs)
    }

    fun getVideoTitleMesgs(): MutableList<VideoTitleMesg?> {
        return Collections.unmodifiableList<VideoTitleMesg?>(videoTitleMesgs)
    }

    fun getVideoDescriptionMesgs(): MutableList<VideoDescriptionMesg?> {
        return Collections.unmodifiableList<VideoDescriptionMesg?>(videoDescriptionMesgs)
    }

    fun getVideoClipMesgs(): MutableList<VideoClipMesg?> {
        return Collections.unmodifiableList<VideoClipMesg?>(videoClipMesgs)
    }

    fun getSetMesgs(): MutableList<SetMesg?> {
        return Collections.unmodifiableList<SetMesg?>(setMesgs)
    }

    fun getJumpMesgs(): MutableList<JumpMesg?> {
        return Collections.unmodifiableList<JumpMesg?>(jumpMesgs)
    }

    fun getSplitMesgs(): MutableList<SplitMesg?> {
        return Collections.unmodifiableList<SplitMesg?>(splitMesgs)
    }

    fun getSplitSummaryMesgs(): MutableList<SplitSummaryMesg?> {
        return Collections.unmodifiableList<SplitSummaryMesg?>(splitSummaryMesgs)
    }

    fun getClimbProMesgs(): MutableList<ClimbProMesg?> {
        return Collections.unmodifiableList<ClimbProMesg?>(climbProMesgs)
    }

    fun getFieldDescriptionMesgs(): MutableList<FieldDescriptionMesg?> {
        return Collections.unmodifiableList<FieldDescriptionMesg?>(fieldDescriptionMesgs)
    }

    fun getDeveloperDataIdMesgs(): MutableList<DeveloperDataIdMesg?> {
        return Collections.unmodifiableList<DeveloperDataIdMesg?>(developerDataIdMesgs)
    }

    fun getCourseMesgs(): MutableList<CourseMesg?> {
        return Collections.unmodifiableList<CourseMesg?>(courseMesgs)
    }

    fun getCoursePointMesgs(): MutableList<CoursePointMesg?> {
        return Collections.unmodifiableList<CoursePointMesg?>(coursePointMesgs)
    }

    fun getSegmentIdMesgs(): MutableList<SegmentIdMesg?> {
        return Collections.unmodifiableList<SegmentIdMesg?>(segmentIdMesgs)
    }

    fun getSegmentLeaderboardEntryMesgs(): MutableList<SegmentLeaderboardEntryMesg?> {
        return Collections.unmodifiableList<SegmentLeaderboardEntryMesg?>(
            segmentLeaderboardEntryMesgs
        )
    }

    fun getSegmentPointMesgs(): MutableList<SegmentPointMesg?> {
        return Collections.unmodifiableList<SegmentPointMesg?>(segmentPointMesgs)
    }

    fun getSegmentLapMesgs(): MutableList<SegmentLapMesg?> {
        return Collections.unmodifiableList<SegmentLapMesg?>(segmentLapMesgs)
    }

    fun getSegmentFileMesgs(): MutableList<SegmentFileMesg?> {
        return Collections.unmodifiableList<SegmentFileMesg?>(segmentFileMesgs)
    }

    fun getWorkoutMesgs(): MutableList<WorkoutMesg?> {
        return Collections.unmodifiableList<WorkoutMesg?>(workoutMesgs)
    }

    fun getWorkoutSessionMesgs(): MutableList<WorkoutSessionMesg?> {
        return Collections.unmodifiableList<WorkoutSessionMesg?>(workoutSessionMesgs)
    }

    fun getWorkoutStepMesgs(): MutableList<WorkoutStepMesg?> {
        return Collections.unmodifiableList<WorkoutStepMesg?>(workoutStepMesgs)
    }

    fun getExerciseTitleMesgs(): MutableList<ExerciseTitleMesg?> {
        return Collections.unmodifiableList<ExerciseTitleMesg?>(exerciseTitleMesgs)
    }

    fun getScheduleMesgs(): MutableList<ScheduleMesg?> {
        return Collections.unmodifiableList<ScheduleMesg?>(scheduleMesgs)
    }

    fun getTotalsMesgs(): MutableList<TotalsMesg?> {
        return Collections.unmodifiableList<TotalsMesg?>(totalsMesgs)
    }

    fun getWeightScaleMesgs(): MutableList<WeightScaleMesg?> {
        return Collections.unmodifiableList<WeightScaleMesg?>(weightScaleMesgs)
    }

    fun getBloodPressureMesgs(): MutableList<BloodPressureMesg?> {
        return Collections.unmodifiableList<BloodPressureMesg?>(bloodPressureMesgs)
    }

    fun getMonitoringInfoMesgs(): MutableList<MonitoringInfoMesg?> {
        return Collections.unmodifiableList<MonitoringInfoMesg?>(monitoringInfoMesgs)
    }

    fun getMonitoringMesgs(): MutableList<MonitoringMesg?> {
        return Collections.unmodifiableList<MonitoringMesg?>(monitoringMesgs)
    }

    fun getMonitoringHrDataMesgs(): MutableList<MonitoringHrDataMesg?> {
        return Collections.unmodifiableList<MonitoringHrDataMesg?>(monitoringHrDataMesgs)
    }

    fun getSpo2DataMesgs(): MutableList<Spo2DataMesg?> {
        return Collections.unmodifiableList<Spo2DataMesg?>(spo2DataMesgs)
    }

    fun getHrMesgs(): MutableList<HrMesg?> {
        return Collections.unmodifiableList<HrMesg?>(hrMesgs)
    }

    fun getStressLevelMesgs(): MutableList<StressLevelMesg?> {
        return Collections.unmodifiableList<StressLevelMesg?>(stressLevelMesgs)
    }

    fun getMaxMetDataMesgs(): MutableList<MaxMetDataMesg?> {
        return Collections.unmodifiableList<MaxMetDataMesg?>(maxMetDataMesgs)
    }

    fun getHsaBodyBatteryDataMesgs(): MutableList<HsaBodyBatteryDataMesg?> {
        return Collections.unmodifiableList<HsaBodyBatteryDataMesg?>(hsaBodyBatteryDataMesgs)
    }

    fun getHsaEventMesgs(): MutableList<HsaEventMesg?> {
        return Collections.unmodifiableList<HsaEventMesg?>(hsaEventMesgs)
    }

    fun getHsaAccelerometerDataMesgs(): MutableList<HsaAccelerometerDataMesg?> {
        return Collections.unmodifiableList<HsaAccelerometerDataMesg?>(hsaAccelerometerDataMesgs)
    }

    fun getHsaGyroscopeDataMesgs(): MutableList<HsaGyroscopeDataMesg?> {
        return Collections.unmodifiableList<HsaGyroscopeDataMesg?>(hsaGyroscopeDataMesgs)
    }

    fun getHsaStepDataMesgs(): MutableList<HsaStepDataMesg?> {
        return Collections.unmodifiableList<HsaStepDataMesg?>(hsaStepDataMesgs)
    }

    fun getHsaSpo2DataMesgs(): MutableList<HsaSpo2DataMesg?> {
        return Collections.unmodifiableList<HsaSpo2DataMesg?>(hsaSpo2DataMesgs)
    }

    fun getHsaStressDataMesgs(): MutableList<HsaStressDataMesg?> {
        return Collections.unmodifiableList<HsaStressDataMesg?>(hsaStressDataMesgs)
    }

    fun getHsaRespirationDataMesgs(): MutableList<HsaRespirationDataMesg?> {
        return Collections.unmodifiableList<HsaRespirationDataMesg?>(hsaRespirationDataMesgs)
    }

    fun getHsaHeartRateDataMesgs(): MutableList<HsaHeartRateDataMesg?> {
        return Collections.unmodifiableList<HsaHeartRateDataMesg?>(hsaHeartRateDataMesgs)
    }

    fun getHsaConfigurationDataMesgs(): MutableList<HsaConfigurationDataMesg?> {
        return Collections.unmodifiableList<HsaConfigurationDataMesg?>(hsaConfigurationDataMesgs)
    }

    fun getHsaWristTemperatureDataMesgs(): MutableList<HsaWristTemperatureDataMesg?> {
        return Collections.unmodifiableList<HsaWristTemperatureDataMesg?>(
            hsaWristTemperatureDataMesgs
        )
    }

    fun getMemoGlobMesgs(): MutableList<MemoGlobMesg?> {
        return Collections.unmodifiableList<MemoGlobMesg?>(memoGlobMesgs)
    }

    fun getSleepLevelMesgs(): MutableList<SleepLevelMesg?> {
        return Collections.unmodifiableList<SleepLevelMesg?>(sleepLevelMesgs)
    }

    fun getAntChannelIdMesgs(): MutableList<AntChannelIdMesg?> {
        return Collections.unmodifiableList<AntChannelIdMesg?>(antChannelIdMesgs)
    }

    fun getAntRxMesgs(): MutableList<AntRxMesg?> {
        return Collections.unmodifiableList<AntRxMesg?>(antRxMesgs)
    }

    fun getAntTxMesgs(): MutableList<AntTxMesg?> {
        return Collections.unmodifiableList<AntTxMesg?>(antTxMesgs)
    }

    fun getExdScreenConfigurationMesgs(): MutableList<ExdScreenConfigurationMesg?> {
        return Collections.unmodifiableList<ExdScreenConfigurationMesg?>(exdScreenConfigurationMesgs)
    }

    fun getExdDataFieldConfigurationMesgs(): MutableList<ExdDataFieldConfigurationMesg?> {
        return Collections.unmodifiableList<ExdDataFieldConfigurationMesg?>(
            exdDataFieldConfigurationMesgs
        )
    }

    fun getExdDataConceptConfigurationMesgs(): MutableList<ExdDataConceptConfigurationMesg?> {
        return Collections.unmodifiableList<ExdDataConceptConfigurationMesg?>(
            exdDataConceptConfigurationMesgs
        )
    }

    fun getDiveSummaryMesgs(): MutableList<DiveSummaryMesg?> {
        return Collections.unmodifiableList<DiveSummaryMesg?>(diveSummaryMesgs)
    }

    fun getAadAccelFeaturesMesgs(): MutableList<AadAccelFeaturesMesg?> {
        return Collections.unmodifiableList<AadAccelFeaturesMesg?>(aadAccelFeaturesMesgs)
    }

    fun getHrvMesgs(): MutableList<HrvMesg?> {
        return Collections.unmodifiableList<HrvMesg?>(hrvMesgs)
    }

    fun getBeatIntervalsMesgs(): MutableList<BeatIntervalsMesg?> {
        return Collections.unmodifiableList<BeatIntervalsMesg?>(beatIntervalsMesgs)
    }

    fun getHrvStatusSummaryMesgs(): MutableList<HrvStatusSummaryMesg?> {
        return Collections.unmodifiableList<HrvStatusSummaryMesg?>(hrvStatusSummaryMesgs)
    }

    fun getHrvValueMesgs(): MutableList<HrvValueMesg?> {
        return Collections.unmodifiableList<HrvValueMesg?>(hrvValueMesgs)
    }

    fun getRawBbiMesgs(): MutableList<RawBbiMesg?> {
        return Collections.unmodifiableList<RawBbiMesg?>(rawBbiMesgs)
    }

    fun getRespirationRateMesgs(): MutableList<RespirationRateMesg?> {
        return Collections.unmodifiableList<RespirationRateMesg?>(respirationRateMesgs)
    }

    fun getChronoShotSessionMesgs(): MutableList<ChronoShotSessionMesg?> {
        return Collections.unmodifiableList<ChronoShotSessionMesg?>(chronoShotSessionMesgs)
    }

    fun getChronoShotDataMesgs(): MutableList<ChronoShotDataMesg?> {
        return Collections.unmodifiableList<ChronoShotDataMesg?>(chronoShotDataMesgs)
    }

    fun getTankUpdateMesgs(): MutableList<TankUpdateMesg?> {
        return Collections.unmodifiableList<TankUpdateMesg?>(tankUpdateMesgs)
    }

    fun getTankSummaryMesgs(): MutableList<TankSummaryMesg?> {
        return Collections.unmodifiableList<TankSummaryMesg?>(tankSummaryMesgs)
    }

    fun getSleepAssessmentMesgs(): MutableList<SleepAssessmentMesg?> {
        return Collections.unmodifiableList<SleepAssessmentMesg?>(sleepAssessmentMesgs)
    }

    fun getSleepDisruptionSeverityPeriodMesgs(): MutableList<SleepDisruptionSeverityPeriodMesg?> {
        return Collections.unmodifiableList<SleepDisruptionSeverityPeriodMesg?>(
            sleepDisruptionSeverityPeriodMesgs
        )
    }

    fun getSleepDisruptionOvernightSeverityMesgs(): MutableList<SleepDisruptionOvernightSeverityMesg?> {
        return Collections.unmodifiableList<SleepDisruptionOvernightSeverityMesg?>(
            sleepDisruptionOvernightSeverityMesgs
        )
    }

    fun getNapEventMesgs(): MutableList<NapEventMesg?> {
        return Collections.unmodifiableList<NapEventMesg?>(napEventMesgs)
    }

    fun getSkinTempOvernightMesgs(): MutableList<SkinTempOvernightMesg?> {
        return Collections.unmodifiableList<SkinTempOvernightMesg?>(skinTempOvernightMesgs)
    }

    fun getPadMesgs(): MutableList<PadMesg?> {
        return Collections.unmodifiableList<PadMesg?>(padMesgs)
    }

    fun getDeveloperFieldDescriptionMesgs(): MutableList<DeveloperFieldDescription?> {
        return Collections.unmodifiableList<DeveloperFieldDescription?>(
            developerFieldDescriptionMesgs
        )
    }
}