/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

object LanguageBits4 {
    const val BRAZILIAN_PORTUGUESE: Short = 0x01
    const val INDONESIAN: Short = 0x02
    const val MALAYSIAN: Short = 0x04
    const val VIETNAMESE: Short = 0x08
    const val BURMESE: Short = 0x10
    const val MONGOLIAN: Short = 0x20
    val INVALID: Short = Fit.UINT8Z_INVALID

    private val stringMap: MutableMap<Short?, String?>

    init {
        stringMap = HashMap<Short?, String?>()
        stringMap.put(BRAZILIAN_PORTUGUESE, "BRAZILIAN_PORTUGUESE")
        stringMap.put(INDONESIAN, "INDONESIAN")
        stringMap.put(MALAYSIAN, "MALAYSIAN")
        stringMap.put(VIETNAMESE, "VIETNAMESE")
        stringMap.put(BURMESE, "BURMESE")
        stringMap.put(MONGOLIAN, "MONGOLIAN")
    }


    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum contsant
     */
    fun getStringFromValue(value: Short?): String? {
        if (stringMap.containsKey(value)) {
            return stringMap.get(value)
        }

        return ""
    }

    /**
     * Returns the enum constant with the specified name.
     * @param value The enum string value
     * @return The enum constant or INVALID if unknown
     */
    fun getValueFromString(value: String?): Short? {
        for (entry in stringMap.entries) {
            if (entry.value == value) {
                return entry.key
            }
        }

        return INVALID
    }
}
