/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

object LateralRaiseExerciseName {
    const val _45_DEGREE_CABLE_EXTERNAL_ROTATION: Int = 0
    const val ALTERNATING_LATERAL_RAISE_WITH_STATIC_HOLD: Int = 1
    const val BAR_MUSCLE_UP: Int = 2
    const val BENT_OVER_LATERAL_RAISE: Int = 3
    const val CABLE_DIAGONAL_RAISE: Int = 4
    const val CABLE_FRONT_RAISE: Int = 5
    const val CALORIE_ROW: Int = 6
    const val COMBO_SHOULDER_RAISE: Int = 7
    const val DUMBBELL_DIAGONAL_RAISE: Int = 8
    const val DUMBBELL_V_RAISE: Int = 9
    const val FRONT_RAISE: Int = 10
    const val LEANING_DUMBBELL_LATERAL_RAISE: Int = 11
    const val LYING_DUMBBELL_RAISE: Int = 12
    const val MUSCLE_UP: Int = 13
    const val ONE_ARM_CABLE_LATERAL_RAISE: Int = 14
    const val OVERHAND_GRIP_REAR_LATERAL_RAISE: Int = 15
    const val PLATE_RAISES: Int = 16
    const val RING_DIP: Int = 17
    const val WEIGHTED_RING_DIP: Int = 18
    const val RING_MUSCLE_UP: Int = 19
    const val WEIGHTED_RING_MUSCLE_UP: Int = 20
    const val ROPE_CLIMB: Int = 21
    const val WEIGHTED_ROPE_CLIMB: Int = 22
    const val SCAPTION: Int = 23
    const val SEATED_LATERAL_RAISE: Int = 24
    const val SEATED_REAR_LATERAL_RAISE: Int = 25
    const val SIDE_LYING_LATERAL_RAISE: Int = 26
    const val STANDING_LIFT: Int = 27
    const val SUSPENDED_ROW: Int = 28
    const val UNDERHAND_GRIP_REAR_LATERAL_RAISE: Int = 29
    const val WALL_SLIDE: Int = 30
    const val WEIGHTED_WALL_SLIDE: Int = 31
    const val ARM_CIRCLES: Int = 32
    const val SHAVING_THE_HEAD: Int = 33
    const val DUMBBELL_LATERAL_RAISE: Int = 34
    const val RING_DIP_KIPPING: Int = 36
    const val WALL_WALK: Int = 37
    const val DUMBBELL_FRONT_RAISE_WHEELCHAIR: Int = 38
    const val DUMBBELL_LATERAL_RAISE_WHEELCHAIR: Int = 39
    const val POLE_DOUBLE_ARM_OVERHEAD_AND_FORWARD_WHEELCHAIR: Int = 40
    const val POLE_STRAIGHT_ARM_OVERHEAD_WHEELCHAIR: Int = 41
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: MutableMap<Int?, String?>

    init {
        stringMap = HashMap<Int?, String?>()
        stringMap.put(_45_DEGREE_CABLE_EXTERNAL_ROTATION, "_45_DEGREE_CABLE_EXTERNAL_ROTATION")
        stringMap.put(
            ALTERNATING_LATERAL_RAISE_WITH_STATIC_HOLD,
            "ALTERNATING_LATERAL_RAISE_WITH_STATIC_HOLD"
        )
        stringMap.put(BAR_MUSCLE_UP, "BAR_MUSCLE_UP")
        stringMap.put(BENT_OVER_LATERAL_RAISE, "BENT_OVER_LATERAL_RAISE")
        stringMap.put(CABLE_DIAGONAL_RAISE, "CABLE_DIAGONAL_RAISE")
        stringMap.put(CABLE_FRONT_RAISE, "CABLE_FRONT_RAISE")
        stringMap.put(CALORIE_ROW, "CALORIE_ROW")
        stringMap.put(COMBO_SHOULDER_RAISE, "COMBO_SHOULDER_RAISE")
        stringMap.put(DUMBBELL_DIAGONAL_RAISE, "DUMBBELL_DIAGONAL_RAISE")
        stringMap.put(DUMBBELL_V_RAISE, "DUMBBELL_V_RAISE")
        stringMap.put(FRONT_RAISE, "FRONT_RAISE")
        stringMap.put(LEANING_DUMBBELL_LATERAL_RAISE, "LEANING_DUMBBELL_LATERAL_RAISE")
        stringMap.put(LYING_DUMBBELL_RAISE, "LYING_DUMBBELL_RAISE")
        stringMap.put(MUSCLE_UP, "MUSCLE_UP")
        stringMap.put(ONE_ARM_CABLE_LATERAL_RAISE, "ONE_ARM_CABLE_LATERAL_RAISE")
        stringMap.put(OVERHAND_GRIP_REAR_LATERAL_RAISE, "OVERHAND_GRIP_REAR_LATERAL_RAISE")
        stringMap.put(PLATE_RAISES, "PLATE_RAISES")
        stringMap.put(RING_DIP, "RING_DIP")
        stringMap.put(WEIGHTED_RING_DIP, "WEIGHTED_RING_DIP")
        stringMap.put(RING_MUSCLE_UP, "RING_MUSCLE_UP")
        stringMap.put(WEIGHTED_RING_MUSCLE_UP, "WEIGHTED_RING_MUSCLE_UP")
        stringMap.put(ROPE_CLIMB, "ROPE_CLIMB")
        stringMap.put(WEIGHTED_ROPE_CLIMB, "WEIGHTED_ROPE_CLIMB")
        stringMap.put(SCAPTION, "SCAPTION")
        stringMap.put(SEATED_LATERAL_RAISE, "SEATED_LATERAL_RAISE")
        stringMap.put(SEATED_REAR_LATERAL_RAISE, "SEATED_REAR_LATERAL_RAISE")
        stringMap.put(SIDE_LYING_LATERAL_RAISE, "SIDE_LYING_LATERAL_RAISE")
        stringMap.put(STANDING_LIFT, "STANDING_LIFT")
        stringMap.put(SUSPENDED_ROW, "SUSPENDED_ROW")
        stringMap.put(UNDERHAND_GRIP_REAR_LATERAL_RAISE, "UNDERHAND_GRIP_REAR_LATERAL_RAISE")
        stringMap.put(WALL_SLIDE, "WALL_SLIDE")
        stringMap.put(WEIGHTED_WALL_SLIDE, "WEIGHTED_WALL_SLIDE")
        stringMap.put(ARM_CIRCLES, "ARM_CIRCLES")
        stringMap.put(SHAVING_THE_HEAD, "SHAVING_THE_HEAD")
        stringMap.put(DUMBBELL_LATERAL_RAISE, "DUMBBELL_LATERAL_RAISE")
        stringMap.put(RING_DIP_KIPPING, "RING_DIP_KIPPING")
        stringMap.put(WALL_WALK, "WALL_WALK")
        stringMap.put(DUMBBELL_FRONT_RAISE_WHEELCHAIR, "DUMBBELL_FRONT_RAISE_WHEELCHAIR")
        stringMap.put(DUMBBELL_LATERAL_RAISE_WHEELCHAIR, "DUMBBELL_LATERAL_RAISE_WHEELCHAIR")
        stringMap.put(
            POLE_DOUBLE_ARM_OVERHEAD_AND_FORWARD_WHEELCHAIR,
            "POLE_DOUBLE_ARM_OVERHEAD_AND_FORWARD_WHEELCHAIR"
        )
        stringMap.put(
            POLE_STRAIGHT_ARM_OVERHEAD_WHEELCHAIR,
            "POLE_STRAIGHT_ARM_OVERHEAD_WHEELCHAIR"
        )
    }


    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum contsant
     */
    fun getStringFromValue(value: Int?): String? {
        if (stringMap.containsKey(value)) {
            return stringMap.get(value)
        }

        return ""
    }

    /**
     * Returns the enum constant with the specified name.
     * @param value The enum string value
     * @return The enum constant or INVALID if unknown
     */
    fun getValueFromString(value: String?): Int? {
        for (entry in stringMap.entries) {
            if (entry.value == value) {
                return entry.key
            }
        }

        return INVALID
    }
}
