/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

object LegRaiseExerciseName {
    const val HANGING_KNEE_RAISE: Int = 0
    const val HANGING_LEG_RAISE: Int = 1
    const val WEIGHTED_HANGING_LEG_RAISE: Int = 2
    const val HANGING_SINGLE_LEG_RAISE: Int = 3
    const val WEIGHTED_HANGING_SINGLE_LEG_RAISE: Int = 4
    const val KETTLEBELL_LEG_RAISES: Int = 5
    const val LEG_LOWERING_DRILL: Int = 6
    const val WEIGHTED_LEG_LOWERING_DRILL: Int = 7
    const val LYING_STRAIGHT_LEG_RAISE: Int = 8
    const val WEIGHTED_LYING_STRAIGHT_LEG_RAISE: Int = 9
    const val MEDICINE_BALL_LEG_DROPS: Int = 10
    const val QUADRUPED_LEG_RAISE: Int = 11
    const val WEIGHTED_QUADRUPED_LEG_RAISE: Int = 12
    const val REVERSE_LEG_RAISE: Int = 13
    const val WEIGHTED_REVERSE_LEG_RAISE: Int = 14
    const val REVERSE_LEG_RAISE_ON_SWISS_BALL: Int = 15
    const val WEIGHTED_REVERSE_LEG_RAISE_ON_SWISS_BALL: Int = 16
    const val SINGLE_LEG_LOWERING_DRILL: Int = 17
    const val WEIGHTED_SINGLE_LEG_LOWERING_DRILL: Int = 18
    const val WEIGHTED_HANGING_KNEE_RAISE: Int = 19
    const val LATERAL_STEPOVER: Int = 20
    const val WEIGHTED_LATERAL_STEPOVER: Int = 21
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: MutableMap<Int?, String?>

    init {
        stringMap = HashMap<Int?, String?>()
        stringMap.put(HANGING_KNEE_RAISE, "HANGING_KNEE_RAISE")
        stringMap.put(HANGING_LEG_RAISE, "HANGING_LEG_RAISE")
        stringMap.put(WEIGHTED_HANGING_LEG_RAISE, "WEIGHTED_HANGING_LEG_RAISE")
        stringMap.put(HANGING_SINGLE_LEG_RAISE, "HANGING_SINGLE_LEG_RAISE")
        stringMap.put(WEIGHTED_HANGING_SINGLE_LEG_RAISE, "WEIGHTED_HANGING_SINGLE_LEG_RAISE")
        stringMap.put(KETTLEBELL_LEG_RAISES, "KETTLEBELL_LEG_RAISES")
        stringMap.put(LEG_LOWERING_DRILL, "LEG_LOWERING_DRILL")
        stringMap.put(WEIGHTED_LEG_LOWERING_DRILL, "WEIGHTED_LEG_LOWERING_DRILL")
        stringMap.put(LYING_STRAIGHT_LEG_RAISE, "LYING_STRAIGHT_LEG_RAISE")
        stringMap.put(WEIGHTED_LYING_STRAIGHT_LEG_RAISE, "WEIGHTED_LYING_STRAIGHT_LEG_RAISE")
        stringMap.put(MEDICINE_BALL_LEG_DROPS, "MEDICINE_BALL_LEG_DROPS")
        stringMap.put(QUADRUPED_LEG_RAISE, "QUADRUPED_LEG_RAISE")
        stringMap.put(WEIGHTED_QUADRUPED_LEG_RAISE, "WEIGHTED_QUADRUPED_LEG_RAISE")
        stringMap.put(REVERSE_LEG_RAISE, "REVERSE_LEG_RAISE")
        stringMap.put(WEIGHTED_REVERSE_LEG_RAISE, "WEIGHTED_REVERSE_LEG_RAISE")
        stringMap.put(REVERSE_LEG_RAISE_ON_SWISS_BALL, "REVERSE_LEG_RAISE_ON_SWISS_BALL")
        stringMap.put(
            WEIGHTED_REVERSE_LEG_RAISE_ON_SWISS_BALL,
            "WEIGHTED_REVERSE_LEG_RAISE_ON_SWISS_BALL"
        )
        stringMap.put(SINGLE_LEG_LOWERING_DRILL, "SINGLE_LEG_LOWERING_DRILL")
        stringMap.put(WEIGHTED_SINGLE_LEG_LOWERING_DRILL, "WEIGHTED_SINGLE_LEG_LOWERING_DRILL")
        stringMap.put(WEIGHTED_HANGING_KNEE_RAISE, "WEIGHTED_HANGING_KNEE_RAISE")
        stringMap.put(LATERAL_STEPOVER, "LATERAL_STEPOVER")
        stringMap.put(WEIGHTED_LATERAL_STEPOVER, "WEIGHTED_LATERAL_STEPOVER")
    }


    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum contsant
     */
    fun getStringFromValue(value: Int?): String? {
        if (stringMap.containsKey(value)) {
            return stringMap.get(value)
        }

        return ""
    }

    /**
     * Returns the enum constant with the specified name.
     * @param value The enum string value
     * @return The enum constant or INVALID if unknown
     */
    fun getValueFromString(value: String?): Int? {
        for (entry in stringMap.entries) {
            if (entry.value == value) {
                return entry.key
            }
        }

        return INVALID
    }
}
