/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

object LocalDeviceType {
    const val GPS: Short = 0 // Onboard gps receiver
    const val GLONASS: Short = 1 // Onboard glonass receiver
    const val GPS_GLONASS: Short = 2 // Onboard gps glonass receiver
    const val ACCELEROMETER: Short = 3 // Onboard sensor
    const val BAROMETER: Short = 4 // Onboard sensor
    const val TEMPERATURE: Short = 5 // Onboard sensor
    const val WHR: Short = 10 // Onboard wrist HR sensor
    const val SENSOR_HUB: Short = 12 // Onboard software package
    val INVALID: Short = Fit.UINT8_INVALID

    private val stringMap: MutableMap<Short?, String?>

    init {
        stringMap = HashMap<Short?, String?>()
        stringMap.put(GPS, "GPS")
        stringMap.put(GLONASS, "GLONASS")
        stringMap.put(GPS_GLONASS, "GPS_GLONASS")
        stringMap.put(ACCELEROMETER, "ACCELEROMETER")
        stringMap.put(BAROMETER, "BAROMETER")
        stringMap.put(TEMPERATURE, "TEMPERATURE")
        stringMap.put(WHR, "WHR")
        stringMap.put(SENSOR_HUB, "SENSOR_HUB")
    }


    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum contsant
     */
    fun getStringFromValue(value: Short?): String? {
        if (stringMap.containsKey(value)) {
            return stringMap.get(value)
        }

        return ""
    }

    /**
     * Returns the enum constant with the specified name.
     * @param value The enum string value
     * @return The enum constant or INVALID if unknown
     */
    fun getValueFromString(value: String?): Short? {
        for (entry in stringMap.entries) {
            if (entry.value == value) {
                return entry.key
            }
        }

        return INVALID
    }
}
