/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

import com.garmin.fit.LocalDateTime.Companion.OFFSET
import java.util.Date

fun LocalDateTime(date: Date) = LocalDateTime((date.time - OFFSET) / 1000)

val LocalDateTime.date: Date get() = Date(timestamp * 1000 + OFFSET)
