/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

import kotlinx.collections.immutable.toImmutableList
import java.io.DataOutputStream
import java.io.IOException
import java.io.OutputStream

open class Mesg {
    // Use a private backing field for constructors to initialize name
    // without calling overridden setters
    private var _name: String? = null
    open var name: String?
        get() = _name
        set(value) {
            _name = value
        }
    var num: Int
    var localNum: Int = 0
        set(localNum) {
            if (localNum >= Fit.MAX_LOCAL_MESGS) {
                throw FitRuntimeException(
                    ("Invalid local message number " + localNum
                            + ".  Local message number must be < " + Fit.MAX_LOCAL_MESGS + ".")
                )
            }

            field = localNum

        }

    @JvmField
    var fields: ArrayList<Field> = ArrayList()
    var developerFields: ArrayList<DeveloperField> = ArrayList()
        internal set
    var systemTimeOffset: Long = 0
    var decoderMesgIndex: Int = 0
        private set

    constructor(mesg: Mesg) {
        this._name = mesg.name
        this.num = mesg.num
        this.localNum = mesg.localNum
        this.systemTimeOffset = mesg.systemTimeOffset
        this.decoderMesgIndex = mesg.decoderMesgIndex

        for (field in mesg.fields) {
            if (field.numValues > 0) {
                this.fields.add(Field(field))
            }
        }

        for (field in mesg.developerFields) {
            if (field.numValues > 0) {
                this.developerFields.add(DeveloperField(field))
            }
        }
    }

    constructor(name: String?, num: Int) {
        this._name = name
        this.num = num
    }

    /**
     * Removes all fields from this message that have been generated through
     * component expansion while decoding the source .FIT file.
     */
    fun removeExpandedFields() {
        val fieldsToRemove = mutableSetOf<Field>()

        for (field in fields) {
            if (field.isExpanded) {
                fieldsToRemove.add(field)
            }
        }

        fields.removeAll(fieldsToRemove)
    }

    @JvmOverloads
    fun write(out: OutputStream, mesgDef: MesgDefinition? = null) {
        var mesgDef = mesgDef
        try {
            val headerByte = localNum and Fit.HDR_TYPE_MASK

            DataOutputStream(out).writeByte(headerByte) // Message record header.
        } catch (e: IOException) {
            throw FitRuntimeException(e)
        }

        if (mesgDef == null) {
            mesgDef = MesgDefinition(this)
        }

        for (fieldDef in mesgDef.fields) {
            var field = this.getField(fieldDef.num)

            if (field == null) {
                field = Factory.createField(num, fieldDef.num)
            }

            field.write(out, fieldDef)
        }

        for (fieldDef in mesgDef.developerFields) {
            var field =
                getDeveloperField(fieldDef.developerDataIndex, fieldDef.num.toInt())

            if (field == null) {
                // Get Default from Definition
                field = fieldDef.defaultField
            }

            field.write(out, fieldDef)
        }
    }

    fun hasField(num: Int): Boolean {
        for (i in fields.indices) {
            if (fields[i].num == num) {
                return true
            }
        }

        return false
    }

    fun addField(field: Field?) {
        fields.add(field!!)
    }

    fun addDeveloperField(field: DeveloperField) {
        for (i in developerFields.indices) {
            val fieldToCompare: DeveloperField = developerFields[i]
            if ((fieldToCompare.num == field.num) &&
                (fieldToCompare.developerDataIndex == field.developerDataIndex)
            ) {
                developerFields[i] = field
                return
            }
        }

        developerFields.add(field)
    }

    fun setField(field: Field) {
        for (i in fields.indices) {
            if (fields[i].num == field.num) {
                fields[i] = field
                return
            }
        }

        fields.add(field)
    }

    val numFields: Int
        get() = fields.size

    private fun getDeveloperField(developerIndex: Short, num: Int): DeveloperField? {
        for (field in developerFields) {
            if ((field.developerDataIndex == developerIndex) &&
                (field.num == num)
            ) {
                return field
            }
        }

        return null
    }

    fun getField(num: Int): Field? {
        for (i in fields.indices) {
            if (fields[i].num == num) {
                return fields[i]
            }
        }

        return null
    }

    fun getField(name: String?): Field? {
        return getField(name, true)
    }

    fun getField(name: String?, checkMesgSupportForSubFields: Boolean): Field? {
        for (i in fields.indices) {
            if (fields[i].name == name) {
                return fields[i]
            }

            for (j in fields[i].subFields.indices) {
                if ((fields[i].subFields[j].name == name) && (!checkMesgSupportForSubFields || (fields[i].subFields[j].canMesgSupport(
                        this
                    )))
                ) {
                    return fields[i]
                }
            }
        }

        return null
    }

    /**
     * Returns the active subfield index of a given field for this message.
     *
     * @param num The field number for the field to be checked
     * @return the subfield index used for the field in this message
     */
    fun getActiveSubFieldIndex(num: Int): Int {
        val testField = Factory.createField(this.num, num)

        for (i in testField.subFields.indices) {
            if (testField.subFields[i].canMesgSupport(this)) {
                return i
            }
        }

        return Fit.SUBFIELD_INDEX_MAIN_FIELD
    }

    /**
     * Returns the active subfield name of a given field for this message.
     *
     * @param num The field number for the field to be checked
     * @return the subfield name used for the field in this message
     */
    fun getActiveSubFieldName(num: Int): String? {
        val testField = Factory.createField(this.num, num)

        for (i in testField.subFields.indices) {
            if (testField.subFields[i].canMesgSupport(this)) {
                return testField.subFields[i].name
            }
        }

        return Fit.SUBFIELD_NAME_MAIN_FIELD
    }

    fun getNumFieldValues(num: Int): Int {
        return getNumFieldValues(num, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getNumFieldValues(num: Int, subFieldIndex: Int): Int {
        val field = getField(num) ?: return 0

        if (subFieldIndex == Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD) {
            return field.numValues
        }

        val subField = field.getSubField(subFieldIndex)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.numValues
        } else {
            0
        }
    }

    fun getNumFieldValues(num: Int, subFieldName: String?): Int {
        val field = getField(num) ?: return 0

        val subField = field.getSubField(subFieldName)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.numValues
        } else {
            0
        }
    }

    fun getNumFieldValues(name: String?): Int {
        val field = getField(name, false) ?: return 0

        val subField = field.getSubField(name)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.numValues
        } else {
            0
        }
    }

    fun getFieldValue(num: Int): Any? {
        return getFieldValue(num, 0, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldValue(num: Int, fieldArrayIndex: Int): Any? {
        return getFieldValue(num, fieldArrayIndex, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldValue(num: Int, fieldArrayIndex: Int, subFieldIndex: Int): Any? {
        val field = getField(num) ?: return null

        return if (subFieldIndex == Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD) {
            field.getValue(fieldArrayIndex, getActiveSubFieldIndex(num))
        } else {
            val subField = field.getSubField(subFieldIndex)

            if ((subField == null) || (subField.canMesgSupport(this))) {
                field.getValue(fieldArrayIndex, subFieldIndex)
            } else {
                null
            }
        }
    }

    fun getFieldValue(num: Int, fieldArrayIndex: Int, subFieldName: String?): Any? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subFieldName)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getValue(fieldArrayIndex, subFieldName)
        } else {
            null
        }
    }

    fun getFieldValue(name: String?): Any? {
        return getFieldValue(name, 0)
    }

    fun getFieldValue(name: String?, fieldArrayIndex: Int): Any? {
        val field = getField(name, false) ?: return null

        val subField = field.getSubField(name)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getValue(fieldArrayIndex, name)
        } else {
            null
        }
    }

    fun getIsFieldAccumulated(num: Int): Boolean {
        val field = getField(num)
        if (field != null) {
            return field.isAccumulated
        }
        return false
    }

    fun setFieldValue(num: Int, value: Any?) {
        setFieldValue(num, 0, value, Fit.SUBFIELD_INDEX_MAIN_FIELD)
    }

    fun setFieldValue(num: Int, fieldArrayIndex: Int, value: Any?) {
        setFieldValue(num, fieldArrayIndex, value, Fit.SUBFIELD_INDEX_MAIN_FIELD)
    }

    fun setFieldValue(num: Int, fieldArrayIndex: Int, value: Any?, subFieldIndex: Int) {
        var subFieldIndex = subFieldIndex
        if (subFieldIndex == Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD) {
            subFieldIndex = getActiveSubFieldIndex(num)
        }

        var field = getField(num)

        if (field == null) {
            field = Factory.createField(this.num, num)
            addField(field)
        }

        field.setValue(fieldArrayIndex, value, subFieldIndex)
    }

    fun setFieldValue(num: Int, fieldArrayIndex: Int, value: Any?, subFieldName: String?) {
        var field = getField(num)

        if (field == null) {
            field = Factory.createField(this.num, num)
            addField(field)
        }

        field.setValue(fieldArrayIndex, value, subFieldName)
    }

    fun setFieldValue(name: String?, value: Any?) {
        setFieldValue(name, 0, value)
    }

    fun setFieldValue(name: String?, fieldArrayIndex: Int, value: Any?) {
        var field = getField(name, false)

        if (field == null) {
            field = Factory.createField(this.num, name)
            addField(field)
        }

        field.setValue(fieldArrayIndex, value, name)
    }

    fun getFieldBitsValue(num: Int, offset: Int, bits: Int, signed: Boolean): Long? {
        val field = getField(num) ?: return null

        return field.getBitsValue(offset, bits, signed)
    }

    fun getFieldBitsValue(name: String?, offset: Int, bits: Int, signed: Boolean): Long? {
        val field = getField(name, false) ?: return null

        val subField = field.getSubField(name)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getBitsValue(offset, bits, signed)
        } else {
            null
        }
    }

    fun getFieldByteValues(num: Int): Array<Byte>? {
        return getFieldByteValues(num, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldByteValues(num: Int, subfieldIndex: Int): Array<Byte>? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subfieldIndex)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getByteValues(subfieldIndex)
        } else {
            null
        }
    }

    fun getFieldByteValues(num: Int, subfieldName: String): Array<Byte>? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subfieldName)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getByteValues(subfieldName)
        } else {
            null
        }
    }

    fun getFieldByteValue(num: Int): Byte? {
        return getFieldByteValue(num, 0, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldByteValue(num: Int, fieldArrayIndex: Int): Byte? {
        return getFieldByteValue(num, fieldArrayIndex, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldByteValue(num: Int, fieldArrayIndex: Int, subFieldIndex: Int): Byte? {
        val field = getField(num) ?: return null

        return if (subFieldIndex == Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD) {
            field.getByteValue(fieldArrayIndex, getActiveSubFieldIndex(num))
        } else {
            val subField = field.getSubField(subFieldIndex)

            if ((subField == null) || (subField.canMesgSupport(this))) {
                field.getByteValue(fieldArrayIndex, subFieldIndex)
            } else {
                null
            }
        }
    }

    fun getFieldByteValue(num: Int, fieldArrayIndex: Int, subFieldName: String?): Byte? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subFieldName)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getByteValue(fieldArrayIndex, subFieldName)
        } else {
            null
        }
    }

    fun getFieldByteValue(name: String?): Byte? {
        return getFieldByteValue(name, 0)
    }

    fun getFieldByteValue(name: String?, fieldArrayIndex: Int): Byte? {
        val field = getField(name, false) ?: return null

        val subField = field.getSubField(name)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getByteValue(fieldArrayIndex, name)
        } else {
            null
        }
    }

    fun getFieldShortValues(num: Int): Array<Short>? {
        return getFieldShortValues(num, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldShortValues(num: Int, subfieldIndex: Int): Array<Short>? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subfieldIndex)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getShortValues(subfieldIndex).filterNotNull().toTypedArray()
        } else {
            null
        }
    }

    fun getFieldShortValues(num: Int, subfieldName: String?): Array<Short>? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subfieldName)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getShortValues(subfieldName)
        } else {
            null
        }
    }

    fun getFieldShortValue(num: Int): Short? {
        return getFieldShortValue(num, 0, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldShortValue(num: Int, fieldArrayIndex: Int): Short? {
        return getFieldShortValue(num, fieldArrayIndex, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldShortValue(num: Int, fieldArrayIndex: Int, subFieldIndex: Int): Short? {
        val field = getField(num) ?: return null

        return if (subFieldIndex == Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD) {
            field.getShortValue(fieldArrayIndex, getActiveSubFieldIndex(num))
        } else {
            val subField = field.getSubField(subFieldIndex)

            if ((subField == null) || (subField.canMesgSupport(this))) {
                field.getShortValue(fieldArrayIndex, subFieldIndex)
            } else {
                null
            }
        }
    }

    fun getFieldShortValue(num: Int, fieldArrayIndex: Int, subFieldName: String?): Short? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subFieldName)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getShortValue(fieldArrayIndex, subFieldName)
        } else {
            null
        }
    }

    fun getFieldShortValue(name: String?): Short? {
        return getFieldShortValue(name, 0)
    }

    fun getFieldShortValue(name: String?, fieldArrayIndex: Int): Short? {
        val field = getField(name, false) ?: return null

        val subField = field.getSubField(name)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getShortValue(fieldArrayIndex, name)
        } else {
            null
        }
    }

    fun getFieldIntegerValues(num: Int): Array<Int>? {
        return getFieldIntegerValues(num, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldIntegerValues(num: Int, subfieldIndex: Int): Array<Int>? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subfieldIndex)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getIntegerValues(subfieldIndex)
        } else {
            null
        }
    }

    fun getFieldIntegerValues(num: Int, subfieldName: String?): Array<Int>? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subfieldName)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getIntegerValues(subfieldName)
        } else {
            null
        }
    }

    fun getFieldIntegerValue(num: Int): Int? {
        return getFieldIntegerValue(num, 0, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldIntegerValue(num: Int, fieldArrayIndex: Int): Int? {
        return getFieldIntegerValue(num, fieldArrayIndex, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldIntegerValue(num: Int, fieldArrayIndex: Int, subFieldIndex: Int): Int? {
        val field = getField(num) ?: return null

        return if (subFieldIndex == Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD) {
            field.getIntegerValue(fieldArrayIndex, getActiveSubFieldIndex(num))
        } else {
            val subField = field.getSubField(subFieldIndex)

            if ((subField == null) || (subField.canMesgSupport(this))) {
                field.getIntegerValue(fieldArrayIndex, subFieldIndex)
            } else {
                null
            }
        }
    }

    fun getFieldIntegerValue(num: Int, fieldArrayIndex: Int, subFieldName: String?): Int? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subFieldName)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getIntegerValue(fieldArrayIndex, subFieldName)
        } else {
            null
        }
    }

    fun getFieldIntegerValue(name: String?): Int? {
        return getFieldIntegerValue(name, 0)
    }

    fun getFieldIntegerValue(name: String?, fieldArrayIndex: Int): Int? {
        val field = getField(name, false) ?: return null

        val subField = field.getSubField(name)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getIntegerValue(fieldArrayIndex, name)
        } else {
            null
        }
    }

    fun getFieldLongValues(num: Int): Array<Long>? {
        return getFieldLongValues(num, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldLongValues(num: Int, subfieldIndex: Int): Array<Long>? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subfieldIndex)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getLongValues(subfieldIndex)
        } else {
            null
        }
    }

    fun getFieldLongValues(num: Int, subfieldName: String?): Array<Long>? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subfieldName)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getLongValues(subfieldName)
        } else {
            null
        }
    }

    fun getFieldLongValue(num: Int): Long? {
        return getFieldLongValue(num, 0, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldLongValue(num: Int, fieldArrayIndex: Int): Long? {
        return getFieldLongValue(num, fieldArrayIndex, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldLongValue(num: Int, fieldArrayIndex: Int, subFieldIndex: Int): Long? {
        val field = getField(num) ?: return null

        return if (subFieldIndex == Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD) {
            field.getLongValue(fieldArrayIndex, getActiveSubFieldIndex(num))
        } else {
            val subField = field.getSubField(subFieldIndex)

            if ((subField == null) || (subField.canMesgSupport(this))) {
                field.getLongValue(fieldArrayIndex, subFieldIndex)
            } else {
                null
            }
        }
    }

    fun getFieldLongValue(num: Int, fieldArrayIndex: Int, subFieldName: String?): Long? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subFieldName)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getLongValue(fieldArrayIndex, subFieldName)
        } else {
            null
        }
    }

    fun getFieldLongValue(name: String?): Long? {
        return getFieldLongValue(name, 0)
    }

    fun getFieldLongValue(name: String?, fieldArrayIndex: Int): Long? {
        val field = getField(name, false) ?: return null

        val subField = field.getSubField(name)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getLongValue(fieldArrayIndex, name)
        } else {
            null
        }
    }

    fun getFieldFloatValues(num: Int): Array<Float>? {
        return getFieldFloatValues(num, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldFloatValues(num: Int, subfieldIndex: Int): Array<Float>? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subfieldIndex)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getFloatValues(subfieldIndex)
        } else {
            null
        }
    }

    fun getFieldFloatValues(num: Int, subfieldName: String?): Array<Float>? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subfieldName)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getFloatValues(subfieldName)
        } else {
            null
        }
    }

    fun getFieldFloatValue(num: Int): Float? {
        return getFieldFloatValue(num, 0, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldFloatValue(num: Int, fieldArrayIndex: Int): Float? {
        return getFieldFloatValue(num, fieldArrayIndex, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldFloatValue(num: Int, fieldArrayIndex: Int, subFieldIndex: Int): Float? {
        val field = getField(num) ?: return null

        return if (subFieldIndex == Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD) {
            field.getFloatValue(fieldArrayIndex, getActiveSubFieldIndex(num))
        } else {
            val subField = field.getSubField(subFieldIndex)

            if ((subField == null) || (subField.canMesgSupport(this))) {
                field.getFloatValue(fieldArrayIndex, subFieldIndex)
            } else {
                null
            }
        }
    }

    fun getFieldFloatValue(num: Int, fieldArrayIndex: Int, subFieldName: String?): Float? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subFieldName)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getFloatValue(fieldArrayIndex, subFieldName)
        } else {
            null
        }
    }

    fun getFieldFloatValue(name: String?): Float? {
        return getFieldFloatValue(name, 0)
    }

    fun getFieldFloatValue(name: String?, fieldArrayIndex: Int): Float? {
        val field = getField(name, false) ?: return null

        val subField = field.getSubField(name)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getFloatValue(fieldArrayIndex, name)
        } else {
            null
        }
    }

    fun getFieldDoubleValues(num: Int): Array<Double>? {
        return getFieldDoubleValues(num, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldDoubleValues(num: Int, subfieldIndex: Int): Array<Double>? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subfieldIndex)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getDoubleValues(subfieldIndex)
        } else {
            null
        }
    }

    fun getFieldDoubleValues(num: Int, subfieldName: String?): Array<Double>? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subfieldName)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getDoubleValues(subfieldName)
        } else {
            null
        }
    }

    fun getFieldDoubleValue(num: Int): Double? {
        return getFieldDoubleValue(num, 0, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldDoubleValue(num: Int, fieldArrayIndex: Int): Double? {
        return getFieldDoubleValue(num, fieldArrayIndex, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldDoubleValue(num: Int, fieldArrayIndex: Int, subFieldIndex: Int): Double? {
        val field = getField(num) ?: return null

        return if (subFieldIndex == Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD) {
            field.getDoubleValue(fieldArrayIndex, getActiveSubFieldIndex(num))
        } else {
            val subField = field.getSubField(subFieldIndex)

            if ((subField == null) || (subField.canMesgSupport(this))) {
                field.getDoubleValue(fieldArrayIndex, subFieldIndex)
            } else {
                null
            }
        }
    }

    fun getFieldDoubleValue(num: Int, fieldArrayIndex: Int, subFieldName: String?): Double? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subFieldName)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getDoubleValue(fieldArrayIndex, subFieldName)
        } else {
            null
        }
    }

    fun getFieldDoubleValue(name: String?): Double? {
        return getFieldDoubleValue(name, 0)
    }

    fun getFieldDoubleValue(name: String?, fieldArrayIndex: Int): Double? {
        val field = getField(name, false) ?: return null

        val subField = field.getSubField(name)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getDoubleValue(fieldArrayIndex, name)
        } else {
            null
        }
    }

    fun getFieldStringValues(num: Int): Array<String?>? {
        return getFieldStringValues(num, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldStringValues(num: Int, subfieldIndex: Int): Array<String?>? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subfieldIndex)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getStringValues(subfieldIndex)
        } else {
            null
        }
    }

    fun getFieldStringValues(num: Int, subfieldName: String?): Array<String?>? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subfieldName)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getStringValues(subfieldName)
        } else {
            null
        }
    }

    fun getFieldStringValue(num: Int): String? {
        return getFieldStringValue(num, 0, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldStringValue(num: Int, fieldArrayIndex: Int): String? {
        return getFieldStringValue(num, fieldArrayIndex, Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD)
    }

    fun getFieldStringValue(num: Int, fieldArrayIndex: Int, subFieldIndex: Int): String? {
        val field = getField(num) ?: return null

        return if (subFieldIndex == Fit.SUBFIELD_INDEX_ACTIVE_SUBFIELD) {
            field.getStringValue(fieldArrayIndex, getActiveSubFieldIndex(num))
        } else {
            val subField = field.getSubField(subFieldIndex)

            if ((subField == null) || (subField.canMesgSupport(this))) {
                field.getStringValue(fieldArrayIndex, subFieldIndex)
            } else {
                null
            }
        }
    }

    fun getFieldStringValue(num: Int, fieldArrayIndex: Int, subFieldName: String?): String? {
        val field = getField(num) ?: return null

        val subField = field.getSubField(subFieldName)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getStringValue(fieldArrayIndex, subFieldName)
        } else {
            null
        }
    }

    fun getFieldStringValue(name: String?): String? {
        return getFieldStringValue(name, 0)
    }

    fun getFieldStringValue(name: String?, fieldArrayIndex: Int): String? {
        val field = getField(name, false) ?: return null

        val subField = field.getSubField(name)

        return if ((subField == null) || (subField.canMesgSupport(this))) {
            field.getStringValue(fieldArrayIndex, name)
        } else {
            null
        }
    }

    fun getFields(): List<Field> = fields.toImmutableList()

    fun setFields(mesg: Mesg) {
        if (mesg.num != num) {
            return
        }

        for (field in mesg.fields) {
            setField(field)
        }
    }

    fun timestampToDateTime(timestamp: Long?): DateTime? {

        if (timestamp == null) {
            return null
        }

        val dateTime = DateTime(timestamp)
        dateTime.convertSystemTimeToUTC(systemTimeOffset)

        return dateTime
    }

    fun setDecoderMessageIndex(decoderMesgIndex: Int) {
        this.decoderMesgIndex = decoderMesgIndex
    }

    fun removeField(f: Field?): Boolean {
        var removedItem = false
        if (this.fields.contains(f)) {
            this.fields.remove(f)
            removedItem = true
        }
        return removedItem
    }

    /**
     * Retrieve all fields that are equivalent to the requested field number
     *
     * @param fieldNum The Field Number from the Profile that we are looking for
     * @return [Iterable] of [FieldBase]s that are equivalent to the
     * field number provided
     */
    fun getOverrideField(fieldNum: Short): Iterable<FieldBase> = buildList {
        getField(fieldNum.toInt())
            ?.let { add(it) }

        developerFields
            .filter { it.nativeOverride == fieldNum }
            .forEach { add(it) }
    }

    override fun toString() = "Mesg(" +
            "name=$name, " +
            "num=$num, " +
            "localNum=$localNum, " +
            "numFields=$numFields, " +
            "fields=$fields, " +
            "developerFields=$developerFields" +
            ")"
}
