/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

object MesgNum {
    const val FILE_ID: Int = 0
    const val CAPABILITIES: Int = 1
    const val DEVICE_SETTINGS: Int = 2
    const val USER_PROFILE: Int = 3
    const val HRM_PROFILE: Int = 4
    const val SDM_PROFILE: Int = 5
    const val BIKE_PROFILE: Int = 6
    const val ZONES_TARGET: Int = 7
    const val HR_ZONE: Int = 8
    const val POWER_ZONE: Int = 9
    const val MET_ZONE: Int = 10
    const val SPORT: Int = 12
    const val TRAINING_SETTINGS: Int = 13
    const val GOAL: Int = 15
    const val SESSION: Int = 18
    const val LAP: Int = 19
    const val RECORD: Int = 20
    const val EVENT: Int = 21
    const val DEVICE_INFO: Int = 23
    const val WORKOUT: Int = 26
    const val WORKOUT_STEP: Int = 27
    const val SCHEDULE: Int = 28
    const val WEIGHT_SCALE: Int = 30
    const val COURSE: Int = 31
    const val COURSE_POINT: Int = 32
    const val TOTALS: Int = 33
    const val ACTIVITY: Int = 34
    const val SOFTWARE: Int = 35
    const val FILE_CAPABILITIES: Int = 37
    const val MESG_CAPABILITIES: Int = 38
    const val FIELD_CAPABILITIES: Int = 39
    const val FILE_CREATOR: Int = 49
    const val BLOOD_PRESSURE: Int = 51
    const val SPEED_ZONE: Int = 53
    const val MONITORING: Int = 55
    const val TRAINING_FILE: Int = 72
    const val HRV: Int = 78
    const val ANT_RX: Int = 80
    const val ANT_TX: Int = 81
    const val ANT_CHANNEL_ID: Int = 82
    const val LENGTH: Int = 101
    const val MONITORING_INFO: Int = 103
    const val PAD: Int = 105
    const val SLAVE_DEVICE: Int = 106
    const val CONNECTIVITY: Int = 127
    const val WEATHER_CONDITIONS: Int = 128
    const val WEATHER_ALERT: Int = 129
    const val CADENCE_ZONE: Int = 131
    const val HR: Int = 132
    const val SEGMENT_LAP: Int = 142
    const val MEMO_GLOB: Int = 145
    const val SEGMENT_ID: Int = 148
    const val SEGMENT_LEADERBOARD_ENTRY: Int = 149
    const val SEGMENT_POINT: Int = 150
    const val SEGMENT_FILE: Int = 151
    const val WORKOUT_SESSION: Int = 158
    const val WATCHFACE_SETTINGS: Int = 159
    const val GPS_METADATA: Int = 160
    const val CAMERA_EVENT: Int = 161
    const val TIMESTAMP_CORRELATION: Int = 162
    const val GYROSCOPE_DATA: Int = 164
    const val ACCELEROMETER_DATA: Int = 165
    const val THREE_D_SENSOR_CALIBRATION: Int = 167
    const val VIDEO_FRAME: Int = 169
    const val OBDII_DATA: Int = 174
    const val NMEA_SENTENCE: Int = 177
    const val AVIATION_ATTITUDE: Int = 178
    const val VIDEO: Int = 184
    const val VIDEO_TITLE: Int = 185
    const val VIDEO_DESCRIPTION: Int = 186
    const val VIDEO_CLIP: Int = 187
    const val OHR_SETTINGS: Int = 188
    const val EXD_SCREEN_CONFIGURATION: Int = 200
    const val EXD_DATA_FIELD_CONFIGURATION: Int = 201
    const val EXD_DATA_CONCEPT_CONFIGURATION: Int = 202
    const val FIELD_DESCRIPTION: Int = 206
    const val DEVELOPER_DATA_ID: Int = 207
    const val MAGNETOMETER_DATA: Int = 208
    const val BAROMETER_DATA: Int = 209
    const val ONE_D_SENSOR_CALIBRATION: Int = 210
    const val MONITORING_HR_DATA: Int = 211
    const val TIME_IN_ZONE: Int = 216
    const val SET: Int = 225
    const val STRESS_LEVEL: Int = 227
    const val MAX_MET_DATA: Int = 229
    const val DIVE_SETTINGS: Int = 258
    const val DIVE_GAS: Int = 259
    const val DIVE_ALARM: Int = 262
    const val EXERCISE_TITLE: Int = 264
    const val DIVE_SUMMARY: Int = 268
    const val SPO2_DATA: Int = 269
    const val SLEEP_LEVEL: Int = 275
    const val JUMP: Int = 285
    const val AAD_ACCEL_FEATURES: Int = 289
    const val BEAT_INTERVALS: Int = 290
    const val RESPIRATION_RATE: Int = 297
    const val HSA_ACCELEROMETER_DATA: Int = 302
    const val HSA_STEP_DATA: Int = 304
    const val HSA_SPO2_DATA: Int = 305
    const val HSA_STRESS_DATA: Int = 306
    const val HSA_RESPIRATION_DATA: Int = 307
    const val HSA_HEART_RATE_DATA: Int = 308
    const val SPLIT: Int = 312
    const val SPLIT_SUMMARY: Int = 313
    const val HSA_BODY_BATTERY_DATA: Int = 314
    const val HSA_EVENT: Int = 315
    const val CLIMB_PRO: Int = 317
    const val TANK_UPDATE: Int = 319
    const val TANK_SUMMARY: Int = 323
    const val SLEEP_ASSESSMENT: Int = 346
    const val HRV_STATUS_SUMMARY: Int = 370
    const val HRV_VALUE: Int = 371
    const val RAW_BBI: Int = 372
    const val DEVICE_AUX_BATTERY_INFO: Int = 375
    const val HSA_GYROSCOPE_DATA: Int = 376
    const val CHRONO_SHOT_SESSION: Int = 387
    const val CHRONO_SHOT_DATA: Int = 388
    const val HSA_CONFIGURATION_DATA: Int = 389
    const val DIVE_APNEA_ALARM: Int = 393
    const val SKIN_TEMP_OVERNIGHT: Int = 398
    const val HSA_WRIST_TEMPERATURE_DATA: Int =
        409 // Message number for the HSA wrist temperature data message
    const val NAP_EVENT: Int = 412
    const val SLEEP_DISRUPTION_SEVERITY_PERIOD: Int = 470
    const val SLEEP_DISRUPTION_OVERNIGHT_SEVERITY: Int = 471
    const val MFG_RANGE_MIN: Int =
        0xFF00 // 0xFF00 - 0xFFFE reserved for manufacturer specific messages
    const val MFG_RANGE_MAX: Int =
        0xFFFE // 0xFF00 - 0xFFFE reserved for manufacturer specific messages
    @JvmField
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: MutableMap<Int?, String?>

    init {
        stringMap = HashMap<Int?, String?>()
        stringMap.put(FILE_ID, "FILE_ID")
        stringMap.put(CAPABILITIES, "CAPABILITIES")
        stringMap.put(DEVICE_SETTINGS, "DEVICE_SETTINGS")
        stringMap.put(USER_PROFILE, "USER_PROFILE")
        stringMap.put(HRM_PROFILE, "HRM_PROFILE")
        stringMap.put(SDM_PROFILE, "SDM_PROFILE")
        stringMap.put(BIKE_PROFILE, "BIKE_PROFILE")
        stringMap.put(ZONES_TARGET, "ZONES_TARGET")
        stringMap.put(HR_ZONE, "HR_ZONE")
        stringMap.put(POWER_ZONE, "POWER_ZONE")
        stringMap.put(MET_ZONE, "MET_ZONE")
        stringMap.put(SPORT, "SPORT")
        stringMap.put(TRAINING_SETTINGS, "TRAINING_SETTINGS")
        stringMap.put(GOAL, "GOAL")
        stringMap.put(SESSION, "SESSION")
        stringMap.put(LAP, "LAP")
        stringMap.put(RECORD, "RECORD")
        stringMap.put(EVENT, "EVENT")
        stringMap.put(DEVICE_INFO, "DEVICE_INFO")
        stringMap.put(WORKOUT, "WORKOUT")
        stringMap.put(WORKOUT_STEP, "WORKOUT_STEP")
        stringMap.put(SCHEDULE, "SCHEDULE")
        stringMap.put(WEIGHT_SCALE, "WEIGHT_SCALE")
        stringMap.put(COURSE, "COURSE")
        stringMap.put(COURSE_POINT, "COURSE_POINT")
        stringMap.put(TOTALS, "TOTALS")
        stringMap.put(ACTIVITY, "ACTIVITY")
        stringMap.put(SOFTWARE, "SOFTWARE")
        stringMap.put(FILE_CAPABILITIES, "FILE_CAPABILITIES")
        stringMap.put(MESG_CAPABILITIES, "MESG_CAPABILITIES")
        stringMap.put(FIELD_CAPABILITIES, "FIELD_CAPABILITIES")
        stringMap.put(FILE_CREATOR, "FILE_CREATOR")
        stringMap.put(BLOOD_PRESSURE, "BLOOD_PRESSURE")
        stringMap.put(SPEED_ZONE, "SPEED_ZONE")
        stringMap.put(MONITORING, "MONITORING")
        stringMap.put(TRAINING_FILE, "TRAINING_FILE")
        stringMap.put(HRV, "HRV")
        stringMap.put(ANT_RX, "ANT_RX")
        stringMap.put(ANT_TX, "ANT_TX")
        stringMap.put(ANT_CHANNEL_ID, "ANT_CHANNEL_ID")
        stringMap.put(LENGTH, "LENGTH")
        stringMap.put(MONITORING_INFO, "MONITORING_INFO")
        stringMap.put(PAD, "PAD")
        stringMap.put(SLAVE_DEVICE, "SLAVE_DEVICE")
        stringMap.put(CONNECTIVITY, "CONNECTIVITY")
        stringMap.put(WEATHER_CONDITIONS, "WEATHER_CONDITIONS")
        stringMap.put(WEATHER_ALERT, "WEATHER_ALERT")
        stringMap.put(CADENCE_ZONE, "CADENCE_ZONE")
        stringMap.put(HR, "HR")
        stringMap.put(SEGMENT_LAP, "SEGMENT_LAP")
        stringMap.put(MEMO_GLOB, "MEMO_GLOB")
        stringMap.put(SEGMENT_ID, "SEGMENT_ID")
        stringMap.put(SEGMENT_LEADERBOARD_ENTRY, "SEGMENT_LEADERBOARD_ENTRY")
        stringMap.put(SEGMENT_POINT, "SEGMENT_POINT")
        stringMap.put(SEGMENT_FILE, "SEGMENT_FILE")
        stringMap.put(WORKOUT_SESSION, "WORKOUT_SESSION")
        stringMap.put(WATCHFACE_SETTINGS, "WATCHFACE_SETTINGS")
        stringMap.put(GPS_METADATA, "GPS_METADATA")
        stringMap.put(CAMERA_EVENT, "CAMERA_EVENT")
        stringMap.put(TIMESTAMP_CORRELATION, "TIMESTAMP_CORRELATION")
        stringMap.put(GYROSCOPE_DATA, "GYROSCOPE_DATA")
        stringMap.put(ACCELEROMETER_DATA, "ACCELEROMETER_DATA")
        stringMap.put(THREE_D_SENSOR_CALIBRATION, "THREE_D_SENSOR_CALIBRATION")
        stringMap.put(VIDEO_FRAME, "VIDEO_FRAME")
        stringMap.put(OBDII_DATA, "OBDII_DATA")
        stringMap.put(NMEA_SENTENCE, "NMEA_SENTENCE")
        stringMap.put(AVIATION_ATTITUDE, "AVIATION_ATTITUDE")
        stringMap.put(VIDEO, "VIDEO")
        stringMap.put(VIDEO_TITLE, "VIDEO_TITLE")
        stringMap.put(VIDEO_DESCRIPTION, "VIDEO_DESCRIPTION")
        stringMap.put(VIDEO_CLIP, "VIDEO_CLIP")
        stringMap.put(OHR_SETTINGS, "OHR_SETTINGS")
        stringMap.put(EXD_SCREEN_CONFIGURATION, "EXD_SCREEN_CONFIGURATION")
        stringMap.put(EXD_DATA_FIELD_CONFIGURATION, "EXD_DATA_FIELD_CONFIGURATION")
        stringMap.put(EXD_DATA_CONCEPT_CONFIGURATION, "EXD_DATA_CONCEPT_CONFIGURATION")
        stringMap.put(FIELD_DESCRIPTION, "FIELD_DESCRIPTION")
        stringMap.put(DEVELOPER_DATA_ID, "DEVELOPER_DATA_ID")
        stringMap.put(MAGNETOMETER_DATA, "MAGNETOMETER_DATA")
        stringMap.put(BAROMETER_DATA, "BAROMETER_DATA")
        stringMap.put(ONE_D_SENSOR_CALIBRATION, "ONE_D_SENSOR_CALIBRATION")
        stringMap.put(MONITORING_HR_DATA, "MONITORING_HR_DATA")
        stringMap.put(TIME_IN_ZONE, "TIME_IN_ZONE")
        stringMap.put(SET, "SET")
        stringMap.put(STRESS_LEVEL, "STRESS_LEVEL")
        stringMap.put(MAX_MET_DATA, "MAX_MET_DATA")
        stringMap.put(DIVE_SETTINGS, "DIVE_SETTINGS")
        stringMap.put(DIVE_GAS, "DIVE_GAS")
        stringMap.put(DIVE_ALARM, "DIVE_ALARM")
        stringMap.put(EXERCISE_TITLE, "EXERCISE_TITLE")
        stringMap.put(DIVE_SUMMARY, "DIVE_SUMMARY")
        stringMap.put(SPO2_DATA, "SPO2_DATA")
        stringMap.put(SLEEP_LEVEL, "SLEEP_LEVEL")
        stringMap.put(JUMP, "JUMP")
        stringMap.put(AAD_ACCEL_FEATURES, "AAD_ACCEL_FEATURES")
        stringMap.put(BEAT_INTERVALS, "BEAT_INTERVALS")
        stringMap.put(RESPIRATION_RATE, "RESPIRATION_RATE")
        stringMap.put(HSA_ACCELEROMETER_DATA, "HSA_ACCELEROMETER_DATA")
        stringMap.put(HSA_STEP_DATA, "HSA_STEP_DATA")
        stringMap.put(HSA_SPO2_DATA, "HSA_SPO2_DATA")
        stringMap.put(HSA_STRESS_DATA, "HSA_STRESS_DATA")
        stringMap.put(HSA_RESPIRATION_DATA, "HSA_RESPIRATION_DATA")
        stringMap.put(HSA_HEART_RATE_DATA, "HSA_HEART_RATE_DATA")
        stringMap.put(SPLIT, "SPLIT")
        stringMap.put(SPLIT_SUMMARY, "SPLIT_SUMMARY")
        stringMap.put(HSA_BODY_BATTERY_DATA, "HSA_BODY_BATTERY_DATA")
        stringMap.put(HSA_EVENT, "HSA_EVENT")
        stringMap.put(CLIMB_PRO, "CLIMB_PRO")
        stringMap.put(TANK_UPDATE, "TANK_UPDATE")
        stringMap.put(TANK_SUMMARY, "TANK_SUMMARY")
        stringMap.put(SLEEP_ASSESSMENT, "SLEEP_ASSESSMENT")
        stringMap.put(HRV_STATUS_SUMMARY, "HRV_STATUS_SUMMARY")
        stringMap.put(HRV_VALUE, "HRV_VALUE")
        stringMap.put(RAW_BBI, "RAW_BBI")
        stringMap.put(DEVICE_AUX_BATTERY_INFO, "DEVICE_AUX_BATTERY_INFO")
        stringMap.put(HSA_GYROSCOPE_DATA, "HSA_GYROSCOPE_DATA")
        stringMap.put(CHRONO_SHOT_SESSION, "CHRONO_SHOT_SESSION")
        stringMap.put(CHRONO_SHOT_DATA, "CHRONO_SHOT_DATA")
        stringMap.put(HSA_CONFIGURATION_DATA, "HSA_CONFIGURATION_DATA")
        stringMap.put(DIVE_APNEA_ALARM, "DIVE_APNEA_ALARM")
        stringMap.put(SKIN_TEMP_OVERNIGHT, "SKIN_TEMP_OVERNIGHT")
        stringMap.put(HSA_WRIST_TEMPERATURE_DATA, "HSA_WRIST_TEMPERATURE_DATA")
        stringMap.put(NAP_EVENT, "NAP_EVENT")
        stringMap.put(SLEEP_DISRUPTION_SEVERITY_PERIOD, "SLEEP_DISRUPTION_SEVERITY_PERIOD")
        stringMap.put(SLEEP_DISRUPTION_OVERNIGHT_SEVERITY, "SLEEP_DISRUPTION_OVERNIGHT_SEVERITY")
        stringMap.put(MFG_RANGE_MIN, "MFG_RANGE_MIN")
        stringMap.put(MFG_RANGE_MAX, "MFG_RANGE_MAX")
    }


    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum contsant
     */
    fun getStringFromValue(value: Int?): String? {
        if (stringMap.containsKey(value)) {
            return stringMap.get(value)
        }

        return ""
    }

    /**
     * Returns the enum constant with the specified name.
     * @param value The enum string value
     * @return The enum constant or INVALID if unknown
     */
    fun getValueFromString(value: String?): Int? {
        for (entry in stringMap.entries) {
            if (entry.value == value) {
                return entry.key
            }
        }

        return INVALID
    }
}
