/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


class MesgWithEventBroadcaster : MesgWithEventListener {
    private val listeners = mutableListOf<MesgWithEventListener>()
    private val startedEvents = Array(MAX_GROUPS) { mutableListOf<MesgWithEvent>() }

    fun addListener(mesgObserver: MesgWithEventListener) {
        listeners.add(mesgObserver)
    }

    fun removeListener(mesgObserver: MesgWithEventListener) {
        listeners.remove(mesgObserver)
    }

    override fun onMesg(message: MesgWithEvent) {
        // 1. Prepare a copy for broadcasting and normalization
        val broadcastMesg = Factory.createMesg(message as Mesg) as MesgWithEvent
        if (broadcastMesg.eventType == null) return

        // 2. Handle legacy types and determine the active group
        val group = broadcastMesg.normalizeLegacyTypes()
        val activeEvents = startedEvents[group]

        // 3. Process the event state machine
        when (broadcastMesg.eventType) {
            EventType.START -> {
                // Insert STOP before START events if already started with the same ID
                activeEvents.removeAll { startedEvent ->
                    (startedEvent.event == broadcastMesg.event)
                        .also { isMatch ->
                            if (isMatch) broadcastStop(
                                startedEvent,
                                broadcastMesg.timestamp,
                                EventType.STOP
                            )
                        }
                }
                // Track the new event
                activeEvents.add(Factory.createMesg(broadcastMesg as Mesg) as MesgWithEvent)
            }

            EventType.STOP, EventType.STOP_DISABLE -> {
                activeEvents.removeAll { it.event == broadcastMesg.event }
            }

            EventType.STOP_ALL, EventType.STOP_DISABLE_ALL -> {
                val stopType =
                    if (broadcastMesg.eventType == EventType.STOP_ALL)
                        EventType.STOP
                    else
                        EventType.STOP_DISABLE

                // Broadcast STOP for all other tracked events in this group
                activeEvents.forEach { startedEvent ->
                    if (startedEvent.event != broadcastMesg.event)
                        broadcastStop(
                            startedEvent,
                            broadcastMesg.timestamp,
                            stopType
                        )

                }
                activeEvents.clear()

                // The STOP_ALL message itself becomes a simple STOP/DISABLE for the current event
                broadcastMesg.eventType = stopType
            }

            else -> {}
        }

        // 4. Final broadcast of the processed message
        broadcast(broadcastMesg)
    }

    private fun MesgWithEvent.normalizeLegacyTypes(): Int {
        var group = eventGroup?.toInt() ?: DEFAULT_GROUP
        when (eventType) {
            EventType.BEGIN_DEPRECIATED -> {
                group = BEGIN_END_GROUP
                eventType = EventType.START
            }

            EventType.END_DEPRECIATED -> {
                group = BEGIN_END_GROUP
                eventType = EventType.STOP
            }

            EventType.CONSECUTIVE_DEPRECIATED -> {
                eventType = EventType.STOP
            }

            EventType.END_ALL_DEPRECIATED -> {
                group = BEGIN_END_GROUP
                eventType = EventType.STOP_ALL
            }

            else -> {}
        }
        return group
    }

    private fun broadcastStop(
        startedEvent: MesgWithEvent,
        timestamp: DateTime?,
        stopType: EventType
    ) {
        val stopEvent = Factory.createMesg(startedEvent as Mesg) as MesgWithEvent
        stopEvent.eventType = stopType
        timestamp?.let { stopEvent.timestamp = it }
        broadcast(stopEvent)
    }

    private fun broadcast(mesg: MesgWithEvent) {
        listeners.forEach { it.onMesg(mesg) }
    }

    private companion object {
        const val MAX_GROUPS = 256
        const val DEFAULT_GROUP = 255
        const val BEGIN_END_GROUP = 254
    }
}
