/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

import com.garmin.fit.Profile.SubFields


class MonitoringMesg : Mesg {
    constructor() : super(Factory.createMesg(MesgNum.MONITORING))

    constructor(mesg: Mesg) : super(mesg)


    var timestamp: DateTime?
        /**
         * Get timestamp field
         * Units: s
         * Comment: Must align to logging interval, for example, time must be 00:00:00 for daily log.
         *
         * @return timestamp
         */
        get() = timestampToDateTime(getFieldLongValue(253, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD))
        /**
         * Set timestamp field
         * Units: s
         * Comment: Must align to logging interval, for example, time must be 00:00:00 for daily log.
         *
         * @param timestamp The new timestamp value to be set
         */
        set(timestamp) {
            setFieldValue(253, 0, timestamp?.timestamp, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var deviceIndex: Short?
        /**
         * Get device_index field
         * Comment: Associates this data to device_info message. Not required for file with single device (sensor).
         *
         * @return device_index
         */
        get() = getFieldShortValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set device_index field
         * Comment: Associates this data to device_info message. Not required for file with single device (sensor).
         *
         * @param deviceIndex The new deviceIndex value to be set
         */
        set(deviceIndex) {
            setFieldValue(0, 0, deviceIndex, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var calories: Int?
        /**
         * Get calories field
         * Units: kcal
         * Comment: Accumulated total calories. Maintained by MonitoringReader for each activity_type. See SDK documentation
         *
         * @return calories
         */
        get() = getFieldIntegerValue(1, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set calories field
         * Units: kcal
         * Comment: Accumulated total calories. Maintained by MonitoringReader for each activity_type. See SDK documentation
         *
         * @param calories The new calories value to be set
         */
        set(calories) {
            setFieldValue(1, 0, calories, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var distance: Float?
        /**
         * Get distance field
         * Units: m
         * Comment: Accumulated distance. Maintained by MonitoringReader for each activity_type. See SDK documentation.
         *
         * @return distance
         */
        get() = getFieldFloatValue(2, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set distance field
         * Units: m
         * Comment: Accumulated distance. Maintained by MonitoringReader for each activity_type. See SDK documentation.
         *
         * @param distance The new distance value to be set
         */
        set(distance) {
            setFieldValue(2, 0, distance, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var cycles: Float?
        /**
         * Get cycles field
         * Units: cycles
         * Comment: Accumulated cycles. Maintained by MonitoringReader for each activity_type. See SDK documentation.
         *
         * @return cycles
         */
        get() = getFieldFloatValue(3, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set cycles field
         * Units: cycles
         * Comment: Accumulated cycles. Maintained by MonitoringReader for each activity_type. See SDK documentation.
         *
         * @param cycles The new cycles value to be set
         */
        set(cycles) {
            setFieldValue(3, 0, cycles, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var steps: Long?
        /**
         * Get steps field
         * Units: steps
         *
         * @return steps
         */
        get() = getFieldLongValue(3, 0, SubFields.MONITORING_MESG_CYCLES_FIELD_STEPS)
        /**
         * Set steps field
         * Units: steps
         *
         * @param steps The new steps value to be set
         */
        set(steps) {
            setFieldValue(3, 0, steps, SubFields.MONITORING_MESG_CYCLES_FIELD_STEPS)
        }

    var strokes: Float?
        /**
         * Get strokes field
         * Units: strokes
         *
         * @return strokes
         */
        get() = getFieldFloatValue(3, 0, SubFields.MONITORING_MESG_CYCLES_FIELD_STROKES)
        /**
         * Set strokes field
         * Units: strokes
         *
         * @param strokes The new strokes value to be set
         */
        set(strokes) {
            setFieldValue(3, 0, strokes, SubFields.MONITORING_MESG_CYCLES_FIELD_STROKES)
        }

    var activeTime: Float?
        /**
         * Get active_time field
         * Units: s
         *
         * @return active_time
         */
        get() = getFieldFloatValue(4, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set active_time field
         * Units: s
         *
         * @param activeTime The new activeTime value to be set
         */
        set(activeTime) {
            setFieldValue(4, 0, activeTime, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var activityType: ActivityType?
        /**
         * Get activity_type field
         *
         * @return activity_type
         */
        get() {
            val value = getFieldShortValue(5, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD) ?: return null
            return ActivityType.getByValue(value)
        }
        /**
         * Set activity_type field
         *
         * @param activityType The new activityType value to be set
         */
        set(activityType) {
            setFieldValue(5, 0, activityType!!.value, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var activitySubtype: ActivitySubtype?
        /**
         * Get activity_subtype field
         *
         * @return activity_subtype
         */
        get() {
            val value = getFieldShortValue(6, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD) ?: return null
            return ActivitySubtype.getByValue(value)
        }
        /**
         * Set activity_subtype field
         *
         * @param activitySubtype The new activitySubtype value to be set
         */
        set(activitySubtype) {
            setFieldValue(6, 0, activitySubtype!!.value, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var activityLevel: ActivityLevel?
        /**
         * Get activity_level field
         *
         * @return activity_level
         */
        get() {
            val value = getFieldShortValue(7, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD) ?: return null
            return ActivityLevel.getByValue(value)
        }
        /**
         * Set activity_level field
         *
         * @param activityLevel The new activityLevel value to be set
         */
        set(activityLevel) {
            setFieldValue(7, 0, activityLevel!!.value, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var distance16: Int?
        /**
         * Get distance_16 field
         * Units: 100 * m
         *
         * @return distance_16
         */
        get() = getFieldIntegerValue(8, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set distance_16 field
         * Units: 100 * m
         *
         * @param distance16 The new distance16 value to be set
         */
        set(distance16) {
            setFieldValue(8, 0, distance16, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var cycles16: Int?
        /**
         * Get cycles_16 field
         * Units: 2 * cycles (steps)
         *
         * @return cycles_16
         */
        get() = getFieldIntegerValue(9, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set cycles_16 field
         * Units: 2 * cycles (steps)
         *
         * @param cycles16 The new cycles16 value to be set
         */
        set(cycles16) {
            setFieldValue(9, 0, cycles16, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var activeTime16: Int?
        /**
         * Get active_time_16 field
         * Units: s
         *
         * @return active_time_16
         */
        get() = getFieldIntegerValue(10, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set active_time_16 field
         * Units: s
         *
         * @param activeTime16 The new activeTime16 value to be set
         */
        set(activeTime16) {
            setFieldValue(10, 0, activeTime16, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var localTimestamp: Long?
        /**
         * Get local_timestamp field
         * Comment: Must align to logging interval, for example, time must be 00:00:00 for daily log.
         *
         * @return local_timestamp
         */
        get() = getFieldLongValue(11, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set local_timestamp field
         * Comment: Must align to logging interval, for example, time must be 00:00:00 for daily log.
         *
         * @param localTimestamp The new localTimestamp value to be set
         */
        set(localTimestamp) {
            setFieldValue(11, 0, localTimestamp, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var temperature: Float?
        /**
         * Get temperature field
         * Units: C
         * Comment: Avg temperature during the logging interval ended at timestamp
         *
         * @return temperature
         */
        get() = getFieldFloatValue(12, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set temperature field
         * Units: C
         * Comment: Avg temperature during the logging interval ended at timestamp
         *
         * @param temperature The new temperature value to be set
         */
        set(temperature) {
            setFieldValue(12, 0, temperature, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var temperatureMin: Float?
        /**
         * Get temperature_min field
         * Units: C
         * Comment: Min temperature during the logging interval ended at timestamp
         *
         * @return temperature_min
         */
        get() = getFieldFloatValue(14, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set temperature_min field
         * Units: C
         * Comment: Min temperature during the logging interval ended at timestamp
         *
         * @param temperatureMin The new temperatureMin value to be set
         */
        set(temperatureMin) {
            setFieldValue(14, 0, temperatureMin, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var temperatureMax: Float?
        /**
         * Get temperature_max field
         * Units: C
         * Comment: Max temperature during the logging interval ended at timestamp
         *
         * @return temperature_max
         */
        get() = getFieldFloatValue(15, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set temperature_max field
         * Units: C
         * Comment: Max temperature during the logging interval ended at timestamp
         *
         * @param temperatureMax The new temperatureMax value to be set
         */
        set(temperatureMax) {
            setFieldValue(15, 0, temperatureMax, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    val activityTime: Array<Int>?
        get() = getFieldIntegerValues(16, Fit.SUBFIELD_INDEX_MAIN_FIELD)

    val numActivityTime: Int
        /**
         * @return number of activity_time
         */
        get() = getNumFieldValues(16, Fit.SUBFIELD_INDEX_MAIN_FIELD)

    /**
     * Get activity_time field
     * Units: minutes
     * Comment: Indexed using minute_activity_level enum
     *
     * @param index of activity_time
     * @return activity_time
     */
    fun getActivityTime(index: Int): Int? {
        return getFieldIntegerValue(16, index, Fit.SUBFIELD_INDEX_MAIN_FIELD)
    }

    /**
     * Set activity_time field
     * Units: minutes
     * Comment: Indexed using minute_activity_level enum
     *
     * @param index of activity_time
     * @param activityTime The new activityTime value to be set
     */
    fun setActivityTime(index: Int, activityTime: Int?) {
        setFieldValue(16, index, activityTime, Fit.SUBFIELD_INDEX_MAIN_FIELD)
    }

    var activeCalories: Int?
        /**
         * Get active_calories field
         * Units: kcal
         *
         * @return active_calories
         */
        get() = getFieldIntegerValue(19, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set active_calories field
         * Units: kcal
         *
         * @param activeCalories The new activeCalories value to be set
         */
        set(activeCalories) {
            setFieldValue(19, 0, activeCalories, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var currentActivityTypeIntensity: Byte?
        /**
         * Get current_activity_type_intensity field
         * Comment: Indicates single type / intensity for duration since last monitoring message.
         *
         * @return current_activity_type_intensity
         */
        get() = getFieldByteValue(24, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set current_activity_type_intensity field
         * Comment: Indicates single type / intensity for duration since last monitoring message.
         *
         * @param currentActivityTypeIntensity The new currentActivityTypeIntensity value to be set
         */
        set(currentActivityTypeIntensity) {
            setFieldValue(24, 0, currentActivityTypeIntensity, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var timestampMin8: Short?
        /**
         * Get timestamp_min_8 field
         * Units: min
         *
         * @return timestamp_min_8
         */
        get() = getFieldShortValue(25, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set timestamp_min_8 field
         * Units: min
         *
         * @param timestampMin8 The new timestampMin8 value to be set
         */
        set(timestampMin8) {
            setFieldValue(25, 0, timestampMin8, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var timestamp16: Int?
        /**
         * Get timestamp_16 field
         * Units: s
         *
         * @return timestamp_16
         */
        get() = getFieldIntegerValue(26, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set timestamp_16 field
         * Units: s
         *
         * @param timestamp16 The new timestamp16 value to be set
         */
        set(timestamp16) {
            setFieldValue(26, 0, timestamp16, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var heartRate: Short?
        /**
         * Get heart_rate field
         * Units: bpm
         *
         * @return heart_rate
         */
        get() = getFieldShortValue(27, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set heart_rate field
         * Units: bpm
         *
         * @param heartRate The new heartRate value to be set
         */
        set(heartRate) {
            setFieldValue(27, 0, heartRate, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var intensity: Float?
        /**
         * Get intensity field
         *
         * @return intensity
         */
        get() = getFieldFloatValue(28, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set intensity field
         *
         * @param intensity The new intensity value to be set
         */
        set(intensity) {
            setFieldValue(28, 0, intensity, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var durationMin: Int?
        /**
         * Get duration_min field
         * Units: min
         *
         * @return duration_min
         */
        get() = getFieldIntegerValue(29, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set duration_min field
         * Units: min
         *
         * @param durationMin The new durationMin value to be set
         */
        set(durationMin) {
            setFieldValue(29, 0, durationMin, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var duration: Long?
        /**
         * Get duration field
         * Units: s
         *
         * @return duration
         */
        get() = getFieldLongValue(30, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set duration field
         * Units: s
         *
         * @param duration The new duration value to be set
         */
        set(duration) {
            setFieldValue(30, 0, duration, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var ascent: Float?
        /**
         * Get ascent field
         * Units: m
         *
         * @return ascent
         */
        get() = getFieldFloatValue(31, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set ascent field
         * Units: m
         *
         * @param ascent The new ascent value to be set
         */
        set(ascent) {
            setFieldValue(31, 0, ascent, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var descent: Float?
        /**
         * Get descent field
         * Units: m
         *
         * @return descent
         */
        get() = getFieldFloatValue(32, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set descent field
         * Units: m
         *
         * @param descent The new descent value to be set
         */
        set(descent) {
            setFieldValue(32, 0, descent, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var moderateActivityMinutes: Int?
        /**
         * Get moderate_activity_minutes field
         * Units: minutes
         *
         * @return moderate_activity_minutes
         */
        get() = getFieldIntegerValue(33, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set moderate_activity_minutes field
         * Units: minutes
         *
         * @param moderateActivityMinutes The new moderateActivityMinutes value to be set
         */
        set(moderateActivityMinutes) {
            setFieldValue(33, 0, moderateActivityMinutes, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var vigorousActivityMinutes: Int?
        /**
         * Get vigorous_activity_minutes field
         * Units: minutes
         *
         * @return vigorous_activity_minutes
         */
        get() = getFieldIntegerValue(34, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set vigorous_activity_minutes field
         * Units: minutes
         *
         * @param vigorousActivityMinutes The new vigorousActivityMinutes value to be set
         */
        set(vigorousActivityMinutes) {
            setFieldValue(34, 0, vigorousActivityMinutes, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    companion object {
        const val TimestampFieldNum: Int = 253

        const val DeviceIndexFieldNum: Int = 0

        const val CaloriesFieldNum: Int = 1

        const val DistanceFieldNum: Int = 2

        const val CyclesFieldNum: Int = 3

        const val ActiveTimeFieldNum: Int = 4

        const val ActivityTypeFieldNum: Int = 5

        const val ActivitySubtypeFieldNum: Int = 6

        const val ActivityLevelFieldNum: Int = 7

        const val Distance16FieldNum: Int = 8

        const val Cycles16FieldNum: Int = 9

        const val ActiveTime16FieldNum: Int = 10

        const val LocalTimestampFieldNum: Int = 11

        const val TemperatureFieldNum: Int = 12

        const val TemperatureMinFieldNum: Int = 14

        const val TemperatureMaxFieldNum: Int = 15

        const val ActivityTimeFieldNum: Int = 16

        const val ActiveCaloriesFieldNum: Int = 19

        const val CurrentActivityTypeIntensityFieldNum: Int = 24

        const val TimestampMin8FieldNum: Int = 25

        const val Timestamp16FieldNum: Int = 26

        const val HeartRateFieldNum: Int = 27

        const val IntensityFieldNum: Int = 28

        const val DurationMinFieldNum: Int = 29

        const val DurationFieldNum: Int = 30

        const val AscentFieldNum: Int = 31

        const val DescentFieldNum: Int = 32

        const val ModerateActivityMinutesFieldNum: Int = 33

        const val VigorousActivityMinutesFieldNum: Int = 34


        // monitoring
        val monitoringMesg = Mesg("monitoring", MesgNum.MONITORING)

        init {
            var field_index = 0
            var subfield_index = 0
            monitoringMesg.addField(
                Field(
                    "timestamp",
                    TimestampFieldNum,
                    134,
                    1.0,
                    0.0,
                    "s",
                    false,
                    Profile.Type.DATE_TIME
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "device_index",
                    DeviceIndexFieldNum,
                    2,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.DEVICE_INDEX
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "calories",
                    CaloriesFieldNum,
                    132,
                    1.0,
                    0.0,
                    "kcal",
                    false,
                    Profile.Type.UINT16
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "distance",
                    DistanceFieldNum,
                    134,
                    100.0,
                    0.0,
                    "m",
                    false,
                    Profile.Type.UINT32
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "cycles",
                    CyclesFieldNum,
                    134,
                    2.0,
                    0.0,
                    "cycles",
                    false,
                    Profile.Type.UINT32
                )
            )
            subfield_index = 0
            monitoringMesg.fields[field_index].subFields.add(
                SubField(
                    "steps",
                    134,
                    1.0,
                    0.0,
                    "steps"
                )
            )
            monitoringMesg.fields[field_index].subFields[subfield_index].addMap(5, 6)
            monitoringMesg.fields[field_index].subFields[subfield_index].addMap(5, 1)
            subfield_index++
            monitoringMesg.fields[field_index].subFields.add(
                SubField(
                    "strokes",
                    134,
                    2.0,
                    0.0,
                    "strokes"
                )
            )
            monitoringMesg.fields[field_index].subFields[subfield_index].addMap(5, 2)
            monitoringMesg.fields[field_index].subFields[subfield_index].addMap(5, 5)
            subfield_index++
            field_index++
            monitoringMesg.addField(
                Field(
                    "active_time",
                    ActiveTimeFieldNum,
                    134,
                    1000.0,
                    0.0,
                    "s",
                    false,
                    Profile.Type.UINT32
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "activity_type",
                    ActivityTypeFieldNum,
                    0,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.ACTIVITY_TYPE
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "activity_subtype",
                    ActivitySubtypeFieldNum,
                    0,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.ACTIVITY_SUBTYPE
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "activity_level",
                    ActivityLevelFieldNum,
                    0,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.ACTIVITY_LEVEL
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "distance_16",
                    Distance16FieldNum,
                    132,
                    1.0,
                    0.0,
                    "100 * m",
                    false,
                    Profile.Type.UINT16
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "cycles_16",
                    Cycles16FieldNum,
                    132,
                    1.0,
                    0.0,
                    "2 * cycles (steps)",
                    false,
                    Profile.Type.UINT16
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "active_time_16",
                    ActiveTime16FieldNum,
                    132,
                    1.0,
                    0.0,
                    "s",
                    false,
                    Profile.Type.UINT16
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "local_timestamp",
                    LocalTimestampFieldNum,
                    134,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.LOCAL_DATE_TIME
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "temperature",
                    TemperatureFieldNum,
                    131,
                    100.0,
                    0.0,
                    "C",
                    false,
                    Profile.Type.SINT16
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "temperature_min",
                    TemperatureMinFieldNum,
                    131,
                    100.0,
                    0.0,
                    "C",
                    false,
                    Profile.Type.SINT16
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "temperature_max",
                    TemperatureMaxFieldNum,
                    131,
                    100.0,
                    0.0,
                    "C",
                    false,
                    Profile.Type.SINT16
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "activity_time",
                    ActivityTimeFieldNum,
                    132,
                    1.0,
                    0.0,
                    "minutes",
                    false,
                    Profile.Type.UINT16
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "active_calories",
                    ActiveCaloriesFieldNum,
                    132,
                    1.0,
                    0.0,
                    "kcal",
                    false,
                    Profile.Type.UINT16
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "current_activity_type_intensity",
                    CurrentActivityTypeIntensityFieldNum,
                    13,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.BYTE
                )
            )
            monitoringMesg.fields[field_index].components.add(
                FieldComponent(
                    5,
                    false,
                    5,
                    1.0,
                    0.0
                )
            ) // activity_type
            monitoringMesg.fields[field_index].components.add(
                FieldComponent(
                    28,
                    false,
                    3,
                    1.0,
                    0.0
                )
            ) // intensity
            field_index++
            monitoringMesg.addField(
                Field(
                    "timestamp_min_8",
                    TimestampMin8FieldNum,
                    2,
                    1.0,
                    0.0,
                    "min",
                    false,
                    Profile.Type.UINT8
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "timestamp_16",
                    Timestamp16FieldNum,
                    132,
                    1.0,
                    0.0,
                    "s",
                    false,
                    Profile.Type.UINT16
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "heart_rate",
                    HeartRateFieldNum,
                    2,
                    1.0,
                    0.0,
                    "bpm",
                    false,
                    Profile.Type.UINT8
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "intensity",
                    IntensityFieldNum,
                    2,
                    10.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT8
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "duration_min",
                    DurationMinFieldNum,
                    132,
                    1.0,
                    0.0,
                    "min",
                    false,
                    Profile.Type.UINT16
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "duration",
                    DurationFieldNum,
                    134,
                    1.0,
                    0.0,
                    "s",
                    false,
                    Profile.Type.UINT32
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "ascent",
                    AscentFieldNum,
                    134,
                    1000.0,
                    0.0,
                    "m",
                    false,
                    Profile.Type.UINT32
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "descent",
                    DescentFieldNum,
                    134,
                    1000.0,
                    0.0,
                    "m",
                    false,
                    Profile.Type.UINT32
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "moderate_activity_minutes",
                    ModerateActivityMinutesFieldNum,
                    132,
                    1.0,
                    0.0,
                    "minutes",
                    false,
                    Profile.Type.UINT16
                )
            )
            field_index++
            monitoringMesg.addField(
                Field(
                    "vigorous_activity_minutes",
                    VigorousActivityMinutesFieldNum,
                    132,
                    1.0,
                    0.0,
                    "minutes",
                    false,
                    Profile.Type.UINT16
                )
            )
            field_index++
        }
    }
}
