/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

object PullUpExerciseName {
    const val BANDED_PULL_UPS: Int = 0
    const val _30_DEGREE_LAT_PULLDOWN: Int = 1
    const val BAND_ASSISTED_CHIN_UP: Int = 2
    const val CLOSE_GRIP_CHIN_UP: Int = 3
    const val WEIGHTED_CLOSE_GRIP_CHIN_UP: Int = 4
    const val CLOSE_GRIP_LAT_PULLDOWN: Int = 5
    const val CROSSOVER_CHIN_UP: Int = 6
    const val WEIGHTED_CROSSOVER_CHIN_UP: Int = 7
    const val EZ_BAR_PULLOVER: Int = 8
    const val HANGING_HURDLE: Int = 9
    const val WEIGHTED_HANGING_HURDLE: Int = 10
    const val KNEELING_LAT_PULLDOWN: Int = 11
    const val KNEELING_UNDERHAND_GRIP_LAT_PULLDOWN: Int = 12
    const val LAT_PULLDOWN: Int = 13
    const val MIXED_GRIP_CHIN_UP: Int = 14
    const val WEIGHTED_MIXED_GRIP_CHIN_UP: Int = 15
    const val MIXED_GRIP_PULL_UP: Int = 16
    const val WEIGHTED_MIXED_GRIP_PULL_UP: Int = 17
    const val REVERSE_GRIP_PULLDOWN: Int = 18
    const val STANDING_CABLE_PULLOVER: Int = 19
    const val STRAIGHT_ARM_PULLDOWN: Int = 20
    const val SWISS_BALL_EZ_BAR_PULLOVER: Int = 21
    const val TOWEL_PULL_UP: Int = 22
    const val WEIGHTED_TOWEL_PULL_UP: Int = 23
    const val WEIGHTED_PULL_UP: Int = 24
    const val WIDE_GRIP_LAT_PULLDOWN: Int = 25
    const val WIDE_GRIP_PULL_UP: Int = 26
    const val WEIGHTED_WIDE_GRIP_PULL_UP: Int = 27
    const val BURPEE_PULL_UP: Int = 28
    const val WEIGHTED_BURPEE_PULL_UP: Int = 29
    const val JUMPING_PULL_UPS: Int = 30
    const val WEIGHTED_JUMPING_PULL_UPS: Int = 31
    const val KIPPING_PULL_UP: Int = 32
    const val WEIGHTED_KIPPING_PULL_UP: Int = 33
    const val L_PULL_UP: Int = 34
    const val WEIGHTED_L_PULL_UP: Int = 35
    const val SUSPENDED_CHIN_UP: Int = 36
    const val WEIGHTED_SUSPENDED_CHIN_UP: Int = 37
    const val PULL_UP: Int = 38
    const val CHIN_UP: Int = 39
    const val NEUTRAL_GRIP_CHIN_UP: Int = 40
    const val WEIGHTED_CHIN_UP: Int = 41
    const val BAND_ASSISTED_PULL_UP: Int = 42
    const val NEUTRAL_GRIP_PULL_UP: Int = 43
    const val WEIGHTED_NEUTRAL_GRIP_CHIN_UP: Int = 44
    const val WEIGHTED_NEUTRAL_GRIP_PULL_UP: Int = 45
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: MutableMap<Int?, String?>

    init {
        stringMap = HashMap<Int?, String?>()
        stringMap.put(BANDED_PULL_UPS, "BANDED_PULL_UPS")
        stringMap.put(_30_DEGREE_LAT_PULLDOWN, "_30_DEGREE_LAT_PULLDOWN")
        stringMap.put(BAND_ASSISTED_CHIN_UP, "BAND_ASSISTED_CHIN_UP")
        stringMap.put(CLOSE_GRIP_CHIN_UP, "CLOSE_GRIP_CHIN_UP")
        stringMap.put(WEIGHTED_CLOSE_GRIP_CHIN_UP, "WEIGHTED_CLOSE_GRIP_CHIN_UP")
        stringMap.put(CLOSE_GRIP_LAT_PULLDOWN, "CLOSE_GRIP_LAT_PULLDOWN")
        stringMap.put(CROSSOVER_CHIN_UP, "CROSSOVER_CHIN_UP")
        stringMap.put(WEIGHTED_CROSSOVER_CHIN_UP, "WEIGHTED_CROSSOVER_CHIN_UP")
        stringMap.put(EZ_BAR_PULLOVER, "EZ_BAR_PULLOVER")
        stringMap.put(HANGING_HURDLE, "HANGING_HURDLE")
        stringMap.put(WEIGHTED_HANGING_HURDLE, "WEIGHTED_HANGING_HURDLE")
        stringMap.put(KNEELING_LAT_PULLDOWN, "KNEELING_LAT_PULLDOWN")
        stringMap.put(KNEELING_UNDERHAND_GRIP_LAT_PULLDOWN, "KNEELING_UNDERHAND_GRIP_LAT_PULLDOWN")
        stringMap.put(LAT_PULLDOWN, "LAT_PULLDOWN")
        stringMap.put(MIXED_GRIP_CHIN_UP, "MIXED_GRIP_CHIN_UP")
        stringMap.put(WEIGHTED_MIXED_GRIP_CHIN_UP, "WEIGHTED_MIXED_GRIP_CHIN_UP")
        stringMap.put(MIXED_GRIP_PULL_UP, "MIXED_GRIP_PULL_UP")
        stringMap.put(WEIGHTED_MIXED_GRIP_PULL_UP, "WEIGHTED_MIXED_GRIP_PULL_UP")
        stringMap.put(REVERSE_GRIP_PULLDOWN, "REVERSE_GRIP_PULLDOWN")
        stringMap.put(STANDING_CABLE_PULLOVER, "STANDING_CABLE_PULLOVER")
        stringMap.put(STRAIGHT_ARM_PULLDOWN, "STRAIGHT_ARM_PULLDOWN")
        stringMap.put(SWISS_BALL_EZ_BAR_PULLOVER, "SWISS_BALL_EZ_BAR_PULLOVER")
        stringMap.put(TOWEL_PULL_UP, "TOWEL_PULL_UP")
        stringMap.put(WEIGHTED_TOWEL_PULL_UP, "WEIGHTED_TOWEL_PULL_UP")
        stringMap.put(WEIGHTED_PULL_UP, "WEIGHTED_PULL_UP")
        stringMap.put(WIDE_GRIP_LAT_PULLDOWN, "WIDE_GRIP_LAT_PULLDOWN")
        stringMap.put(WIDE_GRIP_PULL_UP, "WIDE_GRIP_PULL_UP")
        stringMap.put(WEIGHTED_WIDE_GRIP_PULL_UP, "WEIGHTED_WIDE_GRIP_PULL_UP")
        stringMap.put(BURPEE_PULL_UP, "BURPEE_PULL_UP")
        stringMap.put(WEIGHTED_BURPEE_PULL_UP, "WEIGHTED_BURPEE_PULL_UP")
        stringMap.put(JUMPING_PULL_UPS, "JUMPING_PULL_UPS")
        stringMap.put(WEIGHTED_JUMPING_PULL_UPS, "WEIGHTED_JUMPING_PULL_UPS")
        stringMap.put(KIPPING_PULL_UP, "KIPPING_PULL_UP")
        stringMap.put(WEIGHTED_KIPPING_PULL_UP, "WEIGHTED_KIPPING_PULL_UP")
        stringMap.put(L_PULL_UP, "L_PULL_UP")
        stringMap.put(WEIGHTED_L_PULL_UP, "WEIGHTED_L_PULL_UP")
        stringMap.put(SUSPENDED_CHIN_UP, "SUSPENDED_CHIN_UP")
        stringMap.put(WEIGHTED_SUSPENDED_CHIN_UP, "WEIGHTED_SUSPENDED_CHIN_UP")
        stringMap.put(PULL_UP, "PULL_UP")
        stringMap.put(CHIN_UP, "CHIN_UP")
        stringMap.put(NEUTRAL_GRIP_CHIN_UP, "NEUTRAL_GRIP_CHIN_UP")
        stringMap.put(WEIGHTED_CHIN_UP, "WEIGHTED_CHIN_UP")
        stringMap.put(BAND_ASSISTED_PULL_UP, "BAND_ASSISTED_PULL_UP")
        stringMap.put(NEUTRAL_GRIP_PULL_UP, "NEUTRAL_GRIP_PULL_UP")
        stringMap.put(WEIGHTED_NEUTRAL_GRIP_CHIN_UP, "WEIGHTED_NEUTRAL_GRIP_CHIN_UP")
        stringMap.put(WEIGHTED_NEUTRAL_GRIP_PULL_UP, "WEIGHTED_NEUTRAL_GRIP_PULL_UP")
    }


    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum contsant
     */
    fun getStringFromValue(value: Int?): String? {
        if (stringMap.containsKey(value)) {
            return stringMap.get(value)
        }

        return ""
    }

    /**
     * Returns the enum constant with the specified name.
     * @param value The enum string value
     * @return The enum constant or INVALID if unknown
     */
    fun getValueFromString(value: String?): Int? {
        for (entry in stringMap.entries) {
            if (entry.value == value) {
                return entry.key
            }
        }

        return INVALID
    }
}
