/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

object RunExerciseName {
    const val RUN: Int = 0
    const val WALK: Int = 1
    const val JOG: Int = 2
    const val SPRINT: Int = 3
    const val RUN_OR_WALK: Int = 4
    const val SPEED_WALK: Int = 5
    const val WARM_UP: Int = 6
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: MutableMap<Int?, String?>

    init {
        stringMap = HashMap<Int?, String?>()
        stringMap.put(RUN, "RUN")
        stringMap.put(WALK, "WALK")
        stringMap.put(JOG, "JOG")
        stringMap.put(SPRINT, "SPRINT")
        stringMap.put(RUN_OR_WALK, "RUN_OR_WALK")
        stringMap.put(SPEED_WALK, "SPEED_WALK")
        stringMap.put(WARM_UP, "WARM_UP")
    }


    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum contsant
     */
    fun getStringFromValue(value: Int?): String? {
        if (stringMap.containsKey(value)) {
            return stringMap.get(value)
        }

        return ""
    }

    /**
     * Returns the enum constant with the specified name.
     * @param value The enum string value
     * @return The enum constant or INVALID if unknown
     */
    fun getValueFromString(value: String?): Int? {
        for (entry in stringMap.entries) {
            if (entry.value == value) {
                return entry.key
            }
        }

        return INVALID
    }
}
