/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


class SegmentLeaderboardEntryMesg : Mesg {
    constructor() : super(Factory.createMesg(MesgNum.SEGMENT_LEADERBOARD_ENTRY))

    constructor(mesg: Mesg?) : super(mesg)


    var messageIndex: Int?
        /**
         * Get message_index field
         * 
         * @return message_index
         */
        get() = getFieldIntegerValue(254, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set message_index field
         * 
         * @param messageIndex The new messageIndex value to be set
         */
        set(messageIndex) {
            setFieldValue(254, 0, messageIndex, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    /**
     * Get name field
     * Comment: Friendly name assigned to leader
     * 
     * @return name
     */
    override fun getName(): String? {
        return getFieldStringValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
    }

    /**
     * Set name field
     * Comment: Friendly name assigned to leader
     * 
     * @param name The new name value to be set
     */
    fun setName(name: String?) {
        setFieldValue(0, 0, name, Fit.SUBFIELD_INDEX_MAIN_FIELD)
    }

    var type: SegmentLeaderboardType?
        /**
         * Get type field
         * Comment: Leader classification
         * 
         * @return type
         */
        get() {
            val value = getFieldShortValue(1, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
            if (value == null) {
                return null
            }
            return SegmentLeaderboardType.Companion.getByValue(value)
        }
        /**
         * Set type field
         * Comment: Leader classification
         * 
         * @param type The new type value to be set
         */
        set(type) {
            setFieldValue(1, 0, type!!.value, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var groupPrimaryKey: Long?
        /**
         * Get group_primary_key field
         * Comment: Primary user ID of this leader
         * 
         * @return group_primary_key
         */
        get() = getFieldLongValue(2, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set group_primary_key field
         * Comment: Primary user ID of this leader
         * 
         * @param groupPrimaryKey The new groupPrimaryKey value to be set
         */
        set(groupPrimaryKey) {
            setFieldValue(2, 0, groupPrimaryKey, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var activityId: Long?
        /**
         * Get activity_id field
         * Comment: ID of the activity associated with this leader time
         * 
         * @return activity_id
         */
        get() = getFieldLongValue(3, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set activity_id field
         * Comment: ID of the activity associated with this leader time
         * 
         * @param activityId The new activityId value to be set
         */
        set(activityId) {
            setFieldValue(3, 0, activityId, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var segmentTime: Float?
        /**
         * Get segment_time field
         * Units: s
         * Comment: Segment Time (includes pauses)
         * 
         * @return segment_time
         */
        get() = getFieldFloatValue(4, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set segment_time field
         * Units: s
         * Comment: Segment Time (includes pauses)
         * 
         * @param segmentTime The new segmentTime value to be set
         */
        set(segmentTime) {
            setFieldValue(4, 0, segmentTime, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var activityIdString: String?
        /**
         * Get activity_id_string field
         * Comment: String version of the activity_id. 21 characters long, express in decimal
         * 
         * @return activity_id_string
         */
        get() = getFieldStringValue(5, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set activity_id_string field
         * Comment: String version of the activity_id. 21 characters long, express in decimal
         * 
         * @param activityIdString The new activityIdString value to be set
         */
        set(activityIdString) {
            setFieldValue(5, 0, activityIdString, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    companion object {
        const val MessageIndexFieldNum: Int = 254

        const val NameFieldNum: Int = 0

        const val TypeFieldNum: Int = 1

        const val GroupPrimaryKeyFieldNum: Int = 2

        const val ActivityIdFieldNum: Int = 3

        const val SegmentTimeFieldNum: Int = 4

        const val ActivityIdStringFieldNum: Int = 5


        val segmentLeaderboardEntryMesg: Mesg

        init {
            // segment_leaderboard_entry
            segmentLeaderboardEntryMesg =
                Mesg("segment_leaderboard_entry", MesgNum.SEGMENT_LEADERBOARD_ENTRY)
            segmentLeaderboardEntryMesg.addField(
                Field(
                    "message_index",
                    MessageIndexFieldNum,
                    132,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.MESSAGE_INDEX
                )
            )

            segmentLeaderboardEntryMesg.addField(
                Field(
                    "name",
                    NameFieldNum,
                    7,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.STRING
                )
            )

            segmentLeaderboardEntryMesg.addField(
                Field(
                    "type",
                    TypeFieldNum,
                    0,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.SEGMENT_LEADERBOARD_TYPE
                )
            )

            segmentLeaderboardEntryMesg.addField(
                Field(
                    "group_primary_key",
                    GroupPrimaryKeyFieldNum,
                    134,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT32
                )
            )

            segmentLeaderboardEntryMesg.addField(
                Field(
                    "activity_id",
                    ActivityIdFieldNum,
                    134,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT32
                )
            )

            segmentLeaderboardEntryMesg.addField(
                Field(
                    "segment_time",
                    SegmentTimeFieldNum,
                    134,
                    1000.0,
                    0.0,
                    "s",
                    false,
                    Profile.Type.UINT32
                )
            )

            segmentLeaderboardEntryMesg.addField(
                Field(
                    "activity_id_string",
                    ActivityIdStringFieldNum,
                    7,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.STRING
                )
            )
        }
    }
}
