/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

object ShoulderPressExerciseName {
    const val ALTERNATING_DUMBBELL_SHOULDER_PRESS: Int = 0
    const val ARNOLD_PRESS: Int = 1
    const val BARBELL_FRONT_SQUAT_TO_PUSH_PRESS: Int = 2
    const val BARBELL_PUSH_PRESS: Int = 3
    const val BARBELL_SHOULDER_PRESS: Int = 4
    const val DEAD_CURL_PRESS: Int = 5
    const val DUMBBELL_ALTERNATING_SHOULDER_PRESS_AND_TWIST: Int = 6
    const val DUMBBELL_HAMMER_CURL_TO_LUNGE_TO_PRESS: Int = 7
    const val DUMBBELL_PUSH_PRESS: Int = 8
    const val FLOOR_INVERTED_SHOULDER_PRESS: Int = 9
    const val WEIGHTED_FLOOR_INVERTED_SHOULDER_PRESS: Int = 10
    const val INVERTED_SHOULDER_PRESS: Int = 11
    const val WEIGHTED_INVERTED_SHOULDER_PRESS: Int = 12
    const val ONE_ARM_PUSH_PRESS: Int = 13
    const val OVERHEAD_BARBELL_PRESS: Int = 14
    const val OVERHEAD_DUMBBELL_PRESS: Int = 15
    const val SEATED_BARBELL_SHOULDER_PRESS: Int = 16
    const val SEATED_DUMBBELL_SHOULDER_PRESS: Int = 17
    const val SINGLE_ARM_DUMBBELL_SHOULDER_PRESS: Int = 18
    const val SINGLE_ARM_STEP_UP_AND_PRESS: Int = 19
    const val SMITH_MACHINE_OVERHEAD_PRESS: Int = 20
    const val SPLIT_STANCE_HAMMER_CURL_TO_PRESS: Int = 21
    const val SWISS_BALL_DUMBBELL_SHOULDER_PRESS: Int = 22
    const val WEIGHT_PLATE_FRONT_RAISE: Int = 23
    const val DUMBBELL_SHOULDER_PRESS: Int = 24
    const val MILITARY_PRESS: Int = 25
    const val STRICT_PRESS: Int = 27
    const val DUMBBELL_FRONT_RAISE: Int = 28
    const val DUMBBELL_CURL_TO_OVERHEAD_PRESS_WHEELCHAIR: Int = 29
    const val ARNOLD_PRESS_WHEELCHAIR: Int = 30
    const val OVERHEAD_DUMBBELL_PRESS_WHEELCHAIR: Int = 31
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: MutableMap<Int?, String?>

    init {
        stringMap = HashMap<Int?, String?>()
        stringMap.put(ALTERNATING_DUMBBELL_SHOULDER_PRESS, "ALTERNATING_DUMBBELL_SHOULDER_PRESS")
        stringMap.put(ARNOLD_PRESS, "ARNOLD_PRESS")
        stringMap.put(BARBELL_FRONT_SQUAT_TO_PUSH_PRESS, "BARBELL_FRONT_SQUAT_TO_PUSH_PRESS")
        stringMap.put(BARBELL_PUSH_PRESS, "BARBELL_PUSH_PRESS")
        stringMap.put(BARBELL_SHOULDER_PRESS, "BARBELL_SHOULDER_PRESS")
        stringMap.put(DEAD_CURL_PRESS, "DEAD_CURL_PRESS")
        stringMap.put(
            DUMBBELL_ALTERNATING_SHOULDER_PRESS_AND_TWIST,
            "DUMBBELL_ALTERNATING_SHOULDER_PRESS_AND_TWIST"
        )
        stringMap.put(
            DUMBBELL_HAMMER_CURL_TO_LUNGE_TO_PRESS,
            "DUMBBELL_HAMMER_CURL_TO_LUNGE_TO_PRESS"
        )
        stringMap.put(DUMBBELL_PUSH_PRESS, "DUMBBELL_PUSH_PRESS")
        stringMap.put(FLOOR_INVERTED_SHOULDER_PRESS, "FLOOR_INVERTED_SHOULDER_PRESS")
        stringMap.put(
            WEIGHTED_FLOOR_INVERTED_SHOULDER_PRESS,
            "WEIGHTED_FLOOR_INVERTED_SHOULDER_PRESS"
        )
        stringMap.put(INVERTED_SHOULDER_PRESS, "INVERTED_SHOULDER_PRESS")
        stringMap.put(WEIGHTED_INVERTED_SHOULDER_PRESS, "WEIGHTED_INVERTED_SHOULDER_PRESS")
        stringMap.put(ONE_ARM_PUSH_PRESS, "ONE_ARM_PUSH_PRESS")
        stringMap.put(OVERHEAD_BARBELL_PRESS, "OVERHEAD_BARBELL_PRESS")
        stringMap.put(OVERHEAD_DUMBBELL_PRESS, "OVERHEAD_DUMBBELL_PRESS")
        stringMap.put(SEATED_BARBELL_SHOULDER_PRESS, "SEATED_BARBELL_SHOULDER_PRESS")
        stringMap.put(SEATED_DUMBBELL_SHOULDER_PRESS, "SEATED_DUMBBELL_SHOULDER_PRESS")
        stringMap.put(SINGLE_ARM_DUMBBELL_SHOULDER_PRESS, "SINGLE_ARM_DUMBBELL_SHOULDER_PRESS")
        stringMap.put(SINGLE_ARM_STEP_UP_AND_PRESS, "SINGLE_ARM_STEP_UP_AND_PRESS")
        stringMap.put(SMITH_MACHINE_OVERHEAD_PRESS, "SMITH_MACHINE_OVERHEAD_PRESS")
        stringMap.put(SPLIT_STANCE_HAMMER_CURL_TO_PRESS, "SPLIT_STANCE_HAMMER_CURL_TO_PRESS")
        stringMap.put(SWISS_BALL_DUMBBELL_SHOULDER_PRESS, "SWISS_BALL_DUMBBELL_SHOULDER_PRESS")
        stringMap.put(WEIGHT_PLATE_FRONT_RAISE, "WEIGHT_PLATE_FRONT_RAISE")
        stringMap.put(DUMBBELL_SHOULDER_PRESS, "DUMBBELL_SHOULDER_PRESS")
        stringMap.put(MILITARY_PRESS, "MILITARY_PRESS")
        stringMap.put(STRICT_PRESS, "STRICT_PRESS")
        stringMap.put(DUMBBELL_FRONT_RAISE, "DUMBBELL_FRONT_RAISE")
        stringMap.put(
            DUMBBELL_CURL_TO_OVERHEAD_PRESS_WHEELCHAIR,
            "DUMBBELL_CURL_TO_OVERHEAD_PRESS_WHEELCHAIR"
        )
        stringMap.put(ARNOLD_PRESS_WHEELCHAIR, "ARNOLD_PRESS_WHEELCHAIR")
        stringMap.put(OVERHEAD_DUMBBELL_PRESS_WHEELCHAIR, "OVERHEAD_DUMBBELL_PRESS_WHEELCHAIR")
    }


    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum contsant
     */
    fun getStringFromValue(value: Int?): String? {
        if (stringMap.containsKey(value)) {
            return stringMap.get(value)
        }

        return ""
    }

    /**
     * Returns the enum constant with the specified name.
     * @param value The enum string value
     * @return The enum constant or INVALID if unknown
     */
    fun getValueFromString(value: String?): Int? {
        for (entry in stringMap.entries) {
            if (entry.value == value) {
                return entry.key
            }
        }

        return INVALID
    }
}
