/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

object SitUpExerciseName {
    const val ALTERNATING_SIT_UP: Int = 0
    const val WEIGHTED_ALTERNATING_SIT_UP: Int = 1
    const val BENT_KNEE_V_UP: Int = 2
    const val WEIGHTED_BENT_KNEE_V_UP: Int = 3
    const val BUTTERFLY_SIT_UP: Int = 4
    const val WEIGHTED_BUTTERFLY_SITUP: Int = 5
    const val CROSS_PUNCH_ROLL_UP: Int = 6
    const val WEIGHTED_CROSS_PUNCH_ROLL_UP: Int = 7
    const val CROSSED_ARMS_SIT_UP: Int = 8
    const val WEIGHTED_CROSSED_ARMS_SIT_UP: Int = 9
    const val GET_UP_SIT_UP: Int = 10
    const val WEIGHTED_GET_UP_SIT_UP: Int = 11
    const val HOVERING_SIT_UP: Int = 12
    const val WEIGHTED_HOVERING_SIT_UP: Int = 13
    const val KETTLEBELL_SIT_UP: Int = 14
    const val MEDICINE_BALL_ALTERNATING_V_UP: Int = 15
    const val MEDICINE_BALL_SIT_UP: Int = 16
    const val MEDICINE_BALL_V_UP: Int = 17
    const val MODIFIED_SIT_UP: Int = 18
    const val NEGATIVE_SIT_UP: Int = 19
    const val ONE_ARM_FULL_SIT_UP: Int = 20
    const val RECLINING_CIRCLE: Int = 21
    const val WEIGHTED_RECLINING_CIRCLE: Int = 22
    const val REVERSE_CURL_UP: Int = 23
    const val WEIGHTED_REVERSE_CURL_UP: Int = 24
    const val SINGLE_LEG_SWISS_BALL_JACKKNIFE: Int = 25
    const val WEIGHTED_SINGLE_LEG_SWISS_BALL_JACKKNIFE: Int = 26
    const val THE_TEASER: Int = 27
    const val THE_TEASER_WEIGHTED: Int = 28
    const val THREE_PART_ROLL_DOWN: Int = 29
    const val WEIGHTED_THREE_PART_ROLL_DOWN: Int = 30
    const val V_UP: Int = 31
    const val WEIGHTED_V_UP: Int = 32
    const val WEIGHTED_RUSSIAN_TWIST_ON_SWISS_BALL: Int = 33
    const val WEIGHTED_SIT_UP: Int = 34
    const val X_ABS: Int = 35
    const val WEIGHTED_X_ABS: Int = 36
    const val SIT_UP: Int = 37
    const val GHD_SIT_UPS: Int = 38
    const val SIT_UP_TURKISH_GET_UP: Int = 39
    const val RUSSIAN_TWIST_ON_SWISS_BALL: Int = 40
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: MutableMap<Int?, String?>

    init {
        stringMap = HashMap<Int?, String?>()
        stringMap.put(ALTERNATING_SIT_UP, "ALTERNATING_SIT_UP")
        stringMap.put(WEIGHTED_ALTERNATING_SIT_UP, "WEIGHTED_ALTERNATING_SIT_UP")
        stringMap.put(BENT_KNEE_V_UP, "BENT_KNEE_V_UP")
        stringMap.put(WEIGHTED_BENT_KNEE_V_UP, "WEIGHTED_BENT_KNEE_V_UP")
        stringMap.put(BUTTERFLY_SIT_UP, "BUTTERFLY_SIT_UP")
        stringMap.put(WEIGHTED_BUTTERFLY_SITUP, "WEIGHTED_BUTTERFLY_SITUP")
        stringMap.put(CROSS_PUNCH_ROLL_UP, "CROSS_PUNCH_ROLL_UP")
        stringMap.put(WEIGHTED_CROSS_PUNCH_ROLL_UP, "WEIGHTED_CROSS_PUNCH_ROLL_UP")
        stringMap.put(CROSSED_ARMS_SIT_UP, "CROSSED_ARMS_SIT_UP")
        stringMap.put(WEIGHTED_CROSSED_ARMS_SIT_UP, "WEIGHTED_CROSSED_ARMS_SIT_UP")
        stringMap.put(GET_UP_SIT_UP, "GET_UP_SIT_UP")
        stringMap.put(WEIGHTED_GET_UP_SIT_UP, "WEIGHTED_GET_UP_SIT_UP")
        stringMap.put(HOVERING_SIT_UP, "HOVERING_SIT_UP")
        stringMap.put(WEIGHTED_HOVERING_SIT_UP, "WEIGHTED_HOVERING_SIT_UP")
        stringMap.put(KETTLEBELL_SIT_UP, "KETTLEBELL_SIT_UP")
        stringMap.put(MEDICINE_BALL_ALTERNATING_V_UP, "MEDICINE_BALL_ALTERNATING_V_UP")
        stringMap.put(MEDICINE_BALL_SIT_UP, "MEDICINE_BALL_SIT_UP")
        stringMap.put(MEDICINE_BALL_V_UP, "MEDICINE_BALL_V_UP")
        stringMap.put(MODIFIED_SIT_UP, "MODIFIED_SIT_UP")
        stringMap.put(NEGATIVE_SIT_UP, "NEGATIVE_SIT_UP")
        stringMap.put(ONE_ARM_FULL_SIT_UP, "ONE_ARM_FULL_SIT_UP")
        stringMap.put(RECLINING_CIRCLE, "RECLINING_CIRCLE")
        stringMap.put(WEIGHTED_RECLINING_CIRCLE, "WEIGHTED_RECLINING_CIRCLE")
        stringMap.put(REVERSE_CURL_UP, "REVERSE_CURL_UP")
        stringMap.put(WEIGHTED_REVERSE_CURL_UP, "WEIGHTED_REVERSE_CURL_UP")
        stringMap.put(SINGLE_LEG_SWISS_BALL_JACKKNIFE, "SINGLE_LEG_SWISS_BALL_JACKKNIFE")
        stringMap.put(
            WEIGHTED_SINGLE_LEG_SWISS_BALL_JACKKNIFE,
            "WEIGHTED_SINGLE_LEG_SWISS_BALL_JACKKNIFE"
        )
        stringMap.put(THE_TEASER, "THE_TEASER")
        stringMap.put(THE_TEASER_WEIGHTED, "THE_TEASER_WEIGHTED")
        stringMap.put(THREE_PART_ROLL_DOWN, "THREE_PART_ROLL_DOWN")
        stringMap.put(WEIGHTED_THREE_PART_ROLL_DOWN, "WEIGHTED_THREE_PART_ROLL_DOWN")
        stringMap.put(V_UP, "V_UP")
        stringMap.put(WEIGHTED_V_UP, "WEIGHTED_V_UP")
        stringMap.put(WEIGHTED_RUSSIAN_TWIST_ON_SWISS_BALL, "WEIGHTED_RUSSIAN_TWIST_ON_SWISS_BALL")
        stringMap.put(WEIGHTED_SIT_UP, "WEIGHTED_SIT_UP")
        stringMap.put(X_ABS, "X_ABS")
        stringMap.put(WEIGHTED_X_ABS, "WEIGHTED_X_ABS")
        stringMap.put(SIT_UP, "SIT_UP")
        stringMap.put(GHD_SIT_UPS, "GHD_SIT_UPS")
        stringMap.put(SIT_UP_TURKISH_GET_UP, "SIT_UP_TURKISH_GET_UP")
        stringMap.put(RUSSIAN_TWIST_ON_SWISS_BALL, "RUSSIAN_TWIST_ON_SWISS_BALL")
    }


    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum contsant
     */
    fun getStringFromValue(value: Int?): String? {
        if (stringMap.containsKey(value)) {
            return stringMap.get(value)
        }

        return ""
    }

    /**
     * Returns the enum constant with the specified name.
     * @param value The enum string value
     * @return The enum constant or INVALID if unknown
     */
    fun getValueFromString(value: String?): Int? {
        for (entry in stringMap.entries) {
            if (entry.value == value) {
                return entry.key
            }
        }

        return INVALID
    }
}
