/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

import com.garmin.fit.Profile.SubFields


class SlaveDeviceMesg : Mesg {
    constructor() : super(Factory.createMesg(MesgNum.SLAVE_DEVICE))

    constructor(mesg: Mesg) : super(mesg)


    var manufacturer: Int?
        /**
         * Get manufacturer field
         *
         * @return manufacturer
         */
        get() = getFieldIntegerValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set manufacturer field
         *
         * @param manufacturer The new manufacturer value to be set
         */
        set(manufacturer) {
            setFieldValue(0, 0, manufacturer, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var product: Int?
        /**
         * Get product field
         *
         * @return product
         */
        get() = getFieldIntegerValue(1, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set product field
         *
         * @param product The new product value to be set
         */
        set(product) {
            setFieldValue(1, 0, product, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var faveroProduct: Int?
        /**
         * Get favero_product field
         *
         * @return favero_product
         */
        get() = getFieldIntegerValue(1, 0, SubFields.SLAVE_DEVICE_MESG_PRODUCT_FIELD_FAVERO_PRODUCT)
        /**
         * Set favero_product field
         *
         * @param faveroProduct The new faveroProduct value to be set
         */
        set(faveroProduct) {
            setFieldValue(
                1,
                0,
                faveroProduct,
                SubFields.SLAVE_DEVICE_MESG_PRODUCT_FIELD_FAVERO_PRODUCT
            )
        }

    var garminProduct: Int?
        /**
         * Get garmin_product field
         *
         * @return garmin_product
         */
        get() = getFieldIntegerValue(1, 0, SubFields.SLAVE_DEVICE_MESG_PRODUCT_FIELD_GARMIN_PRODUCT)
        /**
         * Set garmin_product field
         *
         * @param garminProduct The new garminProduct value to be set
         */
        set(garminProduct) {
            setFieldValue(
                1,
                0,
                garminProduct,
                SubFields.SLAVE_DEVICE_MESG_PRODUCT_FIELD_GARMIN_PRODUCT
            )
        }

    companion object {
        const val ManufacturerFieldNum: Int = 0

        const val ProductFieldNum: Int = 1


        val slaveDeviceMesg: Mesg

        init {
            var field_index = 0
            var subfield_index = 0
            // slave_device
            slaveDeviceMesg = Mesg("slave_device", MesgNum.SLAVE_DEVICE)
            slaveDeviceMesg.addField(
                Field(
                    "manufacturer",
                    ManufacturerFieldNum,
                    132,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.MANUFACTURER
                )
            )
            field_index++
            slaveDeviceMesg.addField(
                Field(
                    "product",
                    ProductFieldNum,
                    132,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT16
                )
            )
            subfield_index = 0
            slaveDeviceMesg.fields[field_index].subFields.add(
                SubField(
                    "favero_product",
                    132,
                    1.0,
                    0.0,
                    ""
                )
            )
            slaveDeviceMesg.fields[field_index].subFields[subfield_index].addMap(0, 263)
            subfield_index++
            slaveDeviceMesg.fields[field_index].subFields.add(
                SubField(
                    "garmin_product",
                    132,
                    1.0,
                    0.0,
                    ""
                )
            )
            slaveDeviceMesg.fields[field_index].subFields[subfield_index].addMap(0, 1)
            slaveDeviceMesg.fields[field_index].subFields[subfield_index].addMap(0, 15)
            slaveDeviceMesg.fields[field_index].subFields[subfield_index].addMap(0, 13)
            slaveDeviceMesg.fields[field_index].subFields[subfield_index].addMap(0, 89)
            subfield_index++
            field_index++
        }
    }
}
