/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


class SleepLevelMesg : Mesg {
    constructor() : super(Factory.createMesg(MesgNum.SLEEP_LEVEL))

    constructor(mesg: Mesg) : super(mesg)


    var timestamp: DateTime?
        /**
         * Get timestamp field
         * Units: s
         *
         * @return timestamp
         */
        get() = timestampToDateTime(getFieldLongValue(253, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD))
        /**
         * Set timestamp field
         * Units: s
         *
         * @param timestamp The new timestamp value to be set
         */
        set(timestamp) {
            setFieldValue(253, 0, timestamp?.timestamp, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var sleepLevel: SleepLevel?
        /**
         * Get sleep_level field
         *
         * @return sleep_level
         */
        get() {
            val value = getFieldShortValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD) ?: return null
            return SleepLevel.getByValue(value)
        }
        /**
         * Set sleep_level field
         *
         * @param sleepLevel The new sleepLevel value to be set
         */
        set(sleepLevel) {
            setFieldValue(0, 0, sleepLevel!!.value, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    companion object {
        const val TimestampFieldNum: Int = 253

        const val SleepLevelFieldNum: Int = 0


        // sleep_level
        val sleepLevelMesg: Mesg = Mesg("sleep_level", MesgNum.SLEEP_LEVEL)

        init {
            sleepLevelMesg.addField(
                Field(
                    "timestamp",
                    TimestampFieldNum,
                    134,
                    1.0,
                    0.0,
                    "s",
                    false,
                    Profile.Type.DATE_TIME
                )
            )

            sleepLevelMesg.addField(
                Field(
                    "sleep_level",
                    SleepLevelFieldNum,
                    0,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.SLEEP_LEVEL
                )
            )
        }
    }
}
