/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


class SplitSummaryMesg : Mesg {
    constructor() : super(Factory.createMesg(MesgNum.SPLIT_SUMMARY))

    constructor(mesg: Mesg?) : super(mesg)


    var messageIndex: Int?
        /**
         * Get message_index field
         * 
         * @return message_index
         */
        get() = getFieldIntegerValue(254, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set message_index field
         * 
         * @param messageIndex The new messageIndex value to be set
         */
        set(messageIndex) {
            setFieldValue(254, 0, messageIndex, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var splitType: SplitType?
        /**
         * Get split_type field
         * 
         * @return split_type
         */
        get() {
            val value = getFieldShortValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
            if (value == null) {
                return null
            }
            return SplitType.Companion.getByValue(value)
        }
        /**
         * Set split_type field
         * 
         * @param splitType The new splitType value to be set
         */
        set(splitType) {
            setFieldValue(0, 0, splitType!!.value, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var numSplits: Int?
        /**
         * Get num_splits field
         * 
         * @return num_splits
         */
        get() = getFieldIntegerValue(3, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set num_splits field
         * 
         * @param numSplits The new numSplits value to be set
         */
        set(numSplits) {
            setFieldValue(3, 0, numSplits, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var totalTimerTime: Float?
        /**
         * Get total_timer_time field
         * Units: s
         * 
         * @return total_timer_time
         */
        get() = getFieldFloatValue(4, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set total_timer_time field
         * Units: s
         * 
         * @param totalTimerTime The new totalTimerTime value to be set
         */
        set(totalTimerTime) {
            setFieldValue(4, 0, totalTimerTime, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var totalDistance: Float?
        /**
         * Get total_distance field
         * Units: m
         * 
         * @return total_distance
         */
        get() = getFieldFloatValue(5, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set total_distance field
         * Units: m
         * 
         * @param totalDistance The new totalDistance value to be set
         */
        set(totalDistance) {
            setFieldValue(5, 0, totalDistance, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var avgSpeed: Float?
        /**
         * Get avg_speed field
         * Units: m/s
         * 
         * @return avg_speed
         */
        get() = getFieldFloatValue(6, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set avg_speed field
         * Units: m/s
         * 
         * @param avgSpeed The new avgSpeed value to be set
         */
        set(avgSpeed) {
            setFieldValue(6, 0, avgSpeed, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var maxSpeed: Float?
        /**
         * Get max_speed field
         * Units: m/s
         * 
         * @return max_speed
         */
        get() = getFieldFloatValue(7, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set max_speed field
         * Units: m/s
         * 
         * @param maxSpeed The new maxSpeed value to be set
         */
        set(maxSpeed) {
            setFieldValue(7, 0, maxSpeed, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var totalAscent: Int?
        /**
         * Get total_ascent field
         * Units: m
         * 
         * @return total_ascent
         */
        get() = getFieldIntegerValue(8, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set total_ascent field
         * Units: m
         * 
         * @param totalAscent The new totalAscent value to be set
         */
        set(totalAscent) {
            setFieldValue(8, 0, totalAscent, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var totalDescent: Int?
        /**
         * Get total_descent field
         * Units: m
         * 
         * @return total_descent
         */
        get() = getFieldIntegerValue(9, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set total_descent field
         * Units: m
         * 
         * @param totalDescent The new totalDescent value to be set
         */
        set(totalDescent) {
            setFieldValue(9, 0, totalDescent, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var avgHeartRate: Short?
        /**
         * Get avg_heart_rate field
         * Units: bpm
         * 
         * @return avg_heart_rate
         */
        get() = getFieldShortValue(10, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set avg_heart_rate field
         * Units: bpm
         * 
         * @param avgHeartRate The new avgHeartRate value to be set
         */
        set(avgHeartRate) {
            setFieldValue(10, 0, avgHeartRate, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var maxHeartRate: Short?
        /**
         * Get max_heart_rate field
         * Units: bpm
         * 
         * @return max_heart_rate
         */
        get() = getFieldShortValue(11, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set max_heart_rate field
         * Units: bpm
         * 
         * @param maxHeartRate The new maxHeartRate value to be set
         */
        set(maxHeartRate) {
            setFieldValue(11, 0, maxHeartRate, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var avgVertSpeed: Float?
        /**
         * Get avg_vert_speed field
         * Units: m/s
         * 
         * @return avg_vert_speed
         */
        get() = getFieldFloatValue(12, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set avg_vert_speed field
         * Units: m/s
         * 
         * @param avgVertSpeed The new avgVertSpeed value to be set
         */
        set(avgVertSpeed) {
            setFieldValue(12, 0, avgVertSpeed, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var totalCalories: Long?
        /**
         * Get total_calories field
         * Units: kcal
         * 
         * @return total_calories
         */
        get() = getFieldLongValue(13, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set total_calories field
         * Units: kcal
         * 
         * @param totalCalories The new totalCalories value to be set
         */
        set(totalCalories) {
            setFieldValue(13, 0, totalCalories, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var totalMovingTime: Float?
        /**
         * Get total_moving_time field
         * Units: s
         * 
         * @return total_moving_time
         */
        get() = getFieldFloatValue(77, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set total_moving_time field
         * Units: s
         * 
         * @param totalMovingTime The new totalMovingTime value to be set
         */
        set(totalMovingTime) {
            setFieldValue(77, 0, totalMovingTime, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    companion object {
        const val MessageIndexFieldNum: Int = 254

        const val SplitTypeFieldNum: Int = 0

        const val NumSplitsFieldNum: Int = 3

        const val TotalTimerTimeFieldNum: Int = 4

        const val TotalDistanceFieldNum: Int = 5

        const val AvgSpeedFieldNum: Int = 6

        const val MaxSpeedFieldNum: Int = 7

        const val TotalAscentFieldNum: Int = 8

        const val TotalDescentFieldNum: Int = 9

        const val AvgHeartRateFieldNum: Int = 10

        const val MaxHeartRateFieldNum: Int = 11

        const val AvgVertSpeedFieldNum: Int = 12

        const val TotalCaloriesFieldNum: Int = 13

        const val TotalMovingTimeFieldNum: Int = 77


        val splitSummaryMesg: Mesg

        init {
            // split_summary
            splitSummaryMesg = Mesg("split_summary", MesgNum.SPLIT_SUMMARY)
            splitSummaryMesg.addField(
                Field(
                    "message_index",
                    MessageIndexFieldNum,
                    132,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.MESSAGE_INDEX
                )
            )

            splitSummaryMesg.addField(
                Field(
                    "split_type",
                    SplitTypeFieldNum,
                    0,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.SPLIT_TYPE
                )
            )

            splitSummaryMesg.addField(
                Field(
                    "num_splits",
                    NumSplitsFieldNum,
                    132,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT16
                )
            )

            splitSummaryMesg.addField(
                Field(
                    "total_timer_time",
                    TotalTimerTimeFieldNum,
                    134,
                    1000.0,
                    0.0,
                    "s",
                    false,
                    Profile.Type.UINT32
                )
            )

            splitSummaryMesg.addField(
                Field(
                    "total_distance",
                    TotalDistanceFieldNum,
                    134,
                    100.0,
                    0.0,
                    "m",
                    false,
                    Profile.Type.UINT32
                )
            )

            splitSummaryMesg.addField(
                Field(
                    "avg_speed",
                    AvgSpeedFieldNum,
                    134,
                    1000.0,
                    0.0,
                    "m/s",
                    false,
                    Profile.Type.UINT32
                )
            )

            splitSummaryMesg.addField(
                Field(
                    "max_speed",
                    MaxSpeedFieldNum,
                    134,
                    1000.0,
                    0.0,
                    "m/s",
                    false,
                    Profile.Type.UINT32
                )
            )

            splitSummaryMesg.addField(
                Field(
                    "total_ascent",
                    TotalAscentFieldNum,
                    132,
                    1.0,
                    0.0,
                    "m",
                    false,
                    Profile.Type.UINT16
                )
            )

            splitSummaryMesg.addField(
                Field(
                    "total_descent",
                    TotalDescentFieldNum,
                    132,
                    1.0,
                    0.0,
                    "m",
                    false,
                    Profile.Type.UINT16
                )
            )

            splitSummaryMesg.addField(
                Field(
                    "avg_heart_rate",
                    AvgHeartRateFieldNum,
                    2,
                    1.0,
                    0.0,
                    "bpm",
                    false,
                    Profile.Type.UINT8
                )
            )

            splitSummaryMesg.addField(
                Field(
                    "max_heart_rate",
                    MaxHeartRateFieldNum,
                    2,
                    1.0,
                    0.0,
                    "bpm",
                    false,
                    Profile.Type.UINT8
                )
            )

            splitSummaryMesg.addField(
                Field(
                    "avg_vert_speed",
                    AvgVertSpeedFieldNum,
                    133,
                    1000.0,
                    0.0,
                    "m/s",
                    false,
                    Profile.Type.SINT32
                )
            )

            splitSummaryMesg.addField(
                Field(
                    "total_calories",
                    TotalCaloriesFieldNum,
                    134,
                    1.0,
                    0.0,
                    "kcal",
                    false,
                    Profile.Type.UINT32
                )
            )

            splitSummaryMesg.addField(
                Field(
                    "total_moving_time",
                    TotalMovingTimeFieldNum,
                    134,
                    1000.0,
                    0.0,
                    "s",
                    false,
                    Profile.Type.UINT32
                )
            )
        }
    }
}
