/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


enum class Sport(var value: Short) {
    GENERIC(0.toShort()),
    RUNNING(1.toShort()),
    CYCLING(2.toShort()),
    TRANSITION(3.toShort()),
    FITNESS_EQUIPMENT(4.toShort()),
    SWIMMING(5.toShort()),
    BASKETBALL(6.toShort()),
    SOCCER(7.toShort()),
    TENNIS(8.toShort()),
    AMERICAN_FOOTBALL(9.toShort()),
    TRAINING(10.toShort()),
    WALKING(11.toShort()),
    CROSS_COUNTRY_SKIING(12.toShort()),
    ALPINE_SKIING(13.toShort()),
    SNOWBOARDING(14.toShort()),
    ROWING(15.toShort()),
    MOUNTAINEERING(16.toShort()),
    HIKING(17.toShort()),
    MULTISPORT(18.toShort()),
    PADDLING(19.toShort()),
    FLYING(20.toShort()),
    E_BIKING(21.toShort()),
    MOTORCYCLING(22.toShort()),
    BOATING(23.toShort()),
    DRIVING(24.toShort()),
    GOLF(25.toShort()),
    HANG_GLIDING(26.toShort()),
    HORSEBACK_RIDING(27.toShort()),
    HUNTING(28.toShort()),
    FISHING(29.toShort()),
    INLINE_SKATING(30.toShort()),
    ROCK_CLIMBING(31.toShort()),
    SAILING(32.toShort()),
    ICE_SKATING(33.toShort()),
    SKY_DIVING(34.toShort()),
    SNOWSHOEING(35.toShort()),
    SNOWMOBILING(36.toShort()),
    STAND_UP_PADDLEBOARDING(37.toShort()),
    SURFING(38.toShort()),
    WAKEBOARDING(39.toShort()),
    WATER_SKIING(40.toShort()),
    KAYAKING(41.toShort()),
    RAFTING(42.toShort()),
    WINDSURFING(43.toShort()),
    KITESURFING(44.toShort()),
    TACTICAL(45.toShort()),
    JUMPMASTER(46.toShort()),
    BOXING(47.toShort()),
    FLOOR_CLIMBING(48.toShort()),
    BASEBALL(49.toShort()),
    DIVING(53.toShort()),
    SHOOTING(56.toShort()),
    WINTER_SPORT(58.toShort()),
    GRINDING(59.toShort()),
    HIIT(62.toShort()),
    VIDEO_GAMING(63.toShort()),
    RACKET(64.toShort()),
    WHEELCHAIR_PUSH_WALK(65.toShort()),
    WHEELCHAIR_PUSH_RUN(66.toShort()),
    MEDITATION(67.toShort()),
    PARA_SPORT(68.toShort()),
    DISC_GOLF(69.toShort()),
    TEAM_SPORT(70.toShort()),
    CRICKET(71.toShort()),
    RUGBY(72.toShort()),
    HOCKEY(73.toShort()),
    LACROSSE(74.toShort()),
    VOLLEYBALL(75.toShort()),
    WATER_TUBING(76.toShort()),
    WAKESURFING(77.toShort()),
    WATER_SPORT(78.toShort()),
    ARCHERY(79.toShort()),
    MIXED_MARTIAL_ARTS(80.toShort()),
    MOTOR_SPORTS(81.toShort()),
    SNORKELING(82.toShort()),
    DANCE(83.toShort()),
    JUMP_ROPE(84.toShort()),
    POOL_APNEA(85.toShort()),
    MOBILITY(86.toShort()),
    GEOCACHING(87.toShort()),
    CANOEING(88.toShort()),
    ALL(254.toShort()),
    INVALID(255.toShort());


    companion object {
        fun getByValue(value: Short): Sport {
            for (type in entries) {
                if (value == type.value) return type
            }

            return Sport.INVALID
        }

        /**
         * Retrieves the String Representation of the Value
         * @param value The enum constant
         * @return The name of this enum constant
         */
        fun getStringFromValue(value: Sport): String {
            return value.name
        }
    }
}
