/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

object SupportedExdScreenLayouts {
    const val FULL_SCREEN: Long = 0x00000001
    const val HALF_VERTICAL: Long = 0x00000002
    const val HALF_HORIZONTAL: Long = 0x00000004
    const val HALF_VERTICAL_RIGHT_SPLIT: Long = 0x00000008
    const val HALF_HORIZONTAL_BOTTOM_SPLIT: Long = 0x00000010
    const val FULL_QUARTER_SPLIT: Long = 0x00000020
    const val HALF_VERTICAL_LEFT_SPLIT: Long = 0x00000040
    const val HALF_HORIZONTAL_TOP_SPLIT: Long = 0x00000080
    val INVALID: Long = Fit.UINT32Z_INVALID

    private val stringMap = mutableMapOf<Long, String>()

    init {
        stringMap[FULL_SCREEN] = "FULL_SCREEN"
        stringMap[HALF_VERTICAL] = "HALF_VERTICAL"
        stringMap[HALF_HORIZONTAL] = "HALF_HORIZONTAL"
        stringMap[HALF_VERTICAL_RIGHT_SPLIT] = "HALF_VERTICAL_RIGHT_SPLIT"
        stringMap[HALF_HORIZONTAL_BOTTOM_SPLIT] = "HALF_HORIZONTAL_BOTTOM_SPLIT"
        stringMap[FULL_QUARTER_SPLIT] = "FULL_QUARTER_SPLIT"
        stringMap[HALF_VERTICAL_LEFT_SPLIT] = "HALF_VERTICAL_LEFT_SPLIT"
        stringMap[HALF_HORIZONTAL_TOP_SPLIT] = "HALF_HORIZONTAL_TOP_SPLIT"
    }


    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum contsant
     */
    fun getStringFromValue(value: Long): String {
        if (stringMap.containsKey(value)) {
            return stringMap[value] ?: ""
        }

        return ""
    }

    /**
     * Returns the enum constant with the specified name.
     * @param value The enum string value
     * @return The enum constant or INVALID if unknown
     */
    fun getValueFromString(value: String): Long {
        for (entry in stringMap.entries) {
            if (entry.value == value) {
                return entry.key
            }
        }

        return INVALID
    }
}
