/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


class TankUpdateMesg : Mesg {
    constructor() : super(Factory.createMesg(MesgNum.TANK_UPDATE))

    constructor(mesg: Mesg?) : super(mesg)


    var timestamp: DateTime?
        /**
         * Get timestamp field
         * Units: s
         * 
         * @return timestamp
         */
        get() = timestampToDateTime(getFieldLongValue(253, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD))
        /**
         * Set timestamp field
         * Units: s
         * 
         * @param timestamp The new timestamp value to be set
         */
        set(timestamp) {
            setFieldValue(253, 0, timestamp!!.getTimestamp(), Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var sensor: Long?
        /**
         * Get sensor field
         * 
         * @return sensor
         */
        get() = getFieldLongValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set sensor field
         * 
         * @param sensor The new sensor value to be set
         */
        set(sensor) {
            setFieldValue(0, 0, sensor, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var pressure: Float?
        /**
         * Get pressure field
         * Units: bar
         * 
         * @return pressure
         */
        get() = getFieldFloatValue(1, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set pressure field
         * Units: bar
         * 
         * @param pressure The new pressure value to be set
         */
        set(pressure) {
            setFieldValue(1, 0, pressure, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    companion object {
        const val TimestampFieldNum: Int = 253

        const val SensorFieldNum: Int = 0

        const val PressureFieldNum: Int = 1


        val tankUpdateMesg: Mesg

        init {
            // tank_update
            tankUpdateMesg = Mesg("tank_update", MesgNum.TANK_UPDATE)
            tankUpdateMesg.addField(
                Field(
                    "timestamp",
                    TimestampFieldNum,
                    134,
                    1.0,
                    0.0,
                    "s",
                    false,
                    Profile.Type.DATE_TIME
                )
            )

            tankUpdateMesg.addField(
                Field(
                    "sensor",
                    SensorFieldNum,
                    140,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.ANT_CHANNEL_ID
                )
            )

            tankUpdateMesg.addField(
                Field(
                    "pressure",
                    PressureFieldNum,
                    132,
                    100.0,
                    0.0,
                    "bar",
                    false,
                    Profile.Type.UINT16
                )
            )
        }
    }
}
