/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


class TankSummaryMesg : Mesg, AllFitMesg {
    constructor() : super(Factory.createMesg(MesgNum.TANK_SUMMARY))

    constructor(mesg: Mesg) : super(mesg)


    var timestamp: DateTime?
        /**
         * Get timestamp field
         * Units: s
         *
         * @return timestamp
         */
        get() = timestampToDateTime(getFieldLongValue(253, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD))
        /**
         * Set timestamp field
         * Units: s
         *
         * @param timestamp The new timestamp value to be set
         */
        set(timestamp) {
            setFieldValue(253, 0, timestamp?.timestamp, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var sensor: Long?
        /**
         * Get sensor field
         *
         * @return sensor
         */
        get() = getFieldLongValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set sensor field
         *
         * @param sensor The new sensor value to be set
         */
        set(sensor) {
            setFieldValue(0, 0, sensor, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var startPressure: Float?
        /**
         * Get start_pressure field
         * Units: bar
         *
         * @return start_pressure
         */
        get() = getFieldFloatValue(1, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set start_pressure field
         * Units: bar
         *
         * @param startPressure The new startPressure value to be set
         */
        set(startPressure) {
            setFieldValue(1, 0, startPressure, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var endPressure: Float?
        /**
         * Get end_pressure field
         * Units: bar
         *
         * @return end_pressure
         */
        get() = getFieldFloatValue(2, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set end_pressure field
         * Units: bar
         *
         * @param endPressure The new endPressure value to be set
         */
        set(endPressure) {
            setFieldValue(2, 0, endPressure, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var volumeUsed: Float?
        /**
         * Get volume_used field
         * Units: L
         *
         * @return volume_used
         */
        get() = getFieldFloatValue(3, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set volume_used field
         * Units: L
         *
         * @param volumeUsed The new volumeUsed value to be set
         */
        set(volumeUsed) {
            setFieldValue(3, 0, volumeUsed, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    companion object {
        const val TimestampFieldNum: Int = 253

        const val SensorFieldNum: Int = 0

        const val StartPressureFieldNum: Int = 1

        const val EndPressureFieldNum: Int = 2

        const val VolumeUsedFieldNum: Int = 3


        // tank_summary
        val tankSummaryMesg: Mesg = Mesg("tank_summary", MesgNum.TANK_SUMMARY)

        init {
            tankSummaryMesg.addField(
                Field(
                    "timestamp",
                    TimestampFieldNum,
                    134,
                    1.0,
                    0.0,
                    "s",
                    false,
                    Profile.Type.DATE_TIME
                )
            )

            tankSummaryMesg.addField(
                Field(
                    "sensor",
                    SensorFieldNum,
                    140,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.ANT_CHANNEL_ID
                )
            )

            tankSummaryMesg.addField(
                Field(
                    "start_pressure",
                    StartPressureFieldNum,
                    132,
                    100.0,
                    0.0,
                    "bar",
                    false,
                    Profile.Type.UINT16
                )
            )

            tankSummaryMesg.addField(
                Field(
                    "end_pressure",
                    EndPressureFieldNum,
                    132,
                    100.0,
                    0.0,
                    "bar",
                    false,
                    Profile.Type.UINT16
                )
            )

            tankSummaryMesg.addField(
                Field(
                    "volume_used",
                    VolumeUsedFieldNum,
                    134,
                    100.0,
                    0.0,
                    "L",
                    false,
                    Profile.Type.UINT32
                )
            )
        }
    }
}
