/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

import com.garmin.fit.Profile.SubFields


class TrainingFileMesg : Mesg {
    constructor() : super(Factory.createMesg(MesgNum.TRAINING_FILE))

    constructor(mesg: Mesg) : super(mesg)


    var timestamp: DateTime?
        /**
         * Get timestamp field
         *
         * @return timestamp
         */
        get() = timestampToDateTime(getFieldLongValue(253, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD))
        /**
         * Set timestamp field
         *
         * @param timestamp The new timestamp value to be set
         */
        set(timestamp) {
            setFieldValue(253, 0, timestamp?.timestamp, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var type: File?
        /**
         * Get type field
         *
         * @return type
         */
        get() {
            val value = getFieldShortValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD) ?: return null
            return File.getByValue(value)
        }
        /**
         * Set type field
         *
         * @param type The new type value to be set
         */
        set(type) {
            setFieldValue(0, 0, type!!.value, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var manufacturer: Int?
        /**
         * Get manufacturer field
         *
         * @return manufacturer
         */
        get() = getFieldIntegerValue(1, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set manufacturer field
         *
         * @param manufacturer The new manufacturer value to be set
         */
        set(manufacturer) {
            setFieldValue(1, 0, manufacturer, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var product: Int?
        /**
         * Get product field
         *
         * @return product
         */
        get() = getFieldIntegerValue(2, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set product field
         *
         * @param product The new product value to be set
         */
        set(product) {
            setFieldValue(2, 0, product, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var faveroProduct: Int?
        /**
         * Get favero_product field
         *
         * @return favero_product
         */
        get() = getFieldIntegerValue(
            2,
            0,
            SubFields.TRAINING_FILE_MESG_PRODUCT_FIELD_FAVERO_PRODUCT
        )
        /**
         * Set favero_product field
         *
         * @param faveroProduct The new faveroProduct value to be set
         */
        set(faveroProduct) {
            setFieldValue(
                2,
                0,
                faveroProduct,
                SubFields.TRAINING_FILE_MESG_PRODUCT_FIELD_FAVERO_PRODUCT
            )
        }

    var garminProduct: Int?
        /**
         * Get garmin_product field
         *
         * @return garmin_product
         */
        get() = getFieldIntegerValue(
            2,
            0,
            SubFields.TRAINING_FILE_MESG_PRODUCT_FIELD_GARMIN_PRODUCT
        )
        /**
         * Set garmin_product field
         *
         * @param garminProduct The new garminProduct value to be set
         */
        set(garminProduct) {
            setFieldValue(
                2,
                0,
                garminProduct,
                SubFields.TRAINING_FILE_MESG_PRODUCT_FIELD_GARMIN_PRODUCT
            )
        }

    var serialNumber: Long?
        /**
         * Get serial_number field
         *
         * @return serial_number
         */
        get() = getFieldLongValue(3, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set serial_number field
         *
         * @param serialNumber The new serialNumber value to be set
         */
        set(serialNumber) {
            setFieldValue(3, 0, serialNumber, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var timeCreated: DateTime?
        /**
         * Get time_created field
         *
         * @return time_created
         */
        get() = timestampToDateTime(getFieldLongValue(4, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD))
        /**
         * Set time_created field
         *
         * @param timeCreated The new timeCreated value to be set
         */
        set(timeCreated) {
            setFieldValue(4, 0, timeCreated?.timestamp, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    companion object {
        const val TimestampFieldNum: Int = 253

        const val TypeFieldNum: Int = 0

        const val ManufacturerFieldNum: Int = 1

        const val ProductFieldNum: Int = 2

        const val SerialNumberFieldNum: Int = 3

        const val TimeCreatedFieldNum: Int = 4


        val trainingFileMesg: Mesg

        init {
            var field_index = 0
            var subfield_index = 0
            // training_file
            trainingFileMesg = Mesg("training_file", MesgNum.TRAINING_FILE)
            trainingFileMesg.addField(
                Field(
                    "timestamp",
                    TimestampFieldNum,
                    134,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.DATE_TIME
                )
            )
            field_index++
            trainingFileMesg.addField(
                Field(
                    "type",
                    TypeFieldNum,
                    0,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.FILE
                )
            )
            field_index++
            trainingFileMesg.addField(
                Field(
                    "manufacturer",
                    ManufacturerFieldNum,
                    132,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.MANUFACTURER
                )
            )
            field_index++
            trainingFileMesg.addField(
                Field(
                    "product",
                    ProductFieldNum,
                    132,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT16
                )
            )
            subfield_index = 0
            trainingFileMesg.fields[field_index].subFields.add(
                SubField(
                    "favero_product",
                    132,
                    1.0,
                    0.0,
                    ""
                )
            )
            trainingFileMesg.fields[field_index].subFields[subfield_index].addMap(1, 263)
            subfield_index++
            trainingFileMesg.fields[field_index].subFields.add(
                SubField(
                    "garmin_product",
                    132,
                    1.0,
                    0.0,
                    ""
                )
            )
            trainingFileMesg.fields[field_index].subFields[subfield_index].addMap(1, 1)
            trainingFileMesg.fields[field_index].subFields[subfield_index].addMap(1, 15)
            trainingFileMesg.fields[field_index].subFields[subfield_index].addMap(1, 13)
            trainingFileMesg.fields[field_index].subFields[subfield_index].addMap(1, 89)
            subfield_index++
            field_index++
            trainingFileMesg.addField(
                Field(
                    "serial_number",
                    SerialNumberFieldNum,
                    140,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT32Z
                )
            )
            field_index++
            trainingFileMesg.addField(
                Field(
                    "time_created",
                    TimeCreatedFieldNum,
                    134,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.DATE_TIME
                )
            )
            field_index++
        }
    }
}
