/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


class VideoMesg : Mesg {
    constructor() : super(Factory.createMesg(MesgNum.VIDEO))

    constructor(mesg: Mesg) : super(mesg)


    var url: String?
        /**
         * Get url field
         *
         * @return url
         */
        get() = getFieldStringValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set url field
         *
         * @param url The new url value to be set
         */
        set(url) {
            setFieldValue(0, 0, url, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var hostingProvider: String?
        /**
         * Get hosting_provider field
         *
         * @return hosting_provider
         */
        get() = getFieldStringValue(1, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set hosting_provider field
         *
         * @param hostingProvider The new hostingProvider value to be set
         */
        set(hostingProvider) {
            setFieldValue(1, 0, hostingProvider, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var duration: Long?
        /**
         * Get duration field
         * Units: ms
         * Comment: Playback time of video
         *
         * @return duration
         */
        get() = getFieldLongValue(2, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set duration field
         * Units: ms
         * Comment: Playback time of video
         *
         * @param duration The new duration value to be set
         */
        set(duration) {
            setFieldValue(2, 0, duration, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    companion object {
        const val UrlFieldNum: Int = 0

        const val HostingProviderFieldNum: Int = 1

        const val DurationFieldNum: Int = 2


        // video
        val videoMesg: Mesg = Mesg("video", MesgNum.VIDEO)

        init {
            videoMesg.addField(
                Field(
                    "url",
                    UrlFieldNum,
                    7,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.STRING
                )
            )

            videoMesg.addField(
                Field(
                    "hosting_provider",
                    HostingProviderFieldNum,
                    7,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.STRING
                )
            )

            videoMesg.addField(
                Field(
                    "duration",
                    DurationFieldNum,
                    134,
                    1.0,
                    0.0,
                    "ms",
                    false,
                    Profile.Type.UINT32
                )
            )
        }
    }
}
