/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit

object WarmUpExerciseName {
    const val QUADRUPED_ROCKING: Int = 0
    const val NECK_TILTS: Int = 1
    const val ANKLE_CIRCLES: Int = 2
    const val ANKLE_DORSIFLEXION_WITH_BAND: Int = 3
    const val ANKLE_INTERNAL_ROTATION: Int = 4
    const val ARM_CIRCLES: Int = 5
    const val BENT_OVER_REACH_TO_SKY: Int = 6
    const val CAT_CAMEL: Int = 7
    const val ELBOW_TO_FOOT_LUNGE: Int = 8
    const val FORWARD_AND_BACKWARD_LEG_SWINGS: Int = 9
    const val GROINERS: Int = 10
    const val INVERTED_HAMSTRING_STRETCH: Int = 11
    const val LATERAL_DUCK_UNDER: Int = 12
    const val NECK_ROTATIONS: Int = 13
    const val OPPOSITE_ARM_AND_LEG_BALANCE: Int = 14
    const val REACH_ROLL_AND_LIFT: Int = 15
    const val SCORPION: Int = 16 // Deprecated do not use
    const val SHOULDER_CIRCLES: Int = 17
    const val SIDE_TO_SIDE_LEG_SWINGS: Int = 18
    const val SLEEPER_STRETCH: Int = 19
    const val SLIDE_OUT: Int = 20
    const val SWISS_BALL_HIP_CROSSOVER: Int = 21
    const val SWISS_BALL_REACH_ROLL_AND_LIFT: Int = 22
    const val SWISS_BALL_WINDSHIELD_WIPERS: Int = 23
    const val THORACIC_ROTATION: Int = 24
    const val WALKING_HIGH_KICKS: Int = 25
    const val WALKING_HIGH_KNEES: Int = 26
    const val WALKING_KNEE_HUGS: Int = 27
    const val WALKING_LEG_CRADLES: Int = 28
    const val WALKOUT: Int = 29
    const val WALKOUT_FROM_PUSH_UP_POSITION: Int = 30
    const val BICEPS_STRETCH: Int = 31
    const val GLUTES_STRETCH: Int = 32
    const val STANDING_HAMSTRING_STRETCH: Int = 33
    const val STRETCH_90_90: Int = 34
    const val STRETCH_ABS: Int = 35
    const val STRETCH_BUTTERFLY: Int = 36
    const val STRETCH_CALF: Int = 37
    const val STRETCH_CAT_COW: Int = 38
    const val STRETCH_CHILDS_POSE: Int = 39
    const val STRETCH_COBRA: Int = 40
    const val STRETCH_FOREARMS: Int = 41
    const val STRETCH_FORWARD_GLUTES: Int = 42
    const val STRETCH_FRONT_SPLIT: Int = 43
    const val STRETCH_HAMSTRING: Int = 44
    const val STRETCH_HIP_FLEXOR_AND_QUAD: Int = 45
    const val STRETCH_LAT: Int = 46
    const val STRETCH_LEVATOR_SCAPULAE: Int = 47
    const val STRETCH_LUNGE_WITH_SPINAL_TWIST: Int = 48
    const val STRETCH_LUNGING_HIP_FLEXOR: Int = 49
    const val STRETCH_LYING_ABDUCTION: Int = 50
    const val STRETCH_LYING_IT_BAND: Int = 51
    const val STRETCH_LYING_KNEE_TO_CHEST: Int = 52
    const val STRETCH_LYING_PIRIFORMIS: Int = 53
    const val STRETCH_LYING_SPINAL_TWIST: Int = 54
    const val STRETCH_NECK: Int = 55
    const val STRETCH_OBLIQUES: Int = 56
    const val STRETCH_OVER_UNDER_SHOULDER: Int = 57
    const val STRETCH_PECTORAL: Int = 58
    const val STRETCH_PIGEON_POSE: Int = 59
    const val STRETCH_PIRIFORMIS: Int = 60
    const val STRETCH_QUAD: Int = 61
    const val STRETCH_SCORPION: Int = 62
    const val STRETCH_SHOULDER: Int = 63
    const val STRETCH_SIDE: Int = 64
    const val STRETCH_SIDE_LUNGE: Int = 65
    const val STRETCH_SIDE_SPLIT: Int = 66
    const val STRETCH_STANDING_IT_BAND: Int = 67
    const val STRETCH_STRADDLE: Int = 68
    const val STRETCH_TRICEPS: Int = 69
    const val STRETCH_WALL_CHEST_AND_SHOULDER: Int = 70
    const val NECK_ROTATIONS_WHEELCHAIR: Int = 71
    const val HALF_KNEELING_ARM_ROTATION: Int = 72
    const val THREE_WAY_ANKLE_MOBILIZATION: Int = 73
    const val NINETY_NINETY_HIP_SWITCH: Int = 74 // 90_90_hip_switch
    const val ACTIVE_FROG: Int = 75
    const val SHOULDER_SWEEPS: Int = 76
    const val ANKLE_LUNGES: Int = 77
    const val BACK_ROLL_FOAM_ROLLER: Int = 78
    const val BEAR_CRAWL: Int = 79
    const val LATISSIMUS_DORSI_FOAM_ROLL: Int = 80
    const val REVERSE_T_HIP_OPENER: Int = 81
    const val SHOULDER_ROLLS: Int = 82
    const val CHEST_OPENERS: Int = 83
    const val TRICEPS_STRETCH: Int = 84
    const val UPPER_BACK_STRETCH: Int = 85
    const val HIP_CIRCLES: Int = 86
    const val ANKLE_STRETCH: Int = 87
    const val MARCHING_IN_PLACE: Int = 88
    const val TRICEPS_STRETCH_WHEELCHAIR: Int = 89
    const val UPPER_BACK_STRETCH_WHEELCHAIR: Int = 90
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: MutableMap<Int?, String?>

    init {
        stringMap = HashMap<Int?, String?>()
        stringMap.put(QUADRUPED_ROCKING, "QUADRUPED_ROCKING")
        stringMap.put(NECK_TILTS, "NECK_TILTS")
        stringMap.put(ANKLE_CIRCLES, "ANKLE_CIRCLES")
        stringMap.put(ANKLE_DORSIFLEXION_WITH_BAND, "ANKLE_DORSIFLEXION_WITH_BAND")
        stringMap.put(ANKLE_INTERNAL_ROTATION, "ANKLE_INTERNAL_ROTATION")
        stringMap.put(ARM_CIRCLES, "ARM_CIRCLES")
        stringMap.put(BENT_OVER_REACH_TO_SKY, "BENT_OVER_REACH_TO_SKY")
        stringMap.put(CAT_CAMEL, "CAT_CAMEL")
        stringMap.put(ELBOW_TO_FOOT_LUNGE, "ELBOW_TO_FOOT_LUNGE")
        stringMap.put(FORWARD_AND_BACKWARD_LEG_SWINGS, "FORWARD_AND_BACKWARD_LEG_SWINGS")
        stringMap.put(GROINERS, "GROINERS")
        stringMap.put(INVERTED_HAMSTRING_STRETCH, "INVERTED_HAMSTRING_STRETCH")
        stringMap.put(LATERAL_DUCK_UNDER, "LATERAL_DUCK_UNDER")
        stringMap.put(NECK_ROTATIONS, "NECK_ROTATIONS")
        stringMap.put(OPPOSITE_ARM_AND_LEG_BALANCE, "OPPOSITE_ARM_AND_LEG_BALANCE")
        stringMap.put(REACH_ROLL_AND_LIFT, "REACH_ROLL_AND_LIFT")
        stringMap.put(SCORPION, "SCORPION")
        stringMap.put(SHOULDER_CIRCLES, "SHOULDER_CIRCLES")
        stringMap.put(SIDE_TO_SIDE_LEG_SWINGS, "SIDE_TO_SIDE_LEG_SWINGS")
        stringMap.put(SLEEPER_STRETCH, "SLEEPER_STRETCH")
        stringMap.put(SLIDE_OUT, "SLIDE_OUT")
        stringMap.put(SWISS_BALL_HIP_CROSSOVER, "SWISS_BALL_HIP_CROSSOVER")
        stringMap.put(SWISS_BALL_REACH_ROLL_AND_LIFT, "SWISS_BALL_REACH_ROLL_AND_LIFT")
        stringMap.put(SWISS_BALL_WINDSHIELD_WIPERS, "SWISS_BALL_WINDSHIELD_WIPERS")
        stringMap.put(THORACIC_ROTATION, "THORACIC_ROTATION")
        stringMap.put(WALKING_HIGH_KICKS, "WALKING_HIGH_KICKS")
        stringMap.put(WALKING_HIGH_KNEES, "WALKING_HIGH_KNEES")
        stringMap.put(WALKING_KNEE_HUGS, "WALKING_KNEE_HUGS")
        stringMap.put(WALKING_LEG_CRADLES, "WALKING_LEG_CRADLES")
        stringMap.put(WALKOUT, "WALKOUT")
        stringMap.put(WALKOUT_FROM_PUSH_UP_POSITION, "WALKOUT_FROM_PUSH_UP_POSITION")
        stringMap.put(BICEPS_STRETCH, "BICEPS_STRETCH")
        stringMap.put(GLUTES_STRETCH, "GLUTES_STRETCH")
        stringMap.put(STANDING_HAMSTRING_STRETCH, "STANDING_HAMSTRING_STRETCH")
        stringMap.put(STRETCH_90_90, "STRETCH_90_90")
        stringMap.put(STRETCH_ABS, "STRETCH_ABS")
        stringMap.put(STRETCH_BUTTERFLY, "STRETCH_BUTTERFLY")
        stringMap.put(STRETCH_CALF, "STRETCH_CALF")
        stringMap.put(STRETCH_CAT_COW, "STRETCH_CAT_COW")
        stringMap.put(STRETCH_CHILDS_POSE, "STRETCH_CHILDS_POSE")
        stringMap.put(STRETCH_COBRA, "STRETCH_COBRA")
        stringMap.put(STRETCH_FOREARMS, "STRETCH_FOREARMS")
        stringMap.put(STRETCH_FORWARD_GLUTES, "STRETCH_FORWARD_GLUTES")
        stringMap.put(STRETCH_FRONT_SPLIT, "STRETCH_FRONT_SPLIT")
        stringMap.put(STRETCH_HAMSTRING, "STRETCH_HAMSTRING")
        stringMap.put(STRETCH_HIP_FLEXOR_AND_QUAD, "STRETCH_HIP_FLEXOR_AND_QUAD")
        stringMap.put(STRETCH_LAT, "STRETCH_LAT")
        stringMap.put(STRETCH_LEVATOR_SCAPULAE, "STRETCH_LEVATOR_SCAPULAE")
        stringMap.put(STRETCH_LUNGE_WITH_SPINAL_TWIST, "STRETCH_LUNGE_WITH_SPINAL_TWIST")
        stringMap.put(STRETCH_LUNGING_HIP_FLEXOR, "STRETCH_LUNGING_HIP_FLEXOR")
        stringMap.put(STRETCH_LYING_ABDUCTION, "STRETCH_LYING_ABDUCTION")
        stringMap.put(STRETCH_LYING_IT_BAND, "STRETCH_LYING_IT_BAND")
        stringMap.put(STRETCH_LYING_KNEE_TO_CHEST, "STRETCH_LYING_KNEE_TO_CHEST")
        stringMap.put(STRETCH_LYING_PIRIFORMIS, "STRETCH_LYING_PIRIFORMIS")
        stringMap.put(STRETCH_LYING_SPINAL_TWIST, "STRETCH_LYING_SPINAL_TWIST")
        stringMap.put(STRETCH_NECK, "STRETCH_NECK")
        stringMap.put(STRETCH_OBLIQUES, "STRETCH_OBLIQUES")
        stringMap.put(STRETCH_OVER_UNDER_SHOULDER, "STRETCH_OVER_UNDER_SHOULDER")
        stringMap.put(STRETCH_PECTORAL, "STRETCH_PECTORAL")
        stringMap.put(STRETCH_PIGEON_POSE, "STRETCH_PIGEON_POSE")
        stringMap.put(STRETCH_PIRIFORMIS, "STRETCH_PIRIFORMIS")
        stringMap.put(STRETCH_QUAD, "STRETCH_QUAD")
        stringMap.put(STRETCH_SCORPION, "STRETCH_SCORPION")
        stringMap.put(STRETCH_SHOULDER, "STRETCH_SHOULDER")
        stringMap.put(STRETCH_SIDE, "STRETCH_SIDE")
        stringMap.put(STRETCH_SIDE_LUNGE, "STRETCH_SIDE_LUNGE")
        stringMap.put(STRETCH_SIDE_SPLIT, "STRETCH_SIDE_SPLIT")
        stringMap.put(STRETCH_STANDING_IT_BAND, "STRETCH_STANDING_IT_BAND")
        stringMap.put(STRETCH_STRADDLE, "STRETCH_STRADDLE")
        stringMap.put(STRETCH_TRICEPS, "STRETCH_TRICEPS")
        stringMap.put(STRETCH_WALL_CHEST_AND_SHOULDER, "STRETCH_WALL_CHEST_AND_SHOULDER")
        stringMap.put(NECK_ROTATIONS_WHEELCHAIR, "NECK_ROTATIONS_WHEELCHAIR")
        stringMap.put(HALF_KNEELING_ARM_ROTATION, "HALF_KNEELING_ARM_ROTATION")
        stringMap.put(THREE_WAY_ANKLE_MOBILIZATION, "THREE_WAY_ANKLE_MOBILIZATION")
        stringMap.put(NINETY_NINETY_HIP_SWITCH, "NINETY_NINETY_HIP_SWITCH")
        stringMap.put(ACTIVE_FROG, "ACTIVE_FROG")
        stringMap.put(SHOULDER_SWEEPS, "SHOULDER_SWEEPS")
        stringMap.put(ANKLE_LUNGES, "ANKLE_LUNGES")
        stringMap.put(BACK_ROLL_FOAM_ROLLER, "BACK_ROLL_FOAM_ROLLER")
        stringMap.put(BEAR_CRAWL, "BEAR_CRAWL")
        stringMap.put(LATISSIMUS_DORSI_FOAM_ROLL, "LATISSIMUS_DORSI_FOAM_ROLL")
        stringMap.put(REVERSE_T_HIP_OPENER, "REVERSE_T_HIP_OPENER")
        stringMap.put(SHOULDER_ROLLS, "SHOULDER_ROLLS")
        stringMap.put(CHEST_OPENERS, "CHEST_OPENERS")
        stringMap.put(TRICEPS_STRETCH, "TRICEPS_STRETCH")
        stringMap.put(UPPER_BACK_STRETCH, "UPPER_BACK_STRETCH")
        stringMap.put(HIP_CIRCLES, "HIP_CIRCLES")
        stringMap.put(ANKLE_STRETCH, "ANKLE_STRETCH")
        stringMap.put(MARCHING_IN_PLACE, "MARCHING_IN_PLACE")
        stringMap.put(TRICEPS_STRETCH_WHEELCHAIR, "TRICEPS_STRETCH_WHEELCHAIR")
        stringMap.put(UPPER_BACK_STRETCH_WHEELCHAIR, "UPPER_BACK_STRETCH_WHEELCHAIR")
    }


    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum contsant
     */
    fun getStringFromValue(value: Int?): String? {
        if (stringMap.containsKey(value)) {
            return stringMap.get(value)
        }

        return ""
    }

    /**
     * Returns the enum constant with the specified name.
     * @param value The enum string value
     * @return The enum constant or INVALID if unknown
     */
    fun getValueFromString(value: String?): Int? {
        for (entry in stringMap.entries) {
            if (entry.value == value) {
                return entry.key
            }
        }

        return INVALID
    }
}
