/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit


class WeightScaleMesg : Mesg, AllFitMesg {
    constructor() : super(Factory.createMesg(MesgNum.WEIGHT_SCALE))

    constructor(mesg: Mesg) : super(mesg)


    var timestamp: DateTime?
        /**
         * Get timestamp field
         * Units: s
         *
         * @return timestamp
         */
        get() = timestampToDateTime(getFieldLongValue(253, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD))
        /**
         * Set timestamp field
         * Units: s
         *
         * @param timestamp The new timestamp value to be set
         */
        set(timestamp) {
            setFieldValue(253, 0, timestamp?.timestamp, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var weight: Float?
        /**
         * Get weight field
         * Units: kg
         *
         * @return weight
         */
        get() = getFieldFloatValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set weight field
         * Units: kg
         *
         * @param weight The new weight value to be set
         */
        set(weight) {
            setFieldValue(0, 0, weight, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var percentFat: Float?
        /**
         * Get percent_fat field
         * Units: %
         *
         * @return percent_fat
         */
        get() = getFieldFloatValue(1, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set percent_fat field
         * Units: %
         *
         * @param percentFat The new percentFat value to be set
         */
        set(percentFat) {
            setFieldValue(1, 0, percentFat, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var percentHydration: Float?
        /**
         * Get percent_hydration field
         * Units: %
         *
         * @return percent_hydration
         */
        get() = getFieldFloatValue(2, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set percent_hydration field
         * Units: %
         *
         * @param percentHydration The new percentHydration value to be set
         */
        set(percentHydration) {
            setFieldValue(2, 0, percentHydration, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var visceralFatMass: Float?
        /**
         * Get visceral_fat_mass field
         * Units: kg
         *
         * @return visceral_fat_mass
         */
        get() = getFieldFloatValue(3, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set visceral_fat_mass field
         * Units: kg
         *
         * @param visceralFatMass The new visceralFatMass value to be set
         */
        set(visceralFatMass) {
            setFieldValue(3, 0, visceralFatMass, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var boneMass: Float?
        /**
         * Get bone_mass field
         * Units: kg
         *
         * @return bone_mass
         */
        get() = getFieldFloatValue(4, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set bone_mass field
         * Units: kg
         *
         * @param boneMass The new boneMass value to be set
         */
        set(boneMass) {
            setFieldValue(4, 0, boneMass, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var muscleMass: Float?
        /**
         * Get muscle_mass field
         * Units: kg
         *
         * @return muscle_mass
         */
        get() = getFieldFloatValue(5, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set muscle_mass field
         * Units: kg
         *
         * @param muscleMass The new muscleMass value to be set
         */
        set(muscleMass) {
            setFieldValue(5, 0, muscleMass, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var basalMet: Float?
        /**
         * Get basal_met field
         * Units: kcal/day
         *
         * @return basal_met
         */
        get() = getFieldFloatValue(7, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set basal_met field
         * Units: kcal/day
         *
         * @param basalMet The new basalMet value to be set
         */
        set(basalMet) {
            setFieldValue(7, 0, basalMet, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var physiqueRating: Short?
        /**
         * Get physique_rating field
         *
         * @return physique_rating
         */
        get() = getFieldShortValue(8, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set physique_rating field
         *
         * @param physiqueRating The new physiqueRating value to be set
         */
        set(physiqueRating) {
            setFieldValue(8, 0, physiqueRating, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var activeMet: Float?
        /**
         * Get active_met field
         * Units: kcal/day
         * Comment: ~4kJ per kcal, 0.25 allows max 16384 kcal
         *
         * @return active_met
         */
        get() = getFieldFloatValue(9, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set active_met field
         * Units: kcal/day
         * Comment: ~4kJ per kcal, 0.25 allows max 16384 kcal
         *
         * @param activeMet The new activeMet value to be set
         */
        set(activeMet) {
            setFieldValue(9, 0, activeMet, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var metabolicAge: Short?
        /**
         * Get metabolic_age field
         * Units: years
         *
         * @return metabolic_age
         */
        get() = getFieldShortValue(10, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set metabolic_age field
         * Units: years
         *
         * @param metabolicAge The new metabolicAge value to be set
         */
        set(metabolicAge) {
            setFieldValue(10, 0, metabolicAge, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var visceralFatRating: Short?
        /**
         * Get visceral_fat_rating field
         *
         * @return visceral_fat_rating
         */
        get() = getFieldShortValue(11, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set visceral_fat_rating field
         *
         * @param visceralFatRating The new visceralFatRating value to be set
         */
        set(visceralFatRating) {
            setFieldValue(11, 0, visceralFatRating, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var userProfileIndex: Int?
        /**
         * Get user_profile_index field
         * Comment: Associates this weight scale message to a user. This corresponds to the index of the user profile message in the weight scale file.
         *
         * @return user_profile_index
         */
        get() = getFieldIntegerValue(12, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set user_profile_index field
         * Comment: Associates this weight scale message to a user. This corresponds to the index of the user profile message in the weight scale file.
         *
         * @param userProfileIndex The new userProfileIndex value to be set
         */
        set(userProfileIndex) {
            setFieldValue(12, 0, userProfileIndex, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    var bmi: Float?
        /**
         * Get bmi field
         * Units: kg/m^2
         *
         * @return bmi
         */
        get() = getFieldFloatValue(13, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        /**
         * Set bmi field
         * Units: kg/m^2
         *
         * @param bmi The new bmi value to be set
         */
        set(bmi) {
            setFieldValue(13, 0, bmi, Fit.SUBFIELD_INDEX_MAIN_FIELD)
        }

    companion object {
        const val TimestampFieldNum: Int = 253

        const val WeightFieldNum: Int = 0

        const val PercentFatFieldNum: Int = 1

        const val PercentHydrationFieldNum: Int = 2

        const val VisceralFatMassFieldNum: Int = 3

        const val BoneMassFieldNum: Int = 4

        const val MuscleMassFieldNum: Int = 5

        const val BasalMetFieldNum: Int = 7

        const val PhysiqueRatingFieldNum: Int = 8

        const val ActiveMetFieldNum: Int = 9

        const val MetabolicAgeFieldNum: Int = 10

        const val VisceralFatRatingFieldNum: Int = 11

        const val UserProfileIndexFieldNum: Int = 12

        const val BmiFieldNum: Int = 13


        // weight_scale
        val weightScaleMesg: Mesg = Mesg("weight_scale", MesgNum.WEIGHT_SCALE)

        init {
            weightScaleMesg.addField(
                Field(
                    "timestamp",
                    TimestampFieldNum,
                    134,
                    1.0,
                    0.0,
                    "s",
                    false,
                    Profile.Type.DATE_TIME
                )
            )

            weightScaleMesg.addField(
                Field(
                    "weight",
                    WeightFieldNum,
                    132,
                    100.0,
                    0.0,
                    "kg",
                    false,
                    Profile.Type.WEIGHT
                )
            )

            weightScaleMesg.addField(
                Field(
                    "percent_fat",
                    PercentFatFieldNum,
                    132,
                    100.0,
                    0.0,
                    "%",
                    false,
                    Profile.Type.UINT16
                )
            )

            weightScaleMesg.addField(
                Field(
                    "percent_hydration",
                    PercentHydrationFieldNum,
                    132,
                    100.0,
                    0.0,
                    "%",
                    false,
                    Profile.Type.UINT16
                )
            )

            weightScaleMesg.addField(
                Field(
                    "visceral_fat_mass",
                    VisceralFatMassFieldNum,
                    132,
                    100.0,
                    0.0,
                    "kg",
                    false,
                    Profile.Type.UINT16
                )
            )

            weightScaleMesg.addField(
                Field(
                    "bone_mass",
                    BoneMassFieldNum,
                    132,
                    100.0,
                    0.0,
                    "kg",
                    false,
                    Profile.Type.UINT16
                )
            )

            weightScaleMesg.addField(
                Field(
                    "muscle_mass",
                    MuscleMassFieldNum,
                    132,
                    100.0,
                    0.0,
                    "kg",
                    false,
                    Profile.Type.UINT16
                )
            )

            weightScaleMesg.addField(
                Field(
                    "basal_met",
                    BasalMetFieldNum,
                    132,
                    4.0,
                    0.0,
                    "kcal/day",
                    false,
                    Profile.Type.UINT16
                )
            )

            weightScaleMesg.addField(
                Field(
                    "physique_rating",
                    PhysiqueRatingFieldNum,
                    2,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT8
                )
            )

            weightScaleMesg.addField(
                Field(
                    "active_met",
                    ActiveMetFieldNum,
                    132,
                    4.0,
                    0.0,
                    "kcal/day",
                    false,
                    Profile.Type.UINT16
                )
            )

            weightScaleMesg.addField(
                Field(
                    "metabolic_age",
                    MetabolicAgeFieldNum,
                    2,
                    1.0,
                    0.0,
                    "years",
                    false,
                    Profile.Type.UINT8
                )
            )

            weightScaleMesg.addField(
                Field(
                    "visceral_fat_rating",
                    VisceralFatRatingFieldNum,
                    2,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.UINT8
                )
            )

            weightScaleMesg.addField(
                Field(
                    "user_profile_index",
                    UserProfileIndexFieldNum,
                    132,
                    1.0,
                    0.0,
                    "",
                    false,
                    Profile.Type.MESSAGE_INDEX
                )
            )

            weightScaleMesg.addField(
                Field(
                    "bmi",
                    BmiFieldNum,
                    132,
                    10.0,
                    0.0,
                    "kg/m^2",
                    false,
                    Profile.Type.UINT16
                )
            )
        }
    }
}
