/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit.csv

import java.io.ByteArrayOutputStream

class CSVWriter(outputStream: ByteArrayOutputStream) {
    internal var csvWriter: CSVWritable = if (outputStream is ByteArrayOutputStreamPrefixable)
        CSVWriterPrefixable(outputStream)
    else
        CSVWriterBufferedOutput(outputStream)

    val headers: ArrayList<String> = ArrayList()
    private val values = ArrayList<String>()
    private var maxNumberValues = 0

    fun close() {
        csvWriter.close(headers)
    }

    fun writeln() {
        csvWriter.writeln(values, maxNumberValues)
    }

    fun clear() {
        values.fill("")
    }

    fun set(header: String?, value: Any?) {
        var header = header
        var value = value
        if (header == null) {
            header = "null"
        }

        if (value == null) {
            value = "null"
        }

        for (i in headers.indices) {
            if (headers[i].compareTo(header) == 0) {
                values[i] = value.toString()
                return
            }
        }

        headers.add(header)
        values.add(value.toString())
    }

    fun setMaxNumberValues(numberValues: Int) {
        maxNumberValues = numberValues
    }
}