/**////////////////////////////////////////////////////////////////////////////////////////// */ // Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/**////////////////////////////////////////////////////////////////////////////////////////// */ // ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/**////////////////////////////////////////////////////////////////////////////////////////// */
package com.garmin.fit.csv

import com.garmin.fit.Factory.createMesg
import com.garmin.fit.Mesg
import com.garmin.fit.MesgDefinition
import com.garmin.fit.MesgDefinitionListener
import com.garmin.fit.MesgListener
import com.garmin.fit.MesgSource

/**
 * Listens to incoming mesg definitions and data messages and filters
 * them by name - Once filtered the messages are passed along to whoever
 * is listening.
 * 
 */
class MesgFilter : MesgListener, MesgDefinitionListener, MesgSource {
    private val mesgListeners = ArrayList<MesgListener>()
    private val mesgDefListeners = ArrayList<MesgDefinitionListener>()
    private var mesgDefinitionsToOutput: HashSet<String>? = null
    private var mesgDefinitionsToIgnore: HashSet<String>? = null
    private var mesgToOutput: HashSet<String>? = null
    private var mesgToIgnore: HashSet<String>? = null
    private var outputMesgDefinitions = true
    private var outputMesg = true

    override fun addListener(mesgListener: MesgListener) {
        if (!mesgListeners.contains(mesgListener)) {
            mesgListeners.add(mesgListener)
        }
    }

    fun addListener(mesgDefinitionListener: MesgDefinitionListener) {
        if (!mesgDefListeners.contains(mesgDefinitionListener)) {
            mesgDefListeners.add(mesgDefinitionListener)
        }
    }

    fun setMesgDefinitionsToOutput(inputMesgDefinitionsToOutput: HashSet<String>) {
        if (mesgDefinitionsToIgnore != null) {
            throw UnsupportedOperationException("Setting both an include filter and an exclude filter not supported.")
        }

        this.mesgDefinitionsToOutput = inputMesgDefinitionsToOutput
        if (this.mesgDefinitionsToOutput!!.contains("none")) {
            this.outputMesgDefinitions = false
        }
    }

    fun setMesgDefinitionsToIgnore(inputMesgDefinitionsToIgnore: HashSet<String>) {
        if (mesgDefinitionsToOutput != null) {
            throw UnsupportedOperationException("Setting both an include filter and an exclude filter not supported.")
        }

        this.mesgDefinitionsToIgnore = inputMesgDefinitionsToIgnore
        if (this.mesgDefinitionsToIgnore!!.contains("none")) {
            this.outputMesgDefinitions = false
        }
    }

    fun setDataMessagesToOutput(inputMesgToOutput: HashSet<String>) {
        this.mesgToOutput = inputMesgToOutput
        if (this.mesgToOutput!!.contains("none")) {
            this.outputMesg = false
        }
    }

    fun setDataMessagesToIgnore(inputMesgToIgnore: HashSet<String>) {
        this.mesgToIgnore = inputMesgToIgnore
        if (this.mesgToIgnore!!.contains("none")) {
            this.outputMesg = false
        }
    }

    override fun onMesgDefinition(mesgDef: MesgDefinition) {
        var outputDefinition = true
        val mesg = createMesg(mesgDef.num)

        if (!this.outputMesgDefinitions) {
            outputDefinition = false
        } else {
            if (this.mesgDefinitionsToOutput != null && !this.mesgDefinitionsToOutput!!.isEmpty()) {
                outputDefinition = this.mesgDefinitionsToOutput!!.contains(mesg.name)
            } else if (this.mesgDefinitionsToIgnore != null && !this.mesgDefinitionsToIgnore!!.isEmpty()) {
                outputDefinition = if (this.mesgDefinitionsToIgnore!!.contains(mesg.name)) {
                    false // ignore definitions in ignore list
                } else {
                    true
                }
            } // else if no include or exclude list set, output the definition
        }

        if (outputDefinition) {
            for (mesgListener in mesgDefListeners) {
                mesgListener.onMesgDefinition(mesgDef)
            }
        }
    }

    override fun onMesg(mesg: Mesg) {
        var outputMessage = true

        if (!this.outputMesg) {
            outputMessage = false
        } else {
            if (this.mesgToOutput != null && !this.mesgToOutput!!.isEmpty()) {
                outputMessage = if (this.mesgToOutput!!.contains(mesg.name)) {
                    true
                } else {
                    false
                }
            } else if (this.mesgToIgnore != null && !this.mesgToIgnore!!.isEmpty()) {
                outputMessage = if (this.mesgToIgnore!!.contains(mesg.name)) {
                    false
                } else {
                    true
                }
            } // else if no include or exclude list set, output the message
        }

        if (outputMessage) {
            for (mesgListener in mesgListeners) {
                mesgListener.onMesg(mesg)
            }
        }
    }
}
